/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by UIBuilder
 * UIBuilder version: v2.1.0
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"


void __attribute__((weak)) screen_14_love_favorites_custom_created(void) {
}

void __attribute__((weak)) screen_14_love_favorites_button_1_x_custom_clicked(void) {
}

static void screen_14_love_favorites_button_1_x_clicked (lv_event_t *e) {
    screen_14_love_favorites_button_1_x_custom_clicked();
}

void __attribute__((weak)) screen_14_love_favorites_button_1_add_custom_clicked(void) {
}

static void screen_14_love_favorites_button_1_add_clicked (lv_event_t *e) {
    screen_14_love_favorites_button_1_add_custom_clicked();
}

void __attribute__((weak)) screen_14_love_favorites_button_2_edit_custom_clicked(void) {
}

static void screen_14_love_favorites_button_2_edit_clicked (lv_event_t *e) {
    screen_14_love_favorites_button_2_edit_custom_clicked();
}


void screen_14_love_favorites_create(ui_manager_t *ui)
{
    screen_14_love_favorites_t *scr = screen_14_love_favorites_get(ui);

    if (!ui->auto_del && scr->obj) {
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0xf2f2f2), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->container_1_bg
    scr->container_1_bg = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->container_1_bg, 0, 0);
    lv_obj_set_size(scr->container_1_bg, 1152, 576);
    lv_obj_set_scrollbar_mode(scr->container_1_bg, LV_SCROLLBAR_MODE_OFF);
    lv_obj_clear_flag(scr->container_1_bg, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->container_1_bg
    lv_obj_set_style_border_width(scr->container_1_bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_1_bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->container_1_bg, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->container_1_bg, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_1_bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_1_bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_1_bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_1_bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->container_2_favorites
    scr->container_2_favorites = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->container_2_favorites, 30, 30);
    lv_obj_set_size(scr->container_2_favorites, 1092, 516);
    lv_obj_set_scrollbar_mode(scr->container_2_favorites, LV_SCROLLBAR_MODE_OFF);
    lv_obj_clear_flag(scr->container_2_favorites, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->container_2_favorites
    lv_obj_set_style_border_width(scr->container_2_favorites, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_2_favorites, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->container_2_favorites, lv_color_hex(0xf2f2f2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_2_favorites, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_2_favorites, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_2_favorites, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_2_favorites, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_0_favorites
    scr->label_0_favorites = lv_label_create(scr->container_2_favorites);
    lv_label_set_text(scr->label_0_favorites, "favorites");
    lv_label_set_long_mode(scr->label_0_favorites, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_0_favorites, 296, 5);
    lv_obj_set_size(scr->label_0_favorites, 500, 50);

    // Set style of scr->label_0_favorites
    lv_obj_set_style_text_color(scr->label_0_favorites, lv_color_hex(0xc4300e), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_0_favorites, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_0_favorites, fs_montserratmedium_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->button_1_x
    scr->button_1_x = lv_btn_create(scr->container_2_favorites);
    lv_obj_t *button_1_x_label = lv_label_create(scr->button_1_x);
    lv_label_set_text(button_1_x_label, "");
    lv_obj_align(button_1_x_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->button_1_x, 1002, 5);
    lv_obj_set_size(scr->button_1_x, 80, 50);
    lv_obj_add_flag(scr->button_1_x, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->button_1_x
    lv_obj_set_style_shadow_width(scr->button_1_x, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->button_1_x, LVGL_IMAGE_PATH(icon_x.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->button_1_x, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->button_1_x, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->button_1_x, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(scr->button_1_x, 0, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(scr->button_1_x, 0, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(scr->button_1_x, 0, LV_PART_MAIN | LV_STATE_DISABLED);

    // Set event handler of scr->button_1_x
    lv_obj_add_event_cb(scr->button_1_x, screen_14_love_favorites_button_1_x_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->container_3_favorites
    scr->container_3_favorites = lv_obj_create(scr->container_2_favorites);
    lv_obj_set_pos(scr->container_3_favorites, 0, 125);
    lv_obj_set_size(scr->container_3_favorites, 1092, 390);
    lv_obj_set_scrollbar_mode(scr->container_3_favorites, LV_SCROLLBAR_MODE_OFF);
    lv_obj_clear_flag(scr->container_3_favorites, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->container_3_favorites
    lv_obj_set_style_border_width(scr->container_3_favorites, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_3_favorites, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->container_3_favorites, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->container_3_favorites, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_3_favorites, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_3_favorites, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_3_favorites, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_3_favorites, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->button_1_add
    scr->button_1_add = lv_btn_create(scr->container_2_favorites);
    lv_obj_t *button_1_add_label = lv_label_create(scr->button_1_add);
    lv_label_set_text(button_1_add_label, "");
    lv_obj_align(button_1_add_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->button_1_add, 912, 65);
    lv_obj_set_size(scr->button_1_add, 80, 50);
    lv_obj_add_flag(scr->button_1_add, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(scr->button_1_add, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->button_1_add
    lv_obj_set_style_shadow_width(scr->button_1_add, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->button_1_add, LVGL_IMAGE_PATH(icon_add.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->button_1_add, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->button_1_add, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->button_1_add, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(scr->button_1_add, 0, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(scr->button_1_add, 0, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(scr->button_1_add, 0, LV_PART_MAIN | LV_STATE_DISABLED);

    // Set event handler of scr->button_1_add
    lv_obj_add_event_cb(scr->button_1_add, screen_14_love_favorites_button_1_add_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->button_2_edit
    scr->button_2_edit = lv_btn_create(scr->container_2_favorites);
    lv_obj_t *button_2_edit_label = lv_label_create(scr->button_2_edit);
    lv_label_set_text(button_2_edit_label, "");
    lv_obj_align(button_2_edit_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->button_2_edit, 1002, 65);
    lv_obj_set_size(scr->button_2_edit, 80, 50);
    lv_obj_add_flag(scr->button_2_edit, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->button_2_edit
    lv_obj_set_style_shadow_width(scr->button_2_edit, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->button_2_edit, LVGL_IMAGE_PATH(icon_edit01.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->button_2_edit, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->button_2_edit, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->button_2_edit, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(scr->button_2_edit, 0, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(scr->button_2_edit, 0, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(scr->button_2_edit, 0, LV_PART_MAIN | LV_STATE_DISABLED);

    // Set event handler of scr->button_2_edit
    lv_obj_add_event_cb(scr->button_2_edit, screen_14_love_favorites_button_2_edit_clicked, LV_EVENT_CLICKED, NULL);

    screen_14_love_favorites_custom_created();
}


