/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by UIBuilder
 * UIBuilder version: v2.1.0
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"


void __attribute__((weak)) screen_11_show_all_custom_created(void) {
}

static void screen_11_show_all_container_1_bg_clicked (lv_event_t *e) {
    lv_obj_t *act_scr = lv_scr_act();
    if (!screen_is_loading(act_scr)) {
        // create screen_02_main
        screen_02_main_create(&ui_manager);
        // load screen_02_main
        lv_scr_load_anim(screen_02_main_get(&ui_manager)->obj, LV_SCR_LOAD_ANIM_NONE, 1, 0, ui_manager.auto_del);
    }
}

static void screen_11_show_all_button_1_x_clicked (lv_event_t *e) {
    lv_obj_t *act_scr = lv_scr_act();
    if (!screen_is_loading(act_scr)) {
        // create screen_02_main
        screen_02_main_create(&ui_manager);
        // load screen_02_main
        lv_scr_load_anim(screen_02_main_get(&ui_manager)->obj, LV_SCR_LOAD_ANIM_NONE, 1, 0, ui_manager.auto_del);
    }
}


void screen_11_show_all_create(ui_manager_t *ui)
{
    screen_11_show_all_t *scr = screen_11_show_all_get(ui);

    if (!ui->auto_del && scr->obj) {
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0xf2f2f2), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->container_1_bg
    scr->container_1_bg = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->container_1_bg, 0, 0);
    lv_obj_set_size(scr->container_1_bg, 1152, 576);
    lv_obj_set_scrollbar_mode(scr->container_1_bg, LV_SCROLLBAR_MODE_OFF);
    lv_obj_clear_flag(scr->container_1_bg, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->container_1_bg
    lv_obj_set_style_border_width(scr->container_1_bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_1_bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->container_1_bg, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->container_1_bg, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_1_bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_1_bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_1_bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_1_bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->container_1_bg
    lv_obj_add_event_cb(scr->container_1_bg, screen_11_show_all_container_1_bg_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->container_2_show_all
    scr->container_2_show_all = lv_obj_create(scr->container_1_bg);
    lv_obj_set_pos(scr->container_2_show_all, 30, 30);
    lv_obj_set_size(scr->container_2_show_all, 1092, 516);
    lv_obj_set_scrollbar_mode(scr->container_2_show_all, LV_SCROLLBAR_MODE_OFF);
    lv_obj_clear_flag(scr->container_2_show_all, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->container_2_show_all
    lv_obj_set_style_border_width(scr->container_2_show_all, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_2_show_all, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->container_2_show_all, lv_color_hex(0xf1f5f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_2_show_all, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_2_show_all, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_2_show_all, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_2_show_all, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_1_choose_mode
    scr->label_1_choose_mode = lv_label_create(scr->container_2_show_all);
    lv_label_set_text(scr->label_1_choose_mode, "选择食物Choose mode");
    lv_label_set_long_mode(scr->label_1_choose_mode, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_obj_set_pos(scr->label_1_choose_mode, 246, 5);
    lv_obj_set_size(scr->label_1_choose_mode, 600, 50);

    // Set style of scr->label_1_choose_mode
    lv_obj_set_style_border_opa(scr->label_1_choose_mode, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(scr->label_1_choose_mode, lv_color_hex(0xc4300e), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_1_choose_mode, lv_color_hex(0xc42f0d), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->label_1_choose_mode, lv_color_hex(0xc4300e), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_1_choose_mode, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_1_choose_mode, fs_montserratmedium_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->container_3_food
    scr->container_3_food = lv_obj_create(scr->container_2_show_all);
    lv_obj_set_pos(scr->container_3_food, 11, 60);
    lv_obj_set_size(scr->container_3_food, 1070, 445);
    lv_obj_set_scrollbar_mode(scr->container_3_food, LV_SCROLLBAR_MODE_AUTO);
    lv_obj_clear_flag(scr->container_3_food, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->container_3_food
    lv_obj_set_style_border_width(scr->container_3_food, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_3_food, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->container_3_food, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->container_3_food, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_3_food, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_3_food, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_3_food, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_3_food, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_0
    scr->image_0 = lv_img_create(scr->container_3_food);
    lv_img_set_src(scr->image_0, LVGL_IMAGE_PATH(food_00.png));
    lv_img_set_pivot(scr->image_0, 50, 50);
    lv_img_set_offset_x(scr->image_0, 0);
    lv_img_set_offset_y(scr->image_0, 0);
    lv_img_set_angle(scr->image_0, 0);
    lv_obj_set_pos(scr->image_0, 20, 0);
    lv_obj_add_flag(scr->image_0, LV_OBJ_FLAG_CLICKABLE);

    // Init scr->image_1
    scr->image_1 = lv_img_create(scr->container_3_food);
    lv_img_set_src(scr->image_1, LVGL_IMAGE_PATH(food_01.png));
    lv_img_set_pivot(scr->image_1, 50, 50);
    lv_img_set_offset_x(scr->image_1, 0);
    lv_img_set_offset_y(scr->image_1, 0);
    lv_img_set_angle(scr->image_1, 0);
    lv_obj_set_pos(scr->image_1, 230, 0);
    lv_obj_add_flag(scr->image_1, LV_OBJ_FLAG_CLICKABLE);

    // Init scr->image_2
    scr->image_2 = lv_img_create(scr->container_3_food);
    lv_img_set_src(scr->image_2, LVGL_IMAGE_PATH(food_02.png));
    lv_img_set_pivot(scr->image_2, 50, 50);
    lv_img_set_offset_x(scr->image_2, 0);
    lv_img_set_offset_y(scr->image_2, 0);
    lv_img_set_angle(scr->image_2, 0);
    lv_obj_set_pos(scr->image_2, 440, 0);
    lv_obj_add_flag(scr->image_2, LV_OBJ_FLAG_CLICKABLE);

    // Init scr->image_3
    scr->image_3 = lv_img_create(scr->container_3_food);
    lv_img_set_src(scr->image_3, LVGL_IMAGE_PATH(food_03.png));
    lv_img_set_pivot(scr->image_3, 50, 50);
    lv_img_set_offset_x(scr->image_3, 0);
    lv_img_set_offset_y(scr->image_3, 0);
    lv_img_set_angle(scr->image_3, 0);
    lv_obj_set_pos(scr->image_3, 650, 0);
    lv_obj_add_flag(scr->image_3, LV_OBJ_FLAG_CLICKABLE);

    // Init scr->image_4
    scr->image_4 = lv_img_create(scr->container_3_food);
    lv_img_set_src(scr->image_4, LVGL_IMAGE_PATH(food_04.png));
    lv_img_set_pivot(scr->image_4, 50, 50);
    lv_img_set_offset_x(scr->image_4, 0);
    lv_img_set_offset_y(scr->image_4, 0);
    lv_img_set_angle(scr->image_4, 0);
    lv_obj_set_pos(scr->image_4, 860, 0);
    lv_obj_add_flag(scr->image_4, LV_OBJ_FLAG_CLICKABLE);

    // Init scr->image_5
    scr->image_5 = lv_img_create(scr->container_3_food);
    lv_img_set_src(scr->image_5, LVGL_IMAGE_PATH(food_05.png));
    lv_img_set_pivot(scr->image_5, 50, 50);
    lv_img_set_offset_x(scr->image_5, 0);
    lv_img_set_offset_y(scr->image_5, 0);
    lv_img_set_angle(scr->image_5, 0);
    lv_obj_set_pos(scr->image_5, 20, 178);
    lv_obj_add_flag(scr->image_5, LV_OBJ_FLAG_CLICKABLE);

    // Init scr->image_6
    scr->image_6 = lv_img_create(scr->container_3_food);
    lv_img_set_src(scr->image_6, LVGL_IMAGE_PATH(food_06.png));
    lv_img_set_pivot(scr->image_6, 50, 50);
    lv_img_set_offset_x(scr->image_6, 0);
    lv_img_set_offset_y(scr->image_6, 0);
    lv_img_set_angle(scr->image_6, 0);
    lv_obj_set_pos(scr->image_6, 230, 178);
    lv_obj_add_flag(scr->image_6, LV_OBJ_FLAG_CLICKABLE);

    // Init scr->image_7
    scr->image_7 = lv_img_create(scr->container_3_food);
    lv_img_set_src(scr->image_7, LVGL_IMAGE_PATH(food_07.png));
    lv_img_set_pivot(scr->image_7, 50, 50);
    lv_img_set_offset_x(scr->image_7, 0);
    lv_img_set_offset_y(scr->image_7, 0);
    lv_img_set_angle(scr->image_7, 0);
    lv_obj_set_pos(scr->image_7, 440, 178);
    lv_obj_add_flag(scr->image_7, LV_OBJ_FLAG_CLICKABLE);

    // Init scr->image_8
    scr->image_8 = lv_img_create(scr->container_3_food);
    lv_img_set_src(scr->image_8, LVGL_IMAGE_PATH(food_08.png));
    lv_img_set_pivot(scr->image_8, 50, 50);
    lv_img_set_offset_x(scr->image_8, 0);
    lv_img_set_offset_y(scr->image_8, 0);
    lv_img_set_angle(scr->image_8, 0);
    lv_obj_set_pos(scr->image_8, 650, 178);
    lv_obj_add_flag(scr->image_8, LV_OBJ_FLAG_CLICKABLE);

    // Init scr->image_9
    scr->image_9 = lv_img_create(scr->container_3_food);
    lv_img_set_src(scr->image_9, LVGL_IMAGE_PATH(food_09.png));
    lv_img_set_pivot(scr->image_9, 50, 50);
    lv_img_set_offset_x(scr->image_9, 0);
    lv_img_set_offset_y(scr->image_9, 0);
    lv_img_set_angle(scr->image_9, 0);
    lv_obj_set_pos(scr->image_9, 860, 178);
    lv_obj_add_flag(scr->image_9, LV_OBJ_FLAG_CLICKABLE);

    // Init scr->image_10
    scr->image_10 = lv_img_create(scr->container_3_food);
    lv_img_set_src(scr->image_10, LVGL_IMAGE_PATH(food_10.png));
    lv_img_set_pivot(scr->image_10, 50, 50);
    lv_img_set_offset_x(scr->image_10, 0);
    lv_img_set_offset_y(scr->image_10, 0);
    lv_img_set_angle(scr->image_10, 0);
    lv_obj_set_pos(scr->image_10, 20, 356);
    lv_obj_add_flag(scr->image_10, LV_OBJ_FLAG_CLICKABLE);

    // Init scr->image_11
    scr->image_11 = lv_img_create(scr->container_3_food);
    lv_img_set_src(scr->image_11, LVGL_IMAGE_PATH(food_11.png));
    lv_img_set_pivot(scr->image_11, 50, 50);
    lv_img_set_offset_x(scr->image_11, 0);
    lv_img_set_offset_y(scr->image_11, 0);
    lv_img_set_angle(scr->image_11, 0);
    lv_obj_set_pos(scr->image_11, 230, 356);
    lv_obj_add_flag(scr->image_11, LV_OBJ_FLAG_CLICKABLE);

    // Init scr->image_12
    scr->image_12 = lv_img_create(scr->container_3_food);
    lv_img_set_src(scr->image_12, LVGL_IMAGE_PATH(food_12.png));
    lv_img_set_pivot(scr->image_12, 50, 50);
    lv_img_set_offset_x(scr->image_12, 0);
    lv_img_set_offset_y(scr->image_12, 0);
    lv_img_set_angle(scr->image_12, 0);
    lv_obj_set_pos(scr->image_12, 440, 356);
    lv_obj_add_flag(scr->image_12, LV_OBJ_FLAG_CLICKABLE);

    // Init scr->image_13
    scr->image_13 = lv_img_create(scr->container_3_food);
    lv_img_set_src(scr->image_13, LVGL_IMAGE_PATH(food_13.png));
    lv_img_set_pivot(scr->image_13, 50, 50);
    lv_img_set_offset_x(scr->image_13, 0);
    lv_img_set_offset_y(scr->image_13, 0);
    lv_img_set_angle(scr->image_13, 0);
    lv_obj_set_pos(scr->image_13, 650, 356);
    lv_obj_add_flag(scr->image_13, LV_OBJ_FLAG_CLICKABLE);

    // Init scr->image_14
    scr->image_14 = lv_img_create(scr->container_3_food);
    lv_img_set_src(scr->image_14, LVGL_IMAGE_PATH(food_14.png));
    lv_img_set_pivot(scr->image_14, 50, 50);
    lv_img_set_offset_x(scr->image_14, 0);
    lv_img_set_offset_y(scr->image_14, 0);
    lv_img_set_angle(scr->image_14, 0);
    lv_obj_set_pos(scr->image_14, 860, 356);
    lv_obj_add_flag(scr->image_14, LV_OBJ_FLAG_CLICKABLE);

    // Init scr->image_15
    scr->image_15 = lv_img_create(scr->container_3_food);
    lv_img_set_src(scr->image_15, LVGL_IMAGE_PATH(food_15.png));
    lv_img_set_pivot(scr->image_15, 50, 50);
    lv_img_set_offset_x(scr->image_15, 0);
    lv_img_set_offset_y(scr->image_15, 0);
    lv_img_set_angle(scr->image_15, 0);
    lv_obj_set_pos(scr->image_15, 20, 534);
    lv_obj_add_flag(scr->image_15, LV_OBJ_FLAG_CLICKABLE);

    // Init scr->image_16
    scr->image_16 = lv_img_create(scr->container_3_food);
    lv_img_set_src(scr->image_16, LVGL_IMAGE_PATH(food_16.png));
    lv_img_set_pivot(scr->image_16, 50, 50);
    lv_img_set_offset_x(scr->image_16, 0);
    lv_img_set_offset_y(scr->image_16, 0);
    lv_img_set_angle(scr->image_16, 0);
    lv_obj_set_pos(scr->image_16, 230, 534);
    lv_obj_add_flag(scr->image_16, LV_OBJ_FLAG_CLICKABLE);

    // Init scr->button_1_x
    scr->button_1_x = lv_btn_create(scr->container_2_show_all);
    lv_obj_t *button_1_x_label = lv_label_create(scr->button_1_x);
    lv_label_set_text(button_1_x_label, "");
    lv_obj_align(button_1_x_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->button_1_x, 1002, 5);
    lv_obj_set_size(scr->button_1_x, 80, 50);

    // Set style of scr->button_1_x
    lv_obj_set_style_shadow_width(scr->button_1_x, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->button_1_x, LVGL_IMAGE_PATH(icon_x.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->button_1_x, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->button_1_x, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->button_1_x, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(scr->button_1_x, 0, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(scr->button_1_x, 0, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(scr->button_1_x, 0, LV_PART_MAIN | LV_STATE_DISABLED);

    // Set event handler of scr->button_1_x
    lv_obj_add_event_cb(scr->button_1_x, screen_11_show_all_button_1_x_clicked, LV_EVENT_CLICKED, NULL);

    screen_11_show_all_custom_created();
}


