/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by UIBuilder
 * UIBuilder version: v2.1.0
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"


void __attribute__((weak)) screen_07_clock_custom_created(void) {
}
void __attribute__((weak)) screen_07_clock_custom_loaded(void) {
}

static void screen_07_clock_loaded (lv_event_t *e) {
    screen_07_clock_custom_loaded();
}

static void screen_07_clock_button_1_back_clicked (lv_event_t *e) {
    lv_obj_t *act_scr = lv_scr_act();
    if (!screen_is_loading(act_scr)) {
        // create screen_03_setting
        screen_03_setting_create(&ui_manager);
        // load screen_03_setting
        lv_scr_load_anim(screen_03_setting_get(&ui_manager)->obj, LV_SCR_LOAD_ANIM_NONE, 1, 0, ui_manager.auto_del);
    }
}

void __attribute__((weak)) screen_07_clock_switch_1_24_hour_custom_clicked(void) {
}

static void screen_07_clock_switch_1_24_hour_clicked (lv_event_t *e) {
    screen_07_clock_switch_1_24_hour_custom_clicked();
}

void __attribute__((weak)) screen_07_clock_container_7_am_custom_clicked(void) {
}

static void screen_07_clock_container_7_am_clicked (lv_event_t *e) {
    screen_07_clock_container_7_am_custom_clicked();
}

void __attribute__((weak)) screen_07_clock_container_8_pm_custom_clicked(void) {
}

static void screen_07_clock_container_8_pm_clicked (lv_event_t *e) {
    screen_07_clock_container_8_pm_custom_clicked();
}

void __attribute__((weak)) screen_07_clock_button_1_ok_custom_clicked(void) {
}

static void screen_07_clock_button_1_ok_clicked (lv_event_t *e) {
    screen_07_clock_button_1_ok_custom_clicked();
}

void __attribute__((weak)) screen_07_clock_container_3_display_custom_clicked(void) {
}

static void screen_07_clock_container_3_display_clicked (lv_event_t *e) {
    screen_07_clock_container_3_display_custom_clicked();
}

void __attribute__((weak)) screen_07_clock_container_4_clock_custom_clicked(void) {
}

static void screen_07_clock_container_4_clock_clicked (lv_event_t *e) {
    screen_07_clock_container_4_clock_custom_clicked();
}


void screen_07_clock_create(ui_manager_t *ui)
{
    screen_07_clock_t *scr = screen_07_clock_get(ui);

    if (!ui->auto_del && scr->obj) {
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0xf2f2f2), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->obj
    lv_obj_add_event_cb(scr->obj, screen_07_clock_loaded, LV_EVENT_SCREEN_LOADED, NULL);

    // Init scr->button_1_back
    scr->button_1_back = lv_btn_create(scr->obj);
    lv_obj_t *button_1_back_label = lv_label_create(scr->button_1_back);
    lv_label_set_text(button_1_back_label, "");
    lv_obj_align(button_1_back_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->button_1_back, 5, 20);
    lv_obj_set_size(scr->button_1_back, 80, 40);

    // Set style of scr->button_1_back
    lv_obj_set_style_shadow_width(scr->button_1_back, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->button_1_back, LVGL_IMAGE_PATH(back.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->button_1_back, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->button_1_back, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->button_1_back
    lv_obj_add_event_cb(scr->button_1_back, screen_07_clock_button_1_back_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->label_0_clock
    scr->label_0_clock = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_0_clock, "Clock");
    lv_label_set_long_mode(scr->label_0_clock, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_0_clock, 326, 15);
    lv_obj_set_size(scr->label_0_clock, 500, 50);

    // Set style of scr->label_0_clock
    lv_obj_set_style_text_color(scr->label_0_clock, lv_color_hex(0xc4330f), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_0_clock, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_0_clock, fs_montserratmedium_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->container_1
    scr->container_1 = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->container_1, 30, 82);
    lv_obj_set_size(scr->container_1, 1092, 72);
    lv_obj_set_scrollbar_mode(scr->container_1, LV_SCROLLBAR_MODE_OFF);
    lv_obj_clear_flag(scr->container_1, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->container_1
    lv_obj_set_style_border_width(scr->container_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_1_24_hour
    scr->label_1_24_hour = lv_label_create(scr->container_1);
    lv_label_set_text(scr->label_1_24_hour, "24-hour System");
    lv_label_set_long_mode(scr->label_1_24_hour, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_1_24_hour, 20, 20);
    lv_obj_set_size(scr->label_1_24_hour, 211, 24);

    // Set style of scr->label_1_24_hour
    lv_obj_set_style_text_color(scr->label_1_24_hour, lv_color_hex(0x615f5f), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_1_24_hour, fs_montserratmedium_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->switch_1_24_hour
    scr->switch_1_24_hour = lv_switch_create(scr->container_1);
    lv_obj_set_pos(scr->switch_1_24_hour, 234, 17);
    lv_obj_set_size(scr->switch_1_24_hour, 99, 41);

    // Set style of scr->switch_1_24_hour
    lv_obj_set_style_bg_color(scr->switch_1_24_hour, lv_color_hex(0xa95806), LV_PART_INDICATOR | LV_STATE_CHECKED);

    // Set event handler of scr->switch_1_24_hour
    lv_obj_add_event_cb(scr->switch_1_24_hour, screen_07_clock_switch_1_24_hour_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->container_4_am_pm
    scr->container_4_am_pm = lv_obj_create(scr->container_1);
    lv_obj_set_pos(scr->container_4_am_pm, 658, 5);
    lv_obj_set_size(scr->container_4_am_pm, 411, 62);
    lv_obj_set_scrollbar_mode(scr->container_4_am_pm, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->container_4_am_pm
    lv_obj_set_style_border_width(scr->container_4_am_pm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_4_am_pm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->container_4_am_pm, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->container_4_am_pm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_4_am_pm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_4_am_pm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_4_am_pm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_4_am_pm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_2_clock
    scr->label_2_clock = lv_label_create(scr->container_4_am_pm);
    lv_label_set_text(scr->label_2_clock, "Clock");
    lv_label_set_long_mode(scr->label_2_clock, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_2_clock, 5, 14);
    lv_obj_set_size(scr->label_2_clock, 95, 34);

    // Set style of scr->label_2_clock
    lv_obj_set_style_text_color(scr->label_2_clock, lv_color_hex(0x615f5f), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_2_clock, fs_montserratmedium_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->container_7_am
    scr->container_7_am = lv_obj_create(scr->container_4_am_pm);
    lv_obj_set_pos(scr->container_7_am, 135, 0);
    lv_obj_set_size(scr->container_7_am, 132, 62);
    lv_obj_set_scrollbar_mode(scr->container_7_am, LV_SCROLLBAR_MODE_OFF);
    lv_obj_add_flag(scr->container_7_am, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->container_7_am
    lv_obj_set_style_border_width(scr->container_7_am, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_7_am, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->container_7_am, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->container_7_am, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_7_am, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_7_am, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_7_am, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_7_am, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->container_7_am
    lv_obj_add_event_cb(scr->container_7_am, screen_07_clock_container_7_am_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->label_3_am
    scr->label_3_am = lv_label_create(scr->container_7_am);
    lv_label_set_text(scr->label_3_am, "AM");
    lv_label_set_long_mode(scr->label_3_am, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_3_am, 32, 14);
    lv_obj_set_size(scr->label_3_am, 100, 34);

    // Set style of scr->label_3_am
    lv_obj_set_style_text_color(scr->label_3_am, lv_color_hex(0x615f5f), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_3_am, fs_montserratmedium_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_7_am
    scr->image_7_am = lv_img_create(scr->container_7_am);
    lv_img_set_src(scr->image_7_am, LVGL_IMAGE_PATH(set_time1.png));
    lv_img_set_pivot(scr->image_7_am, 50, 50);
    lv_img_set_offset_x(scr->image_7_am, 0);
    lv_img_set_offset_y(scr->image_7_am, 0);
    lv_img_set_angle(scr->image_7_am, 0);
    lv_obj_set_pos(scr->image_7_am, 0, 20);

    // Init scr->container_8_pm
    scr->container_8_pm = lv_obj_create(scr->container_4_am_pm);
    lv_obj_set_pos(scr->container_8_pm, 277, 0);
    lv_obj_set_size(scr->container_8_pm, 132, 62);
    lv_obj_set_scrollbar_mode(scr->container_8_pm, LV_SCROLLBAR_MODE_OFF);
    lv_obj_add_flag(scr->container_8_pm, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->container_8_pm
    lv_obj_set_style_border_width(scr->container_8_pm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_8_pm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->container_8_pm, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->container_8_pm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_8_pm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_8_pm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_8_pm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_8_pm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->container_8_pm
    lv_obj_add_event_cb(scr->container_8_pm, screen_07_clock_container_8_pm_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->label_4_pm
    scr->label_4_pm = lv_label_create(scr->container_8_pm);
    lv_label_set_text(scr->label_4_pm, "PM");
    lv_label_set_long_mode(scr->label_4_pm, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_4_pm, 32, 14);
    lv_obj_set_size(scr->label_4_pm, 100, 34);

    // Set style of scr->label_4_pm
    lv_obj_set_style_text_color(scr->label_4_pm, lv_color_hex(0x615f5f), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_4_pm, fs_montserratmedium_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_8_pm
    scr->image_8_pm = lv_img_create(scr->container_8_pm);
    lv_img_set_src(scr->image_8_pm, LVGL_IMAGE_PATH(set_time0.png));
    lv_img_set_pivot(scr->image_8_pm, 50, 50);
    lv_img_set_offset_x(scr->image_8_pm, 0);
    lv_img_set_offset_y(scr->image_8_pm, 0);
    lv_img_set_angle(scr->image_8_pm, 0);
    lv_obj_set_pos(scr->image_8_pm, 0, 20);

    // Init scr->container_2
    scr->container_2 = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->container_2, 31, 172);
    lv_obj_set_size(scr->container_2, 1092, 275);
    lv_obj_set_scrollbar_mode(scr->container_2, LV_SCROLLBAR_MODE_OFF);
    lv_obj_clear_flag(scr->container_2, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->container_2
    lv_obj_set_style_border_width(scr->container_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_5_time
    scr->label_5_time = lv_label_create(scr->container_2);
    lv_label_set_text(scr->label_5_time, "Time");
    lv_label_set_long_mode(scr->label_5_time, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_5_time, 471, 10);
    lv_obj_set_size(scr->label_5_time, 150, 34);

    // Set style of scr->label_5_time
    lv_obj_set_style_text_color(scr->label_5_time, lv_color_hex(0x615f5f), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_5_time, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_5_time, fs_montserratmedium_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->button_1_ok
    scr->button_1_ok = lv_btn_create(scr->container_2);
    lv_obj_t *button_1_ok_label = lv_label_create(scr->button_1_ok);
    lv_label_set_text(button_1_ok_label, "OK");
    lv_obj_align(button_1_ok_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->button_1_ok, 895, 139);
    lv_obj_set_size(scr->button_1_ok, 95, 32);

    // Set style of scr->button_1_ok
    lv_obj_set_style_shadow_width(scr->button_1_ok, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->button_1_ok, lv_color_hex(0xc4330f), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->button_1_ok, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->button_1_ok, fs_montserratmedium_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->button_1_ok
    lv_obj_add_event_cb(scr->button_1_ok, screen_07_clock_button_1_ok_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->roller_1_12h
    scr->roller_1_12h = lv_roller_create(scr->container_2);
    lv_roller_set_options(scr->roller_1_12h, "01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12", LV_ROLLER_MODE_INFINITE);
    lv_roller_set_visible_row_count(scr->roller_1_12h, 5);
    lv_obj_set_pos(scr->roller_1_12h, 400, 27);
    lv_obj_set_size(scr->roller_1_12h, 54, 241);
    lv_obj_add_flag(scr->roller_1_12h, LV_OBJ_FLAG_HIDDEN);

    // Set style of scr->roller_1_12h
    lv_obj_set_style_bg_opa(scr->roller_1_12h, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->roller_1_12h, lv_color_hex(0x615f5f), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(scr->roller_1_12h, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->roller_1_12h, fs_montserratmedium_26, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->roller_1_12h, lv_color_hex(0xa95806), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->roller_1_12h, 0, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->roller_1_12h, fs_montserratmedium_26, LV_PART_SELECTED | LV_STATE_DEFAULT);

    // Init scr->roller_2_24h
    scr->roller_2_24h = lv_roller_create(scr->container_2);
    lv_roller_set_options(scr->roller_2_24h, "00\n01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23", LV_ROLLER_MODE_INFINITE);
    lv_roller_set_visible_row_count(scr->roller_2_24h, 5);
    lv_obj_set_pos(scr->roller_2_24h, 400, 27);
    lv_obj_set_size(scr->roller_2_24h, 54, 240);

    // Set style of scr->roller_2_24h
    lv_obj_set_style_bg_opa(scr->roller_2_24h, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->roller_2_24h, lv_color_hex(0x615f5f), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(scr->roller_2_24h, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->roller_2_24h, fs_montserratmedium_26, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->roller_2_24h, lv_color_hex(0xa95806), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->roller_2_24h, 0, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->roller_2_24h, fs_montserratmedium_26, LV_PART_SELECTED | LV_STATE_DEFAULT);

    // Init scr->roller_3_m
    scr->roller_3_m = lv_roller_create(scr->container_2);
    lv_roller_set_options(scr->roller_3_m, "00\n01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31\n32\n33\n34\n35\n36\n37\n38\n39\n40\n41\n42\n43\n44\n45\n46\n47\n48\n49\n50\n51\n52\n53\n54\n55\n56\n57\n58\n59", LV_ROLLER_MODE_INFINITE);
    lv_roller_set_visible_row_count(scr->roller_3_m, 5);
    lv_obj_set_pos(scr->roller_3_m, 638, 27);
    lv_obj_set_size(scr->roller_3_m, 54, 240);

    // Set style of scr->roller_3_m
    lv_obj_set_style_bg_opa(scr->roller_3_m, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->roller_3_m, lv_color_hex(0x615f5f), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(scr->roller_3_m, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->roller_3_m, fs_montserratmedium_26, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->roller_3_m, lv_color_hex(0xa95806), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->roller_3_m, 0, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->roller_3_m, fs_montserratmedium_26, LV_PART_SELECTED | LV_STATE_DEFAULT);

    // Init scr->image_8
    scr->image_8 = lv_img_create(scr->container_2);
    lv_img_set_src(scr->image_8, LVGL_IMAGE_PATH(set_clock_white.png));
    lv_img_set_pivot(scr->image_8, 50, 50);
    lv_img_set_offset_x(scr->image_8, 0);
    lv_img_set_offset_y(scr->image_8, 0);
    lv_img_set_angle(scr->image_8, 0);
    lv_obj_set_pos(scr->image_8, 386, 120);

    // Init scr->image_9
    scr->image_9 = lv_img_create(scr->container_2);
    lv_img_set_src(scr->image_9, LVGL_IMAGE_PATH(set_clock_white.png));
    lv_img_set_pivot(scr->image_9, 50, 50);
    lv_img_set_offset_x(scr->image_9, 0);
    lv_img_set_offset_y(scr->image_9, 0);
    lv_img_set_angle(scr->image_9, 0);
    lv_obj_set_pos(scr->image_9, 385, 173);

    // Init scr->container_3
    scr->container_3 = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->container_3, 30, 471);
    lv_obj_set_size(scr->container_3, 1092, 72);
    lv_obj_set_scrollbar_mode(scr->container_3, LV_SCROLLBAR_MODE_OFF);
    lv_obj_clear_flag(scr->container_3, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->container_3
    lv_obj_set_style_border_width(scr->container_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_6_screensaver_time_display
    scr->label_6_screensaver_time_display = lv_label_create(scr->container_3);
    lv_label_set_text(scr->label_6_screensaver_time_display, "Screensaver time display");
    lv_label_set_long_mode(scr->label_6_screensaver_time_display, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_6_screensaver_time_display, 19, 19);
    lv_obj_set_size(scr->label_6_screensaver_time_display, 516, 34);

    // Set style of scr->label_6_screensaver_time_display
    lv_obj_set_style_text_color(scr->label_6_screensaver_time_display, lv_color_hex(0x615f5f), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_6_screensaver_time_display, fs_montserratmedium_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->container_3_display
    scr->container_3_display = lv_obj_create(scr->container_3);
    lv_obj_set_pos(scr->container_3_display, 700, 5);
    lv_obj_set_size(scr->container_3_display, 175, 62);
    lv_obj_set_scrollbar_mode(scr->container_3_display, LV_SCROLLBAR_MODE_OFF);
    lv_obj_add_flag(scr->container_3_display, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->container_3_display
    lv_obj_set_style_border_width(scr->container_3_display, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_3_display, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->container_3_display, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->container_3_display, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_3_display, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_3_display, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_3_display, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_3_display, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->container_3_display
    lv_obj_add_event_cb(scr->container_3_display, screen_07_clock_container_3_display_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->label_7_digital
    scr->label_7_digital = lv_label_create(scr->container_3_display);
    lv_label_set_text(scr->label_7_digital, "Rmer Bun");
    lv_label_set_long_mode(scr->label_7_digital, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_7_digital, 32, 14);
    lv_obj_set_size(scr->label_7_digital, 140, 34);

    // Set style of scr->label_7_digital
    lv_obj_set_style_text_color(scr->label_7_digital, lv_color_hex(0x615f5f), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_7_digital, fs_montserratmedium_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_3_digital
    scr->image_3_digital = lv_img_create(scr->container_3_display);
    lv_img_set_src(scr->image_3_digital, LVGL_IMAGE_PATH(set_time1.png));
    lv_img_set_pivot(scr->image_3_digital, 50, 50);
    lv_img_set_offset_x(scr->image_3_digital, 0);
    lv_img_set_offset_y(scr->image_3_digital, 0);
    lv_img_set_angle(scr->image_3_digital, 0);
    lv_obj_set_pos(scr->image_3_digital, 0, 20);

    // Init scr->container_4_clock
    scr->container_4_clock = lv_obj_create(scr->container_3);
    lv_obj_set_pos(scr->container_4_clock, 907, 5);
    lv_obj_set_size(scr->container_4_clock, 175, 62);
    lv_obj_set_scrollbar_mode(scr->container_4_clock, LV_SCROLLBAR_MODE_OFF);
    lv_obj_add_flag(scr->container_4_clock, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->container_4_clock
    lv_obj_set_style_border_width(scr->container_4_clock, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_4_clock, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->container_4_clock, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->container_4_clock, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_4_clock, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_4_clock, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_4_clock, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_4_clock, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->container_4_clock
    lv_obj_add_event_cb(scr->container_4_clock, screen_07_clock_container_4_clock_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->label_8_clock
    scr->label_8_clock = lv_label_create(scr->container_4_clock);
    lv_label_set_text(scr->label_8_clock, "Clock");
    lv_label_set_long_mode(scr->label_8_clock, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_8_clock, 32, 14);
    lv_obj_set_size(scr->label_8_clock, 140, 34);

    // Set style of scr->label_8_clock
    lv_obj_set_style_text_color(scr->label_8_clock, lv_color_hex(0x615f5f), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_8_clock, fs_montserratmedium_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_4_clock
    scr->image_4_clock = lv_img_create(scr->container_4_clock);
    lv_img_set_src(scr->image_4_clock, LVGL_IMAGE_PATH(set_time0.png));
    lv_img_set_pivot(scr->image_4_clock, 50, 50);
    lv_img_set_offset_x(scr->image_4_clock, 0);
    lv_img_set_offset_y(scr->image_4_clock, 0);
    lv_img_set_angle(scr->image_4_clock, 0);
    lv_obj_set_pos(scr->image_4_clock, 0, 20);

    screen_07_clock_custom_created();
}


