/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by UIBuilder
 * UIBuilder version: v2.1.0
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"


void __attribute__((weak)) screen_03_setting_custom_created(void) {
}

static void screen_03_setting_container_1_display_clicked (lv_event_t *e) {
    lv_obj_t *act_scr = lv_scr_act();
    if (!screen_is_loading(act_scr)) {
        // create screen_04_display
        screen_04_display_create(&ui_manager);
        // load screen_04_display
        lv_scr_load_anim(screen_04_display_get(&ui_manager)->obj, LV_SCR_LOAD_ANIM_NONE, 1, 0, ui_manager.auto_del);
    }
}

static void screen_03_setting_container_2_language_clicked (lv_event_t *e) {
    lv_obj_t *act_scr = lv_scr_act();
    if (!screen_is_loading(act_scr)) {
        // create screen_05_language
        screen_05_language_create(&ui_manager);
        // load screen_05_language
        lv_scr_load_anim(screen_05_language_get(&ui_manager)->obj, LV_SCR_LOAD_ANIM_NONE, 1, 0, ui_manager.auto_del);
    }
}

static void screen_03_setting_container_3_brightness_clicked (lv_event_t *e) {
    lv_obj_t *act_scr = lv_scr_act();
    if (!screen_is_loading(act_scr)) {
        // create screen_06_brightness
        screen_06_brightness_create(&ui_manager);
        // load screen_06_brightness
        lv_scr_load_anim(screen_06_brightness_get(&ui_manager)->obj, LV_SCR_LOAD_ANIM_NONE, 1, 0, ui_manager.auto_del);
    }
}

static void screen_03_setting_container_4_clock_clicked (lv_event_t *e) {
    lv_obj_t *act_scr = lv_scr_act();
    if (!screen_is_loading(act_scr)) {
        // create screen_07_clock
        screen_07_clock_create(&ui_manager);
        // load screen_07_clock
        lv_scr_load_anim(screen_07_clock_get(&ui_manager)->obj, LV_SCR_LOAD_ANIM_NONE, 1, 0, ui_manager.auto_del);
    }
}

static void screen_03_setting_container_5_sound_clicked (lv_event_t *e) {
    lv_obj_t *act_scr = lv_scr_act();
    if (!screen_is_loading(act_scr)) {
        // create screen_08_sound
        screen_08_sound_create(&ui_manager);
        // load screen_08_sound
        lv_scr_load_anim(screen_08_sound_get(&ui_manager)->obj, LV_SCR_LOAD_ANIM_NONE, 1, 0, ui_manager.auto_del);
    }
}

static void screen_03_setting_container_6_f_to_c_clicked (lv_event_t *e) {
    lv_obj_t *act_scr = lv_scr_act();
    if (!screen_is_loading(act_scr)) {
        // create screen_09_F_to_C
        screen_09_F_to_C_create(&ui_manager);
        // load screen_09_F_to_C
        lv_scr_load_anim(screen_09_F_to_C_get(&ui_manager)->obj, LV_SCR_LOAD_ANIM_NONE, 1, 0, ui_manager.auto_del);
    }
}

static void screen_03_setting_container_7_version_clicked (lv_event_t *e) {
    lv_obj_t *act_scr = lv_scr_act();
    if (!screen_is_loading(act_scr)) {
        // create screen_10_version
        screen_10_version_create(&ui_manager);
        // load screen_10_version
        lv_scr_load_anim(screen_10_version_get(&ui_manager)->obj, LV_SCR_LOAD_ANIM_NONE, 1, 0, ui_manager.auto_del);
    }
}

static void screen_03_setting_container_8_restore_factory_settings_clicked (lv_event_t *e) {
    lv_obj_t *act_scr = lv_scr_act();
    if (!screen_is_loading(act_scr)) {
        // create screen_15_restore_factory_settings
        screen_15_restore_factory_settings_create(&ui_manager);
        // load screen_15_restore_factory_settings
        lv_scr_load_anim(screen_15_restore_factory_settings_get(&ui_manager)->obj, LV_SCR_LOAD_ANIM_NONE, 1, 0, ui_manager.auto_del);
    }
}

static void screen_03_setting_button_1_back_clicked (lv_event_t *e) {
    lv_obj_t *act_scr = lv_scr_act();
    if (!screen_is_loading(act_scr)) {
        // create screen_02_main
        screen_02_main_create(&ui_manager);
        // load screen_02_main
        lv_scr_load_anim(screen_02_main_get(&ui_manager)->obj, LV_SCR_LOAD_ANIM_NONE, 1, 0, ui_manager.auto_del);
    }
}


void screen_03_setting_create(ui_manager_t *ui)
{
    screen_03_setting_t *scr = screen_03_setting_get(ui);

    if (!ui->auto_del && scr->obj) {
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0xf2f2f2), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->container_1
    scr->container_1 = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->container_1, 0, 83);
    lv_obj_set_size(scr->container_1, 1152, 471);
    lv_obj_set_scrollbar_mode(scr->container_1, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->container_1
    lv_obj_set_style_border_width(scr->container_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->container_1, lv_color_hex(0xf5f5f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->container_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->container_1_display
    scr->container_1_display = lv_obj_create(scr->container_1);
    lv_obj_set_pos(scr->container_1_display, 30, 0);
    lv_obj_set_size(scr->container_1_display, 1092, 62);
    lv_obj_set_scrollbar_mode(scr->container_1_display, LV_SCROLLBAR_MODE_OFF);
    lv_obj_add_flag(scr->container_1_display, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->container_1_display
    lv_obj_set_style_border_width(scr->container_1_display, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_1_display, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_1_display, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_1_display, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_1_display, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_1_display, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->container_1_display
    lv_obj_add_event_cb(scr->container_1_display, screen_03_setting_container_1_display_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->label_1_display
    scr->label_1_display = lv_label_create(scr->container_1_display);
    lv_label_set_text(scr->label_1_display, "Display");
    lv_label_set_long_mode(scr->label_1_display, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_1_display, 70, 17);
    lv_obj_set_size(scr->label_1_display, 211, 24);

    // Set style of scr->label_1_display
    lv_obj_set_style_text_color(scr->label_1_display, lv_color_hex(0x615f5f), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_1_display, fs_montserratmedium_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_1_display
    scr->image_1_display = lv_img_create(scr->container_1_display);
    lv_img_set_src(scr->image_1_display, LVGL_IMAGE_PATH(set_icon1_display.png));
    lv_img_set_pivot(scr->image_1_display, 50, 50);
    lv_img_set_offset_x(scr->image_1_display, 0);
    lv_img_set_offset_y(scr->image_1_display, 0);
    lv_img_set_angle(scr->image_1_display, 0);
    lv_obj_set_pos(scr->image_1_display, 13, 13);

    // Init scr->container_2_language
    scr->container_2_language = lv_obj_create(scr->container_1);
    lv_obj_set_pos(scr->container_2_language, 30, 83);
    lv_obj_set_size(scr->container_2_language, 1092, 62);
    lv_obj_set_scrollbar_mode(scr->container_2_language, LV_SCROLLBAR_MODE_OFF);
    lv_obj_add_flag(scr->container_2_language, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->container_2_language
    lv_obj_set_style_border_width(scr->container_2_language, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_2_language, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_2_language, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_2_language, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_2_language, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_2_language, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->container_2_language
    lv_obj_add_event_cb(scr->container_2_language, screen_03_setting_container_2_language_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->label_2_language
    scr->label_2_language = lv_label_create(scr->container_2_language);
    lv_label_set_text(scr->label_2_language, "Language");
    lv_label_set_long_mode(scr->label_2_language, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_2_language, 70, 17);
    lv_obj_set_size(scr->label_2_language, 211, 24);

    // Set style of scr->label_2_language
    lv_obj_set_style_text_color(scr->label_2_language, lv_color_hex(0x615f5f), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_2_language, fs_montserratmedium_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_2_language
    scr->image_2_language = lv_img_create(scr->container_2_language);
    lv_img_set_src(scr->image_2_language, LVGL_IMAGE_PATH(set_icon2_language.png));
    lv_img_set_pivot(scr->image_2_language, 50, 50);
    lv_img_set_offset_x(scr->image_2_language, 0);
    lv_img_set_offset_y(scr->image_2_language, 0);
    lv_img_set_angle(scr->image_2_language, 0);
    lv_obj_set_pos(scr->image_2_language, 13, 13);

    // Init scr->container_3_brightness
    scr->container_3_brightness = lv_obj_create(scr->container_1);
    lv_obj_set_pos(scr->container_3_brightness, 30, 166);
    lv_obj_set_size(scr->container_3_brightness, 1092, 62);
    lv_obj_set_scrollbar_mode(scr->container_3_brightness, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->container_3_brightness
    lv_obj_set_style_border_width(scr->container_3_brightness, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_3_brightness, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_3_brightness, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_3_brightness, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_3_brightness, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_3_brightness, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->container_3_brightness
    lv_obj_add_event_cb(scr->container_3_brightness, screen_03_setting_container_3_brightness_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->label_3_brightness
    scr->label_3_brightness = lv_label_create(scr->container_3_brightness);
    lv_label_set_text(scr->label_3_brightness, "Brightness");
    lv_label_set_long_mode(scr->label_3_brightness, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_3_brightness, 70, 17);
    lv_obj_set_size(scr->label_3_brightness, 211, 24);

    // Set style of scr->label_3_brightness
    lv_obj_set_style_text_color(scr->label_3_brightness, lv_color_hex(0x615f5f), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_3_brightness, fs_montserratmedium_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_3_brightness
    scr->image_3_brightness = lv_img_create(scr->container_3_brightness);
    lv_img_set_src(scr->image_3_brightness, LVGL_IMAGE_PATH(set_icon3_brightness.png));
    lv_img_set_pivot(scr->image_3_brightness, 50, 50);
    lv_img_set_offset_x(scr->image_3_brightness, 0);
    lv_img_set_offset_y(scr->image_3_brightness, 0);
    lv_img_set_angle(scr->image_3_brightness, 0);
    lv_obj_set_pos(scr->image_3_brightness, 13, 13);

    // Init scr->container_4_clock
    scr->container_4_clock = lv_obj_create(scr->container_1);
    lv_obj_set_pos(scr->container_4_clock, 30, 249);
    lv_obj_set_size(scr->container_4_clock, 1092, 62);
    lv_obj_set_scrollbar_mode(scr->container_4_clock, LV_SCROLLBAR_MODE_OFF);
    lv_obj_add_flag(scr->container_4_clock, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->container_4_clock
    lv_obj_set_style_border_width(scr->container_4_clock, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_4_clock, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_4_clock, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_4_clock, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_4_clock, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_4_clock, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->container_4_clock
    lv_obj_add_event_cb(scr->container_4_clock, screen_03_setting_container_4_clock_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->label_4_clock
    scr->label_4_clock = lv_label_create(scr->container_4_clock);
    lv_label_set_text(scr->label_4_clock, "clock");
    lv_label_set_long_mode(scr->label_4_clock, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_4_clock, 70, 17);
    lv_obj_set_size(scr->label_4_clock, 211, 24);

    // Set style of scr->label_4_clock
    lv_obj_set_style_text_color(scr->label_4_clock, lv_color_hex(0x615f5f), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_4_clock, fs_montserratmedium_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_4_clock
    scr->image_4_clock = lv_img_create(scr->container_4_clock);
    lv_img_set_src(scr->image_4_clock, LVGL_IMAGE_PATH(set_icon4_clock.png));
    lv_img_set_pivot(scr->image_4_clock, 50, 50);
    lv_img_set_offset_x(scr->image_4_clock, 0);
    lv_img_set_offset_y(scr->image_4_clock, 0);
    lv_img_set_angle(scr->image_4_clock, 0);
    lv_obj_set_pos(scr->image_4_clock, 13, 13);

    // Init scr->container_5_sound
    scr->container_5_sound = lv_obj_create(scr->container_1);
    lv_obj_set_pos(scr->container_5_sound, 30, 332);
    lv_obj_set_size(scr->container_5_sound, 1092, 62);
    lv_obj_set_scrollbar_mode(scr->container_5_sound, LV_SCROLLBAR_MODE_OFF);
    lv_obj_add_flag(scr->container_5_sound, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->container_5_sound
    lv_obj_set_style_border_width(scr->container_5_sound, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_5_sound, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_5_sound, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_5_sound, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_5_sound, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_5_sound, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->container_5_sound
    lv_obj_add_event_cb(scr->container_5_sound, screen_03_setting_container_5_sound_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->label_5_sound
    scr->label_5_sound = lv_label_create(scr->container_5_sound);
    lv_label_set_text(scr->label_5_sound, "Sound");
    lv_label_set_long_mode(scr->label_5_sound, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_5_sound, 70, 17);
    lv_obj_set_size(scr->label_5_sound, 211, 24);

    // Set style of scr->label_5_sound
    lv_obj_set_style_text_color(scr->label_5_sound, lv_color_hex(0x615f5f), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_5_sound, fs_montserratmedium_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_5_sound
    scr->image_5_sound = lv_img_create(scr->container_5_sound);
    lv_img_set_src(scr->image_5_sound, LVGL_IMAGE_PATH(set_icon5_sound.png));
    lv_img_set_pivot(scr->image_5_sound, 50, 50);
    lv_img_set_offset_x(scr->image_5_sound, 0);
    lv_img_set_offset_y(scr->image_5_sound, 0);
    lv_img_set_angle(scr->image_5_sound, 0);
    lv_obj_set_pos(scr->image_5_sound, 13, 13);

    // Init scr->container_6_f_to_c
    scr->container_6_f_to_c = lv_obj_create(scr->container_1);
    lv_obj_set_pos(scr->container_6_f_to_c, 30, 415);
    lv_obj_set_size(scr->container_6_f_to_c, 1092, 62);
    lv_obj_set_scrollbar_mode(scr->container_6_f_to_c, LV_SCROLLBAR_MODE_OFF);
    lv_obj_add_flag(scr->container_6_f_to_c, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->container_6_f_to_c
    lv_obj_set_style_border_width(scr->container_6_f_to_c, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_6_f_to_c, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_6_f_to_c, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_6_f_to_c, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_6_f_to_c, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_6_f_to_c, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->container_6_f_to_c
    lv_obj_add_event_cb(scr->container_6_f_to_c, screen_03_setting_container_6_f_to_c_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->label_6_f_to_c
    scr->label_6_f_to_c = lv_label_create(scr->container_6_f_to_c);
    lv_label_set_text(scr->label_6_f_to_c, "°F to °C");
    lv_label_set_long_mode(scr->label_6_f_to_c, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_6_f_to_c, 70, 17);
    lv_obj_set_size(scr->label_6_f_to_c, 211, 24);

    // Set style of scr->label_6_f_to_c
    lv_obj_set_style_text_color(scr->label_6_f_to_c, lv_color_hex(0x615f5f), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_6_f_to_c, fs_montserratmedium_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_6_f_to_c
    scr->image_6_f_to_c = lv_img_create(scr->container_6_f_to_c);
    lv_img_set_src(scr->image_6_f_to_c, LVGL_IMAGE_PATH(set_icon6_f_c.png));
    lv_img_set_pivot(scr->image_6_f_to_c, 50, 50);
    lv_img_set_offset_x(scr->image_6_f_to_c, 0);
    lv_img_set_offset_y(scr->image_6_f_to_c, 0);
    lv_img_set_angle(scr->image_6_f_to_c, 0);
    lv_obj_set_pos(scr->image_6_f_to_c, 13, 13);

    // Init scr->container_7_version
    scr->container_7_version = lv_obj_create(scr->container_1);
    lv_obj_set_pos(scr->container_7_version, 30, 498);
    lv_obj_set_size(scr->container_7_version, 1092, 62);
    lv_obj_set_scrollbar_mode(scr->container_7_version, LV_SCROLLBAR_MODE_OFF);
    lv_obj_add_flag(scr->container_7_version, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->container_7_version
    lv_obj_set_style_border_width(scr->container_7_version, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_7_version, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_7_version, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_7_version, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_7_version, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_7_version, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->container_7_version
    lv_obj_add_event_cb(scr->container_7_version, screen_03_setting_container_7_version_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->label_7_version
    scr->label_7_version = lv_label_create(scr->container_7_version);
    lv_label_set_text(scr->label_7_version, "Version");
    lv_label_set_long_mode(scr->label_7_version, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_7_version, 70, 17);
    lv_obj_set_size(scr->label_7_version, 211, 24);

    // Set style of scr->label_7_version
    lv_obj_set_style_text_color(scr->label_7_version, lv_color_hex(0x615f5f), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_7_version, fs_montserratmedium_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_7_version
    scr->image_7_version = lv_img_create(scr->container_7_version);
    lv_img_set_src(scr->image_7_version, LVGL_IMAGE_PATH(set_icon7_version.png));
    lv_img_set_pivot(scr->image_7_version, 50, 50);
    lv_img_set_offset_x(scr->image_7_version, 0);
    lv_img_set_offset_y(scr->image_7_version, 0);
    lv_img_set_angle(scr->image_7_version, 0);
    lv_obj_set_pos(scr->image_7_version, 13, 13);

    // Init scr->container_8_restore_factory_settings
    scr->container_8_restore_factory_settings = lv_obj_create(scr->container_1);
    lv_obj_set_pos(scr->container_8_restore_factory_settings, 30, 581);
    lv_obj_set_size(scr->container_8_restore_factory_settings, 1092, 62);
    lv_obj_set_scrollbar_mode(scr->container_8_restore_factory_settings, LV_SCROLLBAR_MODE_OFF);
    lv_obj_add_flag(scr->container_8_restore_factory_settings, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->container_8_restore_factory_settings
    lv_obj_set_style_border_width(scr->container_8_restore_factory_settings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_8_restore_factory_settings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_8_restore_factory_settings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_8_restore_factory_settings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_8_restore_factory_settings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_8_restore_factory_settings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->container_8_restore_factory_settings
    lv_obj_add_event_cb(scr->container_8_restore_factory_settings, screen_03_setting_container_8_restore_factory_settings_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->label_8_restore_factory_settings
    scr->label_8_restore_factory_settings = lv_label_create(scr->container_8_restore_factory_settings);
    lv_label_set_text(scr->label_8_restore_factory_settings, "Factory data reset");
    lv_label_set_long_mode(scr->label_8_restore_factory_settings, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_8_restore_factory_settings, 70, 17);
    lv_obj_set_size(scr->label_8_restore_factory_settings, 211, 24);

    // Set style of scr->label_8_restore_factory_settings
    lv_obj_set_style_text_color(scr->label_8_restore_factory_settings, lv_color_hex(0x615f5f), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_8_restore_factory_settings, fs_montserratmedium_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_8_restore_factory_settings
    scr->image_8_restore_factory_settings = lv_img_create(scr->container_8_restore_factory_settings);
    lv_img_set_src(scr->image_8_restore_factory_settings, LVGL_IMAGE_PATH(set_icon7_version.png));
    lv_img_set_pivot(scr->image_8_restore_factory_settings, 50, 50);
    lv_img_set_offset_x(scr->image_8_restore_factory_settings, 0);
    lv_img_set_offset_y(scr->image_8_restore_factory_settings, 0);
    lv_img_set_angle(scr->image_8_restore_factory_settings, 0);
    lv_obj_set_pos(scr->image_8_restore_factory_settings, 13, 13);

    // Init scr->button_1_back
    scr->button_1_back = lv_btn_create(scr->obj);
    lv_obj_t *button_1_back_label = lv_label_create(scr->button_1_back);
    lv_label_set_text(button_1_back_label, "");
    lv_obj_align(button_1_back_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->button_1_back, 5, 20);
    lv_obj_set_size(scr->button_1_back, 80, 40);

    // Set style of scr->button_1_back
    lv_obj_set_style_shadow_width(scr->button_1_back, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->button_1_back, LVGL_IMAGE_PATH(back.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->button_1_back, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->button_1_back, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->button_1_back
    lv_obj_add_event_cb(scr->button_1_back, screen_03_setting_button_1_back_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->label_0_settings
    scr->label_0_settings = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_0_settings, "Settings");
    lv_label_set_long_mode(scr->label_0_settings, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_0_settings, 326, 15);
    lv_obj_set_size(scr->label_0_settings, 500, 50);

    // Set style of scr->label_0_settings
    lv_obj_set_style_text_color(scr->label_0_settings, lv_color_hex(0xc4330f), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_0_settings, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_0_settings, fs_montserratmedium_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    screen_03_setting_custom_created();
}


