/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by UIBuilder
 * UIBuilder version: v2.1.0
 */

#ifndef _UI_OBJECTS
#define _UI_OBJECTS

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"
#include "lv_conf_custom.h"


typedef struct {
    lv_obj_t *obj;
    lv_obj_t *container_1_off_show_set;
    lv_obj_t *image_1_off;
    lv_obj_t *image_2_show_all_food;
    lv_obj_t *image_3_settings;
    lv_obj_t *image_4_love;
    lv_obj_t *container_2_main;
    lv_obj_t *container_2_1;
    lv_obj_t *label_10_food_name;
    lv_obj_t *container_2_3_run;
    lv_obj_t *arc_1;
    lv_obj_t *image_run;
    lv_obj_t *label_run_cancel;
    lv_obj_t *label_run_timer;
    lv_obj_t *label_run_shake;
    lv_obj_t *container_2_2;
    lv_obj_t *label_9_info;
    lv_obj_t *container_2_2_1;
    lv_obj_t *label_7_ingredients;
    lv_obj_t *label_8_steps;
    lv_obj_t *container_2_2_2;
    lv_obj_t *label_9_customize;
    lv_obj_t *image_2_2_1_love;
    lv_obj_t *container_3_food;
    lv_obj_t *container_3_0;
    lv_obj_t *container_3_1;
    lv_obj_t *container_3_2;
    lv_obj_t *container_3_3;
    lv_obj_t *container_3_4;
    lv_obj_t *container_3_5;
    lv_obj_t *container_3_6;
    lv_obj_t *container_3_7;
    lv_obj_t *container_3_8;
    lv_obj_t *container_3_9;
    lv_obj_t *container_3_10;
    lv_obj_t *container_3_11;
    lv_obj_t *container_3_12;
    lv_obj_t *container_3_13;
    lv_obj_t *container_3_14;
    lv_obj_t *container_3_15;
    lv_obj_t *container_3_16;
    lv_obj_t *container_4_t_time;
    lv_obj_t *image_4_t;
    lv_obj_t *image_5_time;
    lv_obj_t *slider_1_t;
    lv_obj_t *slider_2_time;
    lv_obj_t *label_5_t;
    lv_obj_t *label_6_time;
    lv_obj_t *image_1_28_28;
    lv_obj_t *image_2_28_28;
    lv_obj_t *container_5_function_button;
    lv_obj_t *image_6_lamp;
    lv_obj_t *image_7_stop_run;
    lv_obj_t *label_1_airfry;
    lv_obj_t *label_2_bake;
    lv_obj_t *label_3_preheat;
    lv_obj_t *label_4_dehydrate;
    lv_obj_t *container_6_pop_up;
    lv_obj_t *container_6_pop_up_1;
    lv_obj_t *label_6_pop_up_1_insert_basket;
    lv_obj_t *button_2_x;
    lv_obj_t *container_7_toast_notification;
    lv_obj_t *label_10_toast_notification;
} screen_02_main_t;

typedef struct {
    lv_obj_t *obj;
} screen_01_logo_t;

typedef struct {
    lv_obj_t *obj;
    lv_obj_t *container_1;
    lv_obj_t *container_1_display;
    lv_obj_t *label_1_display;
    lv_obj_t *image_1_display;
    lv_obj_t *container_2_language;
    lv_obj_t *label_2_language;
    lv_obj_t *image_2_language;
    lv_obj_t *container_3_brightness;
    lv_obj_t *label_3_brightness;
    lv_obj_t *image_3_brightness;
    lv_obj_t *container_4_clock;
    lv_obj_t *label_4_clock;
    lv_obj_t *image_4_clock;
    lv_obj_t *container_5_sound;
    lv_obj_t *label_5_sound;
    lv_obj_t *image_5_sound;
    lv_obj_t *container_6_f_to_c;
    lv_obj_t *label_6_f_to_c;
    lv_obj_t *image_6_f_to_c;
    lv_obj_t *container_7_version;
    lv_obj_t *label_7_version;
    lv_obj_t *image_7_version;
    lv_obj_t *container_8_restore_factory_settings;
    lv_obj_t *label_8_restore_factory_settings;
    lv_obj_t *image_8_restore_factory_settings;
    lv_obj_t *button_1_back;
    lv_obj_t *label_0_settings;
} screen_03_setting_t;

typedef struct {
    lv_obj_t *obj;
    lv_obj_t *button_1_back;
    lv_obj_t *label_0_display;
    lv_obj_t *container_1_ligth;
    lv_obj_t *label_1_ligth;
    lv_obj_t *image_1_ligth;
    lv_obj_t *container_2_dark;
    lv_obj_t *label_2_dark;
    lv_obj_t *image_2_dark;
} screen_04_display_t;

typedef struct {
    lv_obj_t *obj;
    lv_obj_t *container_1;
    lv_obj_t *container_1_english;
    lv_obj_t *label_1_english;
    lv_obj_t *image_1_english;
    lv_obj_t *container_2_chinese;
    lv_obj_t *label_2_chinese;
    lv_obj_t *image_2_chinese;
    lv_obj_t *container_3_french;
    lv_obj_t *label_3_french;
    lv_obj_t *image_3_french;
    lv_obj_t *container_4_spanish;
    lv_obj_t *label_4_spanish;
    lv_obj_t *image_4_spanish;
    lv_obj_t *container_5_japan;
    lv_obj_t *label_5_japan;
    lv_obj_t *image_5_japan;
    lv_obj_t *container_6_german;
    lv_obj_t *label_6_german;
    lv_obj_t *image_6_german;
    lv_obj_t *container_7_italian;
    lv_obj_t *label_7_italian;
    lv_obj_t *image_7_italian;
    lv_obj_t *button_1_back;
    lv_obj_t *label_0_language;
} screen_05_language_t;

typedef struct {
    lv_obj_t *obj;
    lv_obj_t *button_1_back;
    lv_obj_t *label_0_brightness;
    lv_obj_t *container_1;
    lv_obj_t *label_1_brightness;
    lv_obj_t *label_2_percent;
    lv_obj_t *slider_1;
} screen_06_brightness_t;

typedef struct {
    lv_obj_t *obj;
    lv_obj_t *button_1_back;
    lv_obj_t *label_0_clock;
    lv_obj_t *container_1;
    lv_obj_t *label_1_24_hour;
    lv_obj_t *switch_1_24_hour;
    lv_obj_t *container_4_am_pm;
    lv_obj_t *label_2_clock;
    lv_obj_t *container_7_am;
    lv_obj_t *label_3_am;
    lv_obj_t *image_7_am;
    lv_obj_t *container_8_pm;
    lv_obj_t *label_4_pm;
    lv_obj_t *image_8_pm;
    lv_obj_t *container_2;
    lv_obj_t *label_5_time;
    lv_obj_t *button_1_ok;
    lv_obj_t *roller_1_12h;
    lv_obj_t *roller_2_24h;
    lv_obj_t *roller_3_m;
    lv_obj_t *image_8;
    lv_obj_t *image_9;
    lv_obj_t *container_3;
    lv_obj_t *label_6_screensaver_time_display;
    lv_obj_t *container_3_display;
    lv_obj_t *label_7_digital;
    lv_obj_t *image_3_digital;
    lv_obj_t *container_4_clock;
    lv_obj_t *label_8_clock;
    lv_obj_t *image_4_clock;
} screen_07_clock_t;

typedef struct {
    lv_obj_t *obj;
    lv_obj_t *button_1_back;
    lv_obj_t *label_0_sound;
    lv_obj_t *container_1_sound;
    lv_obj_t *label_1_sound;
    lv_obj_t *switch_1_sound;
} screen_08_sound_t;

typedef struct {
    lv_obj_t *obj;
    lv_obj_t *button_1_back;
    lv_obj_t *label_0_f_to_c;
    lv_obj_t *container_1_F_to_C;
    lv_obj_t *label_1_f_to_c;
    lv_obj_t *container_2_f;
    lv_obj_t *image_1_f;
    lv_obj_t *label_2_f;
    lv_obj_t *container_3_c;
    lv_obj_t *label_3_c;
    lv_obj_t *image_2_c;
} screen_09_F_to_C_t;

typedef struct {
    lv_obj_t *obj;
    lv_obj_t *button_1_back;
    lv_obj_t *label_0_version;
    lv_obj_t *container_1;
    lv_obj_t *label_1_version;
    lv_obj_t *label_2_version_V;
} screen_10_version_t;

typedef struct {
    lv_obj_t *obj;
    lv_obj_t *container_1_bg;
    lv_obj_t *container_2_show_all;
    lv_obj_t *label_1_choose_mode;
    lv_obj_t *container_3_food;
    lv_obj_t *image_0;
    lv_obj_t *image_1;
    lv_obj_t *image_2;
    lv_obj_t *image_3;
    lv_obj_t *image_4;
    lv_obj_t *image_5;
    lv_obj_t *image_6;
    lv_obj_t *image_7;
    lv_obj_t *image_8;
    lv_obj_t *image_9;
    lv_obj_t *image_10;
    lv_obj_t *image_11;
    lv_obj_t *image_12;
    lv_obj_t *image_13;
    lv_obj_t *image_14;
    lv_obj_t *image_15;
    lv_obj_t *image_16;
    lv_obj_t *button_1_x;
} screen_11_show_all_t;

typedef struct {
    lv_obj_t *obj;
} screen_12_idle_t;

typedef struct {
    lv_obj_t *obj;
    lv_obj_t *container_1;
    lv_obj_t *label_1_time;
    lv_obj_t *label_2_am_pm;
    lv_obj_t *container_2;
    lv_obj_t *image_1_h;
    lv_obj_t *image_2_m;
    lv_obj_t *image_3_s;
    lv_obj_t *button_1_back;
} screen_13_screensaver_t;

typedef struct {
    lv_obj_t *obj;
    lv_obj_t *container_1_bg;
    lv_obj_t *container_2_favorites;
    lv_obj_t *label_0_favorites;
    lv_obj_t *button_1_x;
    lv_obj_t *container_3_favorites;
    lv_obj_t *button_1_add;
    lv_obj_t *button_2_edit;
} screen_14_love_favorites_t;

typedef struct {
    lv_obj_t *obj;
    lv_obj_t *button_1_back;
    lv_obj_t *label_0_restore_factory_settings;
    lv_obj_t *container_1_restore_factory_settings;
    lv_obj_t *label_1_restore_factory_settings;
} screen_15_restore_factory_settings_t;


typedef struct {
    bool auto_del;
    screen_02_main_t screen_02_main;
    screen_01_logo_t screen_01_logo;
    screen_03_setting_t screen_03_setting;
    screen_04_display_t screen_04_display;
    screen_05_language_t screen_05_language;
    screen_06_brightness_t screen_06_brightness;
    screen_07_clock_t screen_07_clock;
    screen_08_sound_t screen_08_sound;
    screen_09_F_to_C_t screen_09_F_to_C;
    screen_10_version_t screen_10_version;
    screen_11_show_all_t screen_11_show_all;
    screen_12_idle_t screen_12_idle;
    screen_13_screensaver_t screen_13_screensaver;
    screen_14_love_favorites_t screen_14_love_favorites;
    screen_15_restore_factory_settings_t screen_15_restore_factory_settings;

} ui_manager_t;

static inline void ui_manager_init(ui_manager_t *ui, bool auto_del)
{
    memset(ui, 0 , sizeof(ui_manager_t));
    ui->auto_del = auto_del;
}

static inline screen_02_main_t *screen_02_main_get(ui_manager_t *ui)
{
    return &ui->screen_02_main;
}

static inline screen_01_logo_t *screen_01_logo_get(ui_manager_t *ui)
{
    return &ui->screen_01_logo;
}

static inline screen_03_setting_t *screen_03_setting_get(ui_manager_t *ui)
{
    return &ui->screen_03_setting;
}

static inline screen_04_display_t *screen_04_display_get(ui_manager_t *ui)
{
    return &ui->screen_04_display;
}

static inline screen_05_language_t *screen_05_language_get(ui_manager_t *ui)
{
    return &ui->screen_05_language;
}

static inline screen_06_brightness_t *screen_06_brightness_get(ui_manager_t *ui)
{
    return &ui->screen_06_brightness;
}

static inline screen_07_clock_t *screen_07_clock_get(ui_manager_t *ui)
{
    return &ui->screen_07_clock;
}

static inline screen_08_sound_t *screen_08_sound_get(ui_manager_t *ui)
{
    return &ui->screen_08_sound;
}

static inline screen_09_F_to_C_t *screen_09_F_to_C_get(ui_manager_t *ui)
{
    return &ui->screen_09_F_to_C;
}

static inline screen_10_version_t *screen_10_version_get(ui_manager_t *ui)
{
    return &ui->screen_10_version;
}

static inline screen_11_show_all_t *screen_11_show_all_get(ui_manager_t *ui)
{
    return &ui->screen_11_show_all;
}

static inline screen_12_idle_t *screen_12_idle_get(ui_manager_t *ui)
{
    return &ui->screen_12_idle;
}

static inline screen_13_screensaver_t *screen_13_screensaver_get(ui_manager_t *ui)
{
    return &ui->screen_13_screensaver;
}

static inline screen_14_love_favorites_t *screen_14_love_favorites_get(ui_manager_t *ui)
{
    return &ui->screen_14_love_favorites;
}

static inline screen_15_restore_factory_settings_t *screen_15_restore_factory_settings_get(ui_manager_t *ui)
{
    return &ui->screen_15_restore_factory_settings;
}


void screen_02_main_create(ui_manager_t *ui);
void screen_01_logo_create(ui_manager_t *ui);
void screen_03_setting_create(ui_manager_t *ui);
void screen_04_display_create(ui_manager_t *ui);
void screen_05_language_create(ui_manager_t *ui);
void screen_06_brightness_create(ui_manager_t *ui);
void screen_07_clock_create(ui_manager_t *ui);
void screen_08_sound_create(ui_manager_t *ui);
void screen_09_F_to_C_create(ui_manager_t *ui);
void screen_10_version_create(ui_manager_t *ui);
void screen_11_show_all_create(ui_manager_t *ui);
void screen_12_idle_create(ui_manager_t *ui);
void screen_13_screensaver_create(ui_manager_t *ui);
void screen_14_love_favorites_create(ui_manager_t *ui);
void screen_15_restore_factory_settings_create(ui_manager_t *ui);


extern lv_font_t *fs_montserratmedium_16;
extern lv_font_t *fs_montserratmedium_25;
extern lv_font_t *fs_montserratmedium_47;
extern lv_font_t *fs_montserratmedium_34;
extern lv_font_t *fs_montserratmedium_22;
extern lv_font_t *fs_montserratmedium_20;
extern lv_font_t *fs_montserratmedium_30;
extern lv_font_t *fs_montserratmedium_24;
extern lv_font_t *fs_montserratmedium_36;
extern lv_font_t *fs_montserratmedium_26;
extern lv_font_t *fs_montserratmedium_110;


extern ui_manager_t ui_manager;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif // _UI_OBJECTS
