/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by UIBuilder
 * UIBuilder version: v2.1.0
 */

#include <stdio.h>
#include "ui_util.h"

bool screen_is_loading(lv_obj_t *scr)
{
#if LVGL_VERSION_MAJOR == 8
    lv_obj_t *act_scr = lv_scr_act();
    lv_disp_t *d = lv_obj_get_disp(scr);
    if (d->prev_scr == NULL && (d->scr_to_load == NULL || d->scr_to_load == act_scr))
        return false;
    else
        return true;
#else
    return false;
#endif
}

void ui_style_init(lv_style_t *style)
{
  if (style->prop_cnt >= 1)
    lv_style_reset(style);
  else
    lv_style_init(style);
}

lv_font_t *ui_font_init(char *path, int size) {
#if LVGL_VERSION_MAJOR == 8
    static lv_ft_info_t info;
    info.name = path;
    info.weight = size;
    info.style = FT_FONT_STYLE_NORMAL;
    info.mem = NULL;
    if (!lv_ft_font_init(&info))
        return NULL;
    return info.font;
#else
    lv_font_t *font = lv_freetype_font_create(path,
                                              LV_FREETYPE_FONT_RENDER_MODE_BITMAP,
                                              size,
                                              LV_FREETYPE_FONT_STYLE_NORMAL);
    return font;
#endif //LVGL_VERSION_MAJOR
}
