/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by UIBuilder
 * UIBuilder version: v2.1.0
 */

/* lv_conf_custom.h for custom lv_conf.h file
 * example : 
 *     #undef LV_USE_LOG
 *     #define LV_USE_LOG 1
 */

#ifndef LV_CONF_CUSTOM_H
#define LV_CONF_CUSTOM_H

/* code  begin */

#undef LV_USE_FREETYPE
#define LV_USE_FREETYPE 1

#undef LV_USE_PERF_MONITOR
#define LV_USE_PERF_MONITOR 0

#undef LV_USE_MEM_MONITOR
#define LV_USE_MEM_MONITOR 0



#undef LV_COLOR_DEPTH
#define LV_COLOR_DEPTH 32



/* code end */

#endif  /* LV_CONF_CUSTOM_H */
