/*
 * Copyright (C) 2024 ArtInChip Technology Co., Ltd.有
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v1.0.0
 */
#include "custom.h"


// 从 CSV 读取指定列并打印（调试工具）
int yk_read_csv_column() {
    FILE *file;
    char filename[] = "F:\\LVGL\\D13x\\AiUiBuilderYK\\960x480_air_frye\\ui_builder\\custom\\STL.csv"; // 替换为你的CSV文件名
    char line[1024];
    char *token;
    int column = 6; // F列是第6列（从1开始计数）

	int t = -1;

    // 打开文件
    file = fopen(filename, "r");
    if (file == NULL) {
        // 文件打开失败：直接返回错误码
        yk_printf("Unable to open file %s\n", filename);
        return 1;
    }

    // 逐行读取文件内容
    while (fgets(line, 1024, file) != NULL) {
        int current_column = 1;
        token = strtok(line, ","); // 使用逗号分隔每一列
        while (token != NULL) {
            if (current_column == column) {
                float  value = atoi(token); // 将字符串转换为整数
                yk_printf("{%d,%.f},", t, value); // 打印F列的数据乘以1000
				t++;
                break;
            }
            token = strtok(NULL, ",");
            current_column++;
        }
    }

    // 关闭文件
    fclose(file);
    return 0;
}


// 自定义初始化：加载设置、初始化驱动
void custom_init()
{
	//yk_read_csv_column();


	//文件读写初始化
	yk_f_file_flash_init();

    //自定义驱动初始化
	yk_driver_init();
    //触摸音效初始化
	yk_touch_sound_init();
    // #ifndef YK_USE_UI_BUILDER
    // yk_uart_init();
    // #endif
}
