/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by UIBuilder
 * UIBuilder version: v2.1.0
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"


void __attribute__((weak)) screen_02_main_custom_created(void) {
}
void __attribute__((weak)) screen_02_main_custom_loaded(void) {
}

static void screen_02_main_loaded (lv_event_t *e) {
    screen_02_main_custom_loaded();
}

void __attribute__((weak)) screen_02_main_image_1_off_custom_clicked(void) {
}

static void screen_02_main_image_1_off_clicked (lv_event_t *e) {
    screen_02_main_image_1_off_custom_clicked();
}

static void screen_02_main_image_2_show_all_food_clicked (lv_event_t *e) {
    lv_obj_t *act_scr = lv_scr_act();
    if (!screen_is_loading(act_scr)) {
        // create screen_11_show_all
        screen_11_show_all_create(&ui_manager);
        // load screen_11_show_all
        lv_scr_load_anim(screen_11_show_all_get(&ui_manager)->obj, LV_SCR_LOAD_ANIM_NONE, 1, 0, ui_manager.auto_del);
    }
}

static void screen_02_main_image_3_settings_clicked (lv_event_t *e) {
    lv_obj_t *act_scr = lv_scr_act();
    if (!screen_is_loading(act_scr)) {
        // create screen_03_setting
        screen_03_setting_create(&ui_manager);
        // load screen_03_setting
        lv_scr_load_anim(screen_03_setting_get(&ui_manager)->obj, LV_SCR_LOAD_ANIM_NONE, 1, 0, ui_manager.auto_del);
    }
}

static void screen_02_main_image_4_love_clicked (lv_event_t *e) {
    lv_obj_t *act_scr = lv_scr_act();
    if (!screen_is_loading(act_scr)) {
        // create screen_14_love_favorites
        screen_14_love_favorites_create(&ui_manager);
        // load screen_14_love_favorites
        lv_scr_load_anim(screen_14_love_favorites_get(&ui_manager)->obj, LV_SCR_LOAD_ANIM_NONE, 1, 0, ui_manager.auto_del);
    }
}

void __attribute__((weak)) ntc_t_difference_add_custom_clicked(void) {
}
void __attribute__((weak)) ntc_t_difference_sub_custom_long_pressed(void) {
}

static void screen_02_main_image_run_clicked (lv_event_t *e) {
    ntc_t_difference_add_custom_clicked();
}

static void screen_02_main_image_run_long_pressed (lv_event_t *e) {
    ntc_t_difference_sub_custom_long_pressed();
}

void __attribute__((weak)) screen_02_main_label_2_custom_clicked(void) {
}

static void screen_02_main_label_run_cancel_clicked (lv_event_t *e) {
    screen_02_main_label_2_custom_clicked();
}

void __attribute__((weak)) screen_02_main_label_7_ingredients_custom_clicked(void) {
}

static void screen_02_main_label_7_ingredients_clicked (lv_event_t *e) {
    screen_02_main_label_7_ingredients_custom_clicked();
}

void __attribute__((weak)) screen_02_main_label_8_steps_custom_clicked(void) {
}

static void screen_02_main_label_8_steps_clicked (lv_event_t *e) {
    screen_02_main_label_8_steps_custom_clicked();
}

void __attribute__((weak)) screen_02_main_image_2_2_1_love_custom_clicked(void) {
}

static void screen_02_main_image_2_2_1_love_clicked (lv_event_t *e) {
    screen_02_main_image_2_2_1_love_custom_clicked();
}

void __attribute__((weak)) screen_02_main_slider_1_t_custom_value_changed(void) {
}

static void screen_02_main_slider_1_t_value_changed (lv_event_t *e) {
    screen_02_main_slider_1_t_custom_value_changed();
}

void __attribute__((weak)) screen_02_main_slider_2_time_custom_value_changed(void) {
}

static void screen_02_main_slider_2_time_value_changed (lv_event_t *e) {
    screen_02_main_slider_2_time_custom_value_changed();
}

void __attribute__((weak)) screen_02_main_image_6_lamp_custom_clicked(void) {
}

static void screen_02_main_image_6_lamp_clicked (lv_event_t *e) {
    screen_02_main_image_6_lamp_custom_clicked();
}

void __attribute__((weak)) screen_02_main_image_7_stop_run_custom_clicked(void) {
}

static void screen_02_main_image_7_stop_run_clicked (lv_event_t *e) {
    screen_02_main_image_7_stop_run_custom_clicked();
}

void __attribute__((weak)) screen_02_main_label_1_airfry_custom_clicked(void) {
}

static void screen_02_main_label_1_airfry_clicked (lv_event_t *e) {
    screen_02_main_label_1_airfry_custom_clicked();
}

void __attribute__((weak)) screen_02_main_label_2_bake_custom_clicked(void) {
}

static void screen_02_main_label_2_bake_clicked (lv_event_t *e) {
    screen_02_main_label_2_bake_custom_clicked();
}

void __attribute__((weak)) screen_02_main_label_3_preheat_custom_clicked(void) {
}

static void screen_02_main_label_3_preheat_clicked (lv_event_t *e) {
    screen_02_main_label_3_preheat_custom_clicked();
}

void __attribute__((weak)) screen_02_main_label_4_dehydrate_custom_clicked(void) {
}

static void screen_02_main_label_4_dehydrate_clicked (lv_event_t *e) {
    screen_02_main_label_4_dehydrate_custom_clicked();
}

static void screen_02_main_container_6_pop_up_clicked (lv_event_t *e) {
    lv_obj_t *screen_02_main_container_6_pop_up = screen_02_main_get(&ui_manager)->container_6_pop_up;
    lv_obj_add_flag(screen_02_main_container_6_pop_up, LV_OBJ_FLAG_HIDDEN);
}

static void screen_02_main_button_2_x_clicked (lv_event_t *e) {
    lv_obj_t *screen_02_main_container_6_pop_up = screen_02_main_get(&ui_manager)->container_6_pop_up;
    lv_obj_add_flag(screen_02_main_container_6_pop_up, LV_OBJ_FLAG_HIDDEN);
}

static void screen_02_main_container_7_toast_notification_clicked (lv_event_t *e) {
    lv_obj_t *screen_02_main_container_7_toast_notification = screen_02_main_get(&ui_manager)->container_7_toast_notification;
    lv_obj_add_flag(screen_02_main_container_7_toast_notification, LV_OBJ_FLAG_HIDDEN);
}


void screen_02_main_create(ui_manager_t *ui)
{
    screen_02_main_t *scr = screen_02_main_get(ui);

    if (!ui->auto_del && scr->obj) {
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0xf2f2f2), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->obj
    lv_obj_add_event_cb(scr->obj, screen_02_main_loaded, LV_EVENT_SCREEN_LOADED, NULL);

    // Init scr->container_1_off_show_set
    scr->container_1_off_show_set = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->container_1_off_show_set, 30, 30);
    lv_obj_set_size(scr->container_1_off_show_set, 64, 326);
    lv_obj_set_scrollbar_mode(scr->container_1_off_show_set, LV_SCROLLBAR_MODE_OFF);
    lv_obj_clear_flag(scr->container_1_off_show_set, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->container_1_off_show_set
    lv_obj_set_style_border_width(scr->container_1_off_show_set, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->container_1_off_show_set, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->container_1_off_show_set, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_1_off_show_set, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_1_off_show_set, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_1_off_show_set, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_1_off_show_set, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_1_off
    scr->image_1_off = lv_img_create(scr->container_1_off_show_set);
    lv_img_set_src(scr->image_1_off, LVGL_IMAGE_PATH(icon01_64x64.png));
    lv_img_set_pivot(scr->image_1_off, 50, 50);
    lv_img_set_offset_x(scr->image_1_off, 0);
    lv_img_set_offset_y(scr->image_1_off, 0);
    lv_img_set_angle(scr->image_1_off, 0);
    lv_obj_set_pos(scr->image_1_off, 0, 0);
    lv_obj_add_flag(scr->image_1_off, LV_OBJ_FLAG_CLICKABLE);

    // Set event handler of scr->image_1_off
    lv_obj_add_event_cb(scr->image_1_off, screen_02_main_image_1_off_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->image_2_show_all_food
    scr->image_2_show_all_food = lv_img_create(scr->container_1_off_show_set);
    lv_img_set_src(scr->image_2_show_all_food, LVGL_IMAGE_PATH(icon02_64x64.png));
    lv_img_set_pivot(scr->image_2_show_all_food, 50, 50);
    lv_img_set_offset_x(scr->image_2_show_all_food, 0);
    lv_img_set_offset_y(scr->image_2_show_all_food, 0);
    lv_img_set_angle(scr->image_2_show_all_food, 0);
    lv_obj_set_pos(scr->image_2_show_all_food, 0, 87);
    lv_obj_add_flag(scr->image_2_show_all_food, LV_OBJ_FLAG_CLICKABLE);

    // Set event handler of scr->image_2_show_all_food
    lv_obj_add_event_cb(scr->image_2_show_all_food, screen_02_main_image_2_show_all_food_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->image_3_settings
    scr->image_3_settings = lv_img_create(scr->container_1_off_show_set);
    lv_img_set_src(scr->image_3_settings, LVGL_IMAGE_PATH(icon03_64x64.png));
    lv_img_set_pivot(scr->image_3_settings, 50, 50);
    lv_img_set_offset_x(scr->image_3_settings, 0);
    lv_img_set_offset_y(scr->image_3_settings, 0);
    lv_img_set_angle(scr->image_3_settings, 0);
    lv_obj_set_pos(scr->image_3_settings, 0, 262);
    lv_obj_add_flag(scr->image_3_settings, LV_OBJ_FLAG_CLICKABLE);

    // Set event handler of scr->image_3_settings
    lv_obj_add_event_cb(scr->image_3_settings, screen_02_main_image_3_settings_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->image_4_love
    scr->image_4_love = lv_img_create(scr->container_1_off_show_set);
    lv_img_set_src(scr->image_4_love, LVGL_IMAGE_PATH(icon04_64x64.png));
    lv_img_set_pivot(scr->image_4_love, 50, 50);
    lv_img_set_offset_x(scr->image_4_love, 0);
    lv_img_set_offset_y(scr->image_4_love, 0);
    lv_img_set_angle(scr->image_4_love, 0);
    lv_obj_set_pos(scr->image_4_love, 0, 174);
    lv_obj_add_flag(scr->image_4_love, LV_OBJ_FLAG_CLICKABLE);

    // Set event handler of scr->image_4_love
    lv_obj_add_event_cb(scr->image_4_love, screen_02_main_image_4_love_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->container_2_main
    scr->container_2_main = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->container_2_main, 124, 30);
    lv_obj_set_size(scr->container_2_main, 778, 326);
    lv_obj_set_scrollbar_mode(scr->container_2_main, LV_SCROLLBAR_MODE_OFF);
    lv_obj_clear_flag(scr->container_2_main, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->container_2_main
    lv_obj_set_style_border_width(scr->container_2_main, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_2_main, 18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_2_main, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_2_main, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_2_main, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_2_main, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->container_2_1
    scr->container_2_1 = lv_obj_create(scr->container_2_main);
    lv_obj_set_pos(scr->container_2_1, 0, 0);
    lv_obj_set_size(scr->container_2_1, 372, 326);
    lv_obj_set_scrollbar_mode(scr->container_2_1, LV_SCROLLBAR_MODE_OFF);
    lv_obj_clear_flag(scr->container_2_1, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->container_2_1
    lv_obj_set_style_border_width(scr->container_2_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_2_1, 18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->container_2_1, LVGL_IMAGE_PATH(food_00_01.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->container_2_1, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->container_2_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_2_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_2_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_2_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_2_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_10_food_name
    scr->label_10_food_name = lv_label_create(scr->container_2_1);
    lv_label_set_text(scr->label_10_food_name, "food name");
    lv_label_set_long_mode(scr->label_10_food_name, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_obj_set_pos(scr->label_10_food_name, 1, 270);
    lv_obj_set_size(scr->label_10_food_name, 370, 40);

    // Set style of scr->label_10_food_name
    lv_obj_set_style_border_opa(scr->label_10_food_name, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(scr->label_10_food_name, lv_color_hex(0xc4300e), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_10_food_name, lv_color_hex(0xc4330f), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->label_10_food_name, lv_color_hex(0xc4300e), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_10_food_name, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_10_food_name, fs_montserratmedium_25, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->container_2_3_run
    scr->container_2_3_run = lv_obj_create(scr->container_2_main);
    lv_obj_set_pos(scr->container_2_3_run, 0, 0);
    lv_obj_set_size(scr->container_2_3_run, 372, 326);
    lv_obj_set_scrollbar_mode(scr->container_2_3_run, LV_SCROLLBAR_MODE_OFF);
    lv_obj_add_flag(scr->container_2_3_run, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(scr->container_2_3_run, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->container_2_3_run
    lv_obj_set_style_border_width(scr->container_2_3_run, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_2_3_run, 18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->container_2_3_run, LVGL_IMAGE_PATH(bg_main.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_2_3_run, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_2_3_run, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_2_3_run, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_2_3_run, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->arc_1
    scr->arc_1 = lv_arc_create(scr->container_2_3_run);
    lv_arc_set_mode(scr->arc_1, LV_ARC_MODE_NORMAL);
    lv_arc_set_range(scr->arc_1, 0, 360);
    lv_arc_set_value(scr->arc_1, 0);
    lv_arc_set_bg_angles(scr->arc_1, 0, 360);
    lv_arc_set_angles(scr->arc_1, 0, 45);
    lv_arc_set_rotation(scr->arc_1, 270);
    lv_arc_set_change_rate(scr->arc_1, 720);
    lv_obj_set_pos(scr->arc_1, 43, 20);
    lv_obj_set_size(scr->arc_1, 286, 286);
    lv_obj_clear_flag(scr->arc_1, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->arc_1
    lv_obj_set_style_arc_color(scr->arc_1, lv_color_hex(0xdcd4d4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(scr->arc_1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(scr->arc_1, lv_color_hex(0xc4330f), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(scr->arc_1, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->arc_1, lv_color_hex(0xc4330f), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->arc_1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    // Init scr->image_run
    scr->image_run = lv_img_create(scr->container_2_3_run);
    lv_img_set_src(scr->image_run, LVGL_IMAGE_PATH(food_01_02.png));
    lv_img_set_pivot(scr->image_run, 95, 95);
    lv_img_set_offset_x(scr->image_run, 0);
    lv_img_set_offset_y(scr->image_run, 0);
    lv_img_set_angle(scr->image_run, 0);
    lv_obj_set_pos(scr->image_run, 122, 84);

    // Set event handler of scr->image_run
    lv_obj_add_event_cb(scr->image_run, screen_02_main_image_run_clicked, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(scr->image_run, screen_02_main_image_run_long_pressed, LV_EVENT_LONG_PRESSED, NULL);

    // Init scr->label_run_cancel
    scr->label_run_cancel = lv_label_create(scr->container_2_3_run);
    lv_label_set_text(scr->label_run_cancel, "Cancel");
    lv_label_set_long_mode(scr->label_run_cancel, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_run_cancel, 123, 220);
    lv_obj_set_size(scr->label_run_cancel, 126, 50);
    lv_obj_add_flag(scr->label_run_cancel, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->label_run_cancel
    lv_obj_set_style_border_width(scr->label_run_cancel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(scr->label_run_cancel, lv_color_hex(0xc4330f), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_run_cancel, lv_color_hex(0xfefefe), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->label_run_cancel, lv_color_hex(0xc4300e), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->label_run_cancel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_run_cancel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->label_run_cancel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->label_run_cancel, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_run_cancel, fs_montserratmedium_25, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->label_run_cancel
    lv_obj_add_event_cb(scr->label_run_cancel, screen_02_main_label_run_cancel_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->label_run_timer
    scr->label_run_timer = lv_label_create(scr->container_2_3_run);
    lv_label_set_text(scr->label_run_timer, "20:00");
    lv_label_set_long_mode(scr->label_run_timer, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_run_timer, 108, 152);
    lv_obj_set_size(scr->label_run_timer, 156, 63);

    // Set style of scr->label_run_timer
    lv_obj_set_style_border_opa(scr->label_run_timer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(scr->label_run_timer, lv_color_hex(0xc4300e), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_run_timer, lv_color_hex(0x615f5f), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->label_run_timer, lv_color_hex(0xc4300e), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_run_timer, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->label_run_timer, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_run_timer, fs_montserratmedium_47, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_run_shake
    scr->label_run_shake = lv_label_create(scr->container_2_3_run);
    lv_label_set_text(scr->label_run_shake, "SHAKE");
    lv_label_set_long_mode(scr->label_run_shake, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_run_shake, 111, 51);
    lv_obj_set_size(scr->label_run_shake, 150, 45);
    lv_obj_add_flag(scr->label_run_shake, LV_OBJ_FLAG_HIDDEN);

    // Set style of scr->label_run_shake
    lv_obj_set_style_border_opa(scr->label_run_shake, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(scr->label_run_shake, lv_color_hex(0xc4300e), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_run_shake, lv_color_hex(0x615f5f), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->label_run_shake, lv_color_hex(0xc4300e), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_run_shake, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->label_run_shake, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_run_shake, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->container_2_2
    scr->container_2_2 = lv_obj_create(scr->container_2_main);
    lv_obj_set_pos(scr->container_2_2, 382, 0);
    lv_obj_set_size(scr->container_2_2, 396, 326);
    lv_obj_set_scrollbar_mode(scr->container_2_2, LV_SCROLLBAR_MODE_OFF);
    lv_obj_clear_flag(scr->container_2_2, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->container_2_2
    lv_obj_set_style_border_width(scr->container_2_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_2_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->container_2_2, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->container_2_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_2_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_2_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_2_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_2_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_9_info
    scr->label_9_info = lv_label_create(scr->container_2_2);
    lv_label_set_text(scr->label_9_info, "chicken wings 2 pound (900g)\nOlive oil: 1 tablespoon\nSalt: ½ teaspoon\nBlack pepper: ½ teaspoon\nSpice Mix (Optional): ½ tsp each of \npaprika, garlic powder, and chili \npowder (adjust to taste)powder (ad\njust to taste)\nchicken wings 2 pound (900g)\nOlive oil: 1 tablespoon\nSalt: ½ teaspoon\nBlack pepper: ½ teaspoon\nSpice Mix (Optional): ½ tsp each of \npaprika, garlic powder, and chili \npowder (adjust to taste)powder (ad\njust to taste)");
    lv_label_set_long_mode(scr->label_9_info, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_9_info, 0, 70);
    lv_obj_set_size(scr->label_9_info, 385, 239);
    lv_obj_add_flag(scr->label_9_info, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->label_9_info
    lv_obj_set_style_border_color(scr->label_9_info, lv_color_hex(0x615f5f), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_9_info, lv_color_hex(0x615f5f), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_9_info, fs_montserratmedium_25, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->container_2_2_1
    scr->container_2_2_1 = lv_obj_create(scr->container_2_2);
    lv_obj_set_pos(scr->container_2_2_1, 0, 10);
    lv_obj_set_size(scr->container_2_2_1, 396, 50);
    lv_obj_set_scrollbar_mode(scr->container_2_2_1, LV_SCROLLBAR_MODE_OFF);
    lv_obj_add_flag(scr->container_2_2_1, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(scr->container_2_2_1, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->container_2_2_1
    lv_obj_set_style_border_width(scr->container_2_2_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_2_2_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->container_2_2_1, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->container_2_2_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_2_2_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_2_2_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_2_2_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_2_2_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_7_ingredients
    scr->label_7_ingredients = lv_label_create(scr->container_2_2_1);
    lv_label_set_text(scr->label_7_ingredients, "INGREDIENTS");
    lv_label_set_long_mode(scr->label_7_ingredients, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_obj_set_pos(scr->label_7_ingredients, 0, 0);
    lv_obj_set_size(scr->label_7_ingredients, 180, 50);
    lv_obj_add_flag(scr->label_7_ingredients, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->label_7_ingredients
    lv_obj_set_style_border_width(scr->label_7_ingredients, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(scr->label_7_ingredients, lv_color_hex(0xc4330f), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_7_ingredients, lv_color_hex(0xfefefe), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->label_7_ingredients, lv_color_hex(0xc4300e), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->label_7_ingredients, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_7_ingredients, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->label_7_ingredients, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->label_7_ingredients, 18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_7_ingredients, fs_montserratmedium_25, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->label_7_ingredients
    lv_obj_add_event_cb(scr->label_7_ingredients, screen_02_main_label_7_ingredients_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->label_8_steps
    scr->label_8_steps = lv_label_create(scr->container_2_2_1);
    lv_label_set_text(scr->label_8_steps, "STEPS");
    lv_label_set_long_mode(scr->label_8_steps, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_obj_set_pos(scr->label_8_steps, 200, 0);
    lv_obj_set_size(scr->label_8_steps, 180, 50);
    lv_obj_add_flag(scr->label_8_steps, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->label_8_steps
    lv_obj_set_style_border_width(scr->label_8_steps, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(scr->label_8_steps, lv_color_hex(0xc4300e), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_8_steps, lv_color_hex(0x615f5f), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->label_8_steps, lv_color_hex(0xc4300e), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_8_steps, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->label_8_steps, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->label_8_steps, 18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_8_steps, fs_montserratmedium_25, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->label_8_steps
    lv_obj_add_event_cb(scr->label_8_steps, screen_02_main_label_8_steps_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->container_2_2_2
    scr->container_2_2_2 = lv_obj_create(scr->container_2_2);
    lv_obj_set_pos(scr->container_2_2_2, 0, 10);
    lv_obj_set_size(scr->container_2_2_2, 396, 50);
    lv_obj_set_scrollbar_mode(scr->container_2_2_2, LV_SCROLLBAR_MODE_OFF);
    lv_obj_clear_flag(scr->container_2_2_2, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->container_2_2_2
    lv_obj_set_style_border_width(scr->container_2_2_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_2_2_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->container_2_2_2, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->container_2_2_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_2_2_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_2_2_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_2_2_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_2_2_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_9_customize
    scr->label_9_customize = lv_label_create(scr->container_2_2_2);
    lv_label_set_text(scr->label_9_customize, "customize");
    lv_label_set_long_mode(scr->label_9_customize, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_obj_set_pos(scr->label_9_customize, 0, 0);
    lv_obj_set_size(scr->label_9_customize, 380, 50);

    // Set style of scr->label_9_customize
    lv_obj_set_style_border_opa(scr->label_9_customize, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->label_9_customize, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(scr->label_9_customize, lv_color_hex(0xc4300e), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_9_customize, lv_color_hex(0xc4330f), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->label_9_customize, lv_color_hex(0xc4300e), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->label_9_customize, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->label_9_customize, 18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_9_customize, fs_montserratmedium_25, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_2_2_1_love
    scr->image_2_2_1_love = lv_img_create(scr->container_2_main);
    lv_img_set_src(scr->image_2_2_1_love, LVGL_IMAGE_PATH(icon_love_0.png));
    lv_img_set_pivot(scr->image_2_2_1_love, 50, 50);
    lv_img_set_offset_x(scr->image_2_2_1_love, 0);
    lv_img_set_offset_y(scr->image_2_2_1_love, 0);
    lv_img_set_angle(scr->image_2_2_1_love, 0);
    lv_obj_set_pos(scr->image_2_2_1_love, 20, 20);
    lv_obj_add_flag(scr->image_2_2_1_love, LV_OBJ_FLAG_CLICKABLE);

    // Set event handler of scr->image_2_2_1_love
    lv_obj_add_event_cb(scr->image_2_2_1_love, screen_02_main_image_2_2_1_love_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->container_3_food
    scr->container_3_food = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->container_3_food, 932, 30);
    lv_obj_set_size(scr->container_3_food, 190, 516);
    lv_obj_set_scrollbar_mode(scr->container_3_food, LV_SCROLLBAR_MODE_OFF);
    lv_obj_clear_flag(scr->container_3_food, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->container_3_food
    lv_obj_set_style_border_width(scr->container_3_food, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_3_food, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->container_3_food, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->container_3_food, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_3_food, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_3_food, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_3_food, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_3_food, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->container_3_0
    scr->container_3_0 = lv_obj_create(scr->container_3_food);
    lv_obj_set_pos(scr->container_3_0, 0, 0);
    lv_obj_set_size(scr->container_3_0, 190, 158);
    lv_obj_set_scrollbar_mode(scr->container_3_0, LV_SCROLLBAR_MODE_OFF);
    lv_obj_add_flag(scr->container_3_0, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->container_3_0
    lv_obj_set_style_border_color(scr->container_3_0, lv_color_hex(0xff0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_3_0, 18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->container_3_0, LVGL_IMAGE_PATH(food_00.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->container_3_0, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->container_3_0, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_3_0, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_3_0, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_3_0, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_3_0, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->container_3_1
    scr->container_3_1 = lv_obj_create(scr->container_3_food);
    lv_obj_set_pos(scr->container_3_1, 0, 179);
    lv_obj_set_size(scr->container_3_1, 190, 158);
    lv_obj_set_scrollbar_mode(scr->container_3_1, LV_SCROLLBAR_MODE_OFF);
    lv_obj_add_flag(scr->container_3_1, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->container_3_1
    lv_obj_set_style_border_color(scr->container_3_1, lv_color_hex(0xff0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_3_1, 18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->container_3_1, LVGL_IMAGE_PATH(food_01.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->container_3_1, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->container_3_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_3_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_3_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_3_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_3_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(scr->container_3_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->container_3_2
    scr->container_3_2 = lv_obj_create(scr->container_3_food);
    lv_obj_set_pos(scr->container_3_2, 0, 358);
    lv_obj_set_size(scr->container_3_2, 190, 158);
    lv_obj_set_scrollbar_mode(scr->container_3_2, LV_SCROLLBAR_MODE_OFF);
    lv_obj_add_flag(scr->container_3_2, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->container_3_2
    lv_obj_set_style_border_color(scr->container_3_2, lv_color_hex(0xff0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_3_2, 18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->container_3_2, LVGL_IMAGE_PATH(food_02.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->container_3_2, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->container_3_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_3_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_3_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_3_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_3_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(scr->container_3_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->container_3_3
    scr->container_3_3 = lv_obj_create(scr->container_3_food);
    lv_obj_set_pos(scr->container_3_3, 0, 537);
    lv_obj_set_size(scr->container_3_3, 190, 158);
    lv_obj_set_scrollbar_mode(scr->container_3_3, LV_SCROLLBAR_MODE_OFF);
    lv_obj_add_flag(scr->container_3_3, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->container_3_3
    lv_obj_set_style_border_color(scr->container_3_3, lv_color_hex(0xff0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_3_3, 18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->container_3_3, LVGL_IMAGE_PATH(food_03.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->container_3_3, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->container_3_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_3_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_3_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_3_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_3_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(scr->container_3_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->container_3_4
    scr->container_3_4 = lv_obj_create(scr->container_3_food);
    lv_obj_set_pos(scr->container_3_4, 0, 716);
    lv_obj_set_size(scr->container_3_4, 190, 158);
    lv_obj_set_scrollbar_mode(scr->container_3_4, LV_SCROLLBAR_MODE_OFF);
    lv_obj_add_flag(scr->container_3_4, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->container_3_4
    lv_obj_set_style_border_color(scr->container_3_4, lv_color_hex(0xff0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_3_4, 18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->container_3_4, LVGL_IMAGE_PATH(food_04.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->container_3_4, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->container_3_4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_3_4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_3_4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_3_4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_3_4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(scr->container_3_4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->container_3_5
    scr->container_3_5 = lv_obj_create(scr->container_3_food);
    lv_obj_set_pos(scr->container_3_5, 0, 895);
    lv_obj_set_size(scr->container_3_5, 190, 158);
    lv_obj_set_scrollbar_mode(scr->container_3_5, LV_SCROLLBAR_MODE_OFF);
    lv_obj_add_flag(scr->container_3_5, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->container_3_5
    lv_obj_set_style_border_color(scr->container_3_5, lv_color_hex(0xff0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_3_5, 18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->container_3_5, LVGL_IMAGE_PATH(food_05.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->container_3_5, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->container_3_5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_3_5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_3_5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_3_5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_3_5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(scr->container_3_5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->container_3_6
    scr->container_3_6 = lv_obj_create(scr->container_3_food);
    lv_obj_set_pos(scr->container_3_6, 0, 1074);
    lv_obj_set_size(scr->container_3_6, 190, 158);
    lv_obj_set_scrollbar_mode(scr->container_3_6, LV_SCROLLBAR_MODE_OFF);
    lv_obj_add_flag(scr->container_3_6, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->container_3_6
    lv_obj_set_style_border_color(scr->container_3_6, lv_color_hex(0xff0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_3_6, 18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->container_3_6, LVGL_IMAGE_PATH(food_06.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->container_3_6, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->container_3_6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_3_6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_3_6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_3_6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_3_6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(scr->container_3_6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->container_3_7
    scr->container_3_7 = lv_obj_create(scr->container_3_food);
    lv_obj_set_pos(scr->container_3_7, 0, 1253);
    lv_obj_set_size(scr->container_3_7, 190, 158);
    lv_obj_set_scrollbar_mode(scr->container_3_7, LV_SCROLLBAR_MODE_OFF);
    lv_obj_add_flag(scr->container_3_7, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->container_3_7
    lv_obj_set_style_border_color(scr->container_3_7, lv_color_hex(0xff0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_3_7, 18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->container_3_7, LVGL_IMAGE_PATH(food_07.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->container_3_7, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->container_3_7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_3_7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_3_7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_3_7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_3_7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(scr->container_3_7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->container_3_8
    scr->container_3_8 = lv_obj_create(scr->container_3_food);
    lv_obj_set_pos(scr->container_3_8, 0, 1432);
    lv_obj_set_size(scr->container_3_8, 190, 158);
    lv_obj_set_scrollbar_mode(scr->container_3_8, LV_SCROLLBAR_MODE_OFF);
    lv_obj_add_flag(scr->container_3_8, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->container_3_8
    lv_obj_set_style_border_color(scr->container_3_8, lv_color_hex(0xff0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_3_8, 18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->container_3_8, LVGL_IMAGE_PATH(food_08.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->container_3_8, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->container_3_8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_3_8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_3_8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_3_8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_3_8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(scr->container_3_8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->container_3_9
    scr->container_3_9 = lv_obj_create(scr->container_3_food);
    lv_obj_set_pos(scr->container_3_9, 0, 1611);
    lv_obj_set_size(scr->container_3_9, 190, 158);
    lv_obj_set_scrollbar_mode(scr->container_3_9, LV_SCROLLBAR_MODE_OFF);
    lv_obj_add_flag(scr->container_3_9, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->container_3_9
    lv_obj_set_style_border_color(scr->container_3_9, lv_color_hex(0xff0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_3_9, 18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->container_3_9, LVGL_IMAGE_PATH(food_09.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->container_3_9, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->container_3_9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_3_9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_3_9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_3_9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_3_9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(scr->container_3_9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->container_3_10
    scr->container_3_10 = lv_obj_create(scr->container_3_food);
    lv_obj_set_pos(scr->container_3_10, 0, 1790);
    lv_obj_set_size(scr->container_3_10, 190, 158);
    lv_obj_set_scrollbar_mode(scr->container_3_10, LV_SCROLLBAR_MODE_OFF);
    lv_obj_add_flag(scr->container_3_10, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->container_3_10
    lv_obj_set_style_border_color(scr->container_3_10, lv_color_hex(0xff0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_3_10, 18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->container_3_10, LVGL_IMAGE_PATH(food_10.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->container_3_10, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->container_3_10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_3_10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_3_10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_3_10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_3_10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(scr->container_3_10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->container_3_11
    scr->container_3_11 = lv_obj_create(scr->container_3_food);
    lv_obj_set_pos(scr->container_3_11, 0, 1969);
    lv_obj_set_size(scr->container_3_11, 190, 158);
    lv_obj_set_scrollbar_mode(scr->container_3_11, LV_SCROLLBAR_MODE_OFF);
    lv_obj_add_flag(scr->container_3_11, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->container_3_11
    lv_obj_set_style_border_color(scr->container_3_11, lv_color_hex(0xff0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_3_11, 18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->container_3_11, LVGL_IMAGE_PATH(food_11.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->container_3_11, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->container_3_11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_3_11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_3_11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_3_11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_3_11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(scr->container_3_11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->container_3_12
    scr->container_3_12 = lv_obj_create(scr->container_3_food);
    lv_obj_set_pos(scr->container_3_12, 0, 2148);
    lv_obj_set_size(scr->container_3_12, 190, 158);
    lv_obj_set_scrollbar_mode(scr->container_3_12, LV_SCROLLBAR_MODE_OFF);
    lv_obj_add_flag(scr->container_3_12, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->container_3_12
    lv_obj_set_style_border_color(scr->container_3_12, lv_color_hex(0xff0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_3_12, 18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->container_3_12, LVGL_IMAGE_PATH(food_12.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->container_3_12, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->container_3_12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_3_12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_3_12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_3_12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_3_12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(scr->container_3_12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->container_3_13
    scr->container_3_13 = lv_obj_create(scr->container_3_food);
    lv_obj_set_pos(scr->container_3_13, 0, 2327);
    lv_obj_set_size(scr->container_3_13, 190, 158);
    lv_obj_set_scrollbar_mode(scr->container_3_13, LV_SCROLLBAR_MODE_OFF);
    lv_obj_add_flag(scr->container_3_13, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->container_3_13
    lv_obj_set_style_border_color(scr->container_3_13, lv_color_hex(0xff0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_3_13, 18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->container_3_13, LVGL_IMAGE_PATH(food_13.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->container_3_13, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->container_3_13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_3_13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_3_13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_3_13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_3_13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(scr->container_3_13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->container_3_14
    scr->container_3_14 = lv_obj_create(scr->container_3_food);
    lv_obj_set_pos(scr->container_3_14, 0, 2506);
    lv_obj_set_size(scr->container_3_14, 190, 158);
    lv_obj_set_scrollbar_mode(scr->container_3_14, LV_SCROLLBAR_MODE_OFF);
    lv_obj_add_flag(scr->container_3_14, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->container_3_14
    lv_obj_set_style_border_color(scr->container_3_14, lv_color_hex(0xff0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_3_14, 18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->container_3_14, LVGL_IMAGE_PATH(food_14.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->container_3_14, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->container_3_14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_3_14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_3_14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_3_14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_3_14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(scr->container_3_14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->container_3_15
    scr->container_3_15 = lv_obj_create(scr->container_3_food);
    lv_obj_set_pos(scr->container_3_15, 0, 2685);
    lv_obj_set_size(scr->container_3_15, 190, 158);
    lv_obj_set_scrollbar_mode(scr->container_3_15, LV_SCROLLBAR_MODE_OFF);
    lv_obj_add_flag(scr->container_3_15, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->container_3_15
    lv_obj_set_style_border_color(scr->container_3_15, lv_color_hex(0xff0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_3_15, 18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->container_3_15, LVGL_IMAGE_PATH(food_15.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->container_3_15, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->container_3_15, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_3_15, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_3_15, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_3_15, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_3_15, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(scr->container_3_15, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->container_3_16
    scr->container_3_16 = lv_obj_create(scr->container_3_food);
    lv_obj_set_pos(scr->container_3_16, 0, 2864);
    lv_obj_set_size(scr->container_3_16, 190, 158);
    lv_obj_set_scrollbar_mode(scr->container_3_16, LV_SCROLLBAR_MODE_OFF);
    lv_obj_add_flag(scr->container_3_16, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->container_3_16
    lv_obj_set_style_border_color(scr->container_3_16, lv_color_hex(0xff0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_3_16, 18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->container_3_16, LVGL_IMAGE_PATH(food_16.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->container_3_16, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->container_3_16, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_3_16, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_3_16, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_3_16, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_3_16, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(scr->container_3_16, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->container_4_t_time
    scr->container_4_t_time = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->container_4_t_time, 30, 380);
    lv_obj_set_size(scr->container_4_t_time, 872, 75);
    lv_obj_set_scrollbar_mode(scr->container_4_t_time, LV_SCROLLBAR_MODE_OFF);
    lv_obj_clear_flag(scr->container_4_t_time, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->container_4_t_time
    lv_obj_set_style_border_width(scr->container_4_t_time, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_4_t_time, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->container_4_t_time, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->container_4_t_time, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_4_t_time, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_4_t_time, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_4_t_time, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_4_t_time, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_4_t
    scr->image_4_t = lv_img_create(scr->container_4_t_time);
    lv_img_set_src(scr->image_4_t, LVGL_IMAGE_PATH(t01.png));
    lv_img_set_pivot(scr->image_4_t, 95, 79);
    lv_img_set_offset_x(scr->image_4_t, 0);
    lv_img_set_offset_y(scr->image_4_t, 0);
    lv_img_set_angle(scr->image_4_t, 0);
    lv_obj_set_pos(scr->image_4_t, 5, 0);

    // Init scr->image_5_time
    scr->image_5_time = lv_img_create(scr->container_4_t_time);
    lv_img_set_src(scr->image_5_time, LVGL_IMAGE_PATH(time01.png));
    lv_img_set_pivot(scr->image_5_time, 95, 79);
    lv_img_set_offset_x(scr->image_5_time, 0);
    lv_img_set_offset_y(scr->image_5_time, 0);
    lv_img_set_angle(scr->image_5_time, 0);
    lv_obj_set_pos(scr->image_5_time, 471, 1);

    // Init scr->slider_1_t
    scr->slider_1_t = lv_slider_create(scr->container_4_t_time);
    lv_slider_set_mode(scr->slider_1_t, LV_SLIDER_MODE_NORMAL);
    lv_slider_set_range(scr->slider_1_t, 9, 40);
    lv_slider_set_value(scr->slider_1_t, 25, LV_ANIM_OFF);
    lv_obj_set_pos(scr->slider_1_t, 5, 43);
    lv_obj_set_size(scr->slider_1_t, 393, 28);

    // Set style of scr->slider_1_t
    lv_obj_set_style_bg_color(scr->slider_1_t, lv_color_hex(0xdcdcdc), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(scr->slider_1_t, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->slider_1_t, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(scr->slider_1_t, lv_color_hex(0xe6e5eb), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->slider_1_t, lv_color_hex(0xdcdcdc), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_bg_opa(scr->slider_1_t, 255, LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_bg_color(scr->slider_1_t, lv_color_hex(0xc4330f), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->slider_1_t, lv_color_hex(0x919393), LV_PART_INDICATOR | LV_STATE_DISABLED);
    lv_obj_set_style_bg_color(scr->slider_1_t, lv_color_hex(0xc42f0d), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->slider_1_t, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->slider_1_t, 0, LV_PART_KNOB | LV_STATE_FOCUSED);

    // Set event handler of scr->slider_1_t
    lv_obj_add_event_cb(scr->slider_1_t, screen_02_main_slider_1_t_value_changed, LV_EVENT_VALUE_CHANGED, NULL);

    // Init scr->slider_2_time
    scr->slider_2_time = lv_slider_create(scr->container_4_t_time);
    lv_slider_set_mode(scr->slider_2_time, LV_SLIDER_MODE_NORMAL);
    lv_slider_set_range(scr->slider_2_time, 1, 60);
    lv_slider_set_value(scr->slider_2_time, 50, LV_ANIM_OFF);
    lv_obj_set_pos(scr->slider_2_time, 473, 43);
    lv_obj_set_size(scr->slider_2_time, 393, 28);

    // Set style of scr->slider_2_time
    lv_obj_set_style_bg_color(scr->slider_2_time, lv_color_hex(0xdcdcdc), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(scr->slider_2_time, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->slider_2_time, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(scr->slider_2_time, lv_color_hex(0xe6e5eb), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->slider_2_time, lv_color_hex(0xdcdcdc), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_bg_opa(scr->slider_2_time, 255, LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_bg_color(scr->slider_2_time, lv_color_hex(0xc4330f), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->slider_2_time, lv_color_hex(0x919393), LV_PART_INDICATOR | LV_STATE_DISABLED);
    lv_obj_set_style_bg_opa(scr->slider_2_time, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    // Set event handler of scr->slider_2_time
    lv_obj_add_event_cb(scr->slider_2_time, screen_02_main_slider_2_time_value_changed, LV_EVENT_VALUE_CHANGED, NULL);

    // Init scr->label_5_t
    scr->label_5_t = lv_label_create(scr->container_4_t_time);
    lv_label_set_text(scr->label_5_t, "130℃");
    lv_label_set_long_mode(scr->label_5_t, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_5_t, 198, 0);
    lv_obj_set_size(scr->label_5_t, 200, 33);

    // Set style of scr->label_5_t
    lv_obj_set_style_text_color(scr->label_5_t, lv_color_hex(0xe47a46), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_5_t, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_5_t, fs_montserratmedium_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_6_time
    scr->label_6_time = lv_label_create(scr->container_4_t_time);
    lv_label_set_text(scr->label_6_time, "20 MIN");
    lv_label_set_long_mode(scr->label_6_time, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_6_time, 657, 0);
    lv_obj_set_size(scr->label_6_time, 200, 33);

    // Set style of scr->label_6_time
    lv_obj_set_style_text_color(scr->label_6_time, lv_color_hex(0xe47a46), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_6_time, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_6_time, fs_montserratmedium_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_1_28_28
    scr->image_1_28_28 = lv_img_create(scr->container_4_t_time);
    lv_img_set_src(scr->image_1_28_28, LVGL_IMAGE_PATH(icon_28x28.png));
    lv_img_set_pivot(scr->image_1_28_28, 50, 50);
    lv_img_set_offset_x(scr->image_1_28_28, 0);
    lv_img_set_offset_y(scr->image_1_28_28, 0);
    lv_img_set_angle(scr->image_1_28_28, 0);
    lv_obj_set_pos(scr->image_1_28_28, 5, 43);

    // Set style of scr->image_1_28_28
    lv_obj_set_style_img_recolor_opa(scr->image_1_28_28, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor(scr->image_1_28_28, lv_color_hex(0xc4300e), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_2_28_28
    scr->image_2_28_28 = lv_img_create(scr->container_4_t_time);
    lv_img_set_src(scr->image_2_28_28, LVGL_IMAGE_PATH(icon_28x28.png));
    lv_img_set_pivot(scr->image_2_28_28, 50, 50);
    lv_img_set_offset_x(scr->image_2_28_28, 0);
    lv_img_set_offset_y(scr->image_2_28_28, 0);
    lv_img_set_angle(scr->image_2_28_28, 0);
    lv_obj_set_pos(scr->image_2_28_28, 473, 43);

    // Set style of scr->image_2_28_28
    lv_obj_set_style_img_recolor_opa(scr->image_2_28_28, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor(scr->image_2_28_28, lv_color_hex(0xc4300e), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->container_5_function_button
    scr->container_5_function_button = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->container_5_function_button, 30, 480);
    lv_obj_set_size(scr->container_5_function_button, 872, 76);
    lv_obj_set_scrollbar_mode(scr->container_5_function_button, LV_SCROLLBAR_MODE_OFF);
    lv_obj_clear_flag(scr->container_5_function_button, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->container_5_function_button
    lv_obj_set_style_border_width(scr->container_5_function_button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_5_function_button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->container_5_function_button, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->container_5_function_button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_5_function_button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_5_function_button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_5_function_button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_5_function_button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_6_lamp
    scr->image_6_lamp = lv_img_create(scr->container_5_function_button);
    lv_img_set_src(scr->image_6_lamp, LVGL_IMAGE_PATH(lamp_off.png));
    lv_img_set_pivot(scr->image_6_lamp, 50, 50);
    lv_img_set_offset_x(scr->image_6_lamp, 0);
    lv_img_set_offset_y(scr->image_6_lamp, 0);
    lv_img_set_angle(scr->image_6_lamp, 0);
    lv_obj_set_pos(scr->image_6_lamp, 338, 4);
    lv_obj_add_flag(scr->image_6_lamp, LV_OBJ_FLAG_CLICKABLE);

    // Set event handler of scr->image_6_lamp
    lv_obj_add_event_cb(scr->image_6_lamp, screen_02_main_image_6_lamp_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->image_7_stop_run
    scr->image_7_stop_run = lv_img_create(scr->container_5_function_button);
    lv_img_set_src(scr->image_7_stop_run, LVGL_IMAGE_PATH(icon_stop_0.png));
    lv_img_set_pivot(scr->image_7_stop_run, 50, 50);
    lv_img_set_offset_x(scr->image_7_stop_run, 0);
    lv_img_set_offset_y(scr->image_7_stop_run, 0);
    lv_img_set_angle(scr->image_7_stop_run, 0);
    lv_obj_set_pos(scr->image_7_stop_run, 464, 4);
    lv_obj_add_flag(scr->image_7_stop_run, LV_OBJ_FLAG_CLICKABLE);

    // Set event handler of scr->image_7_stop_run
    lv_obj_add_event_cb(scr->image_7_stop_run, screen_02_main_image_7_stop_run_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->label_1_airfry
    scr->label_1_airfry = lv_label_create(scr->container_5_function_button);
    lv_label_set_text(scr->label_1_airfry, "AIR FRY");
    lv_label_set_long_mode(scr->label_1_airfry, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_obj_set_pos(scr->label_1_airfry, 0, 4);
    lv_obj_set_size(scr->label_1_airfry, 145, 67);
    lv_obj_add_flag(scr->label_1_airfry, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->label_1_airfry
    lv_obj_set_style_border_width(scr->label_1_airfry, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(scr->label_1_airfry, lv_color_hex(0xc4300e), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_1_airfry, lv_color_hex(0x615f5f), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->label_1_airfry, lv_color_hex(0xc4300e), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_1_airfry, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->label_1_airfry, 18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->label_1_airfry, 18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_1_airfry, fs_montserratmedium_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->label_1_airfry
    lv_obj_add_event_cb(scr->label_1_airfry, screen_02_main_label_1_airfry_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->label_2_bake
    scr->label_2_bake = lv_label_create(scr->container_5_function_button);
    lv_label_set_text(scr->label_2_bake, "BAKE");
    lv_label_set_long_mode(scr->label_2_bake, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_obj_set_pos(scr->label_2_bake, 166, 4);
    lv_obj_set_size(scr->label_2_bake, 145, 67);
    lv_obj_add_flag(scr->label_2_bake, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->label_2_bake
    lv_obj_set_style_border_width(scr->label_2_bake, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(scr->label_2_bake, lv_color_hex(0xc4300e), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_2_bake, lv_color_hex(0x615f5f), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->label_2_bake, lv_color_hex(0xc4300e), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_2_bake, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->label_2_bake, 18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->label_2_bake, 18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_2_bake, fs_montserratmedium_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->label_2_bake
    lv_obj_add_event_cb(scr->label_2_bake, screen_02_main_label_2_bake_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->label_3_preheat
    scr->label_3_preheat = lv_label_create(scr->container_5_function_button);
    lv_label_set_text(scr->label_3_preheat, "PREHEAT");
    lv_label_set_long_mode(scr->label_3_preheat, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_obj_set_pos(scr->label_3_preheat, 559, 4);
    lv_obj_set_size(scr->label_3_preheat, 145, 67);
    lv_obj_add_flag(scr->label_3_preheat, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->label_3_preheat
    lv_obj_set_style_border_width(scr->label_3_preheat, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(scr->label_3_preheat, lv_color_hex(0xc4300e), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_3_preheat, lv_color_hex(0x615f5f), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->label_3_preheat, lv_color_hex(0xc4300e), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_3_preheat, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->label_3_preheat, 18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->label_3_preheat, 18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_3_preheat, fs_montserratmedium_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->label_3_preheat
    lv_obj_add_event_cb(scr->label_3_preheat, screen_02_main_label_3_preheat_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->label_4_dehydrate
    scr->label_4_dehydrate = lv_label_create(scr->container_5_function_button);
    lv_label_set_text(scr->label_4_dehydrate, "DEHYDRATE");
    lv_label_set_long_mode(scr->label_4_dehydrate, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_obj_set_pos(scr->label_4_dehydrate, 727, 4);
    lv_obj_set_size(scr->label_4_dehydrate, 145, 67);
    lv_obj_add_flag(scr->label_4_dehydrate, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->label_4_dehydrate
    lv_obj_set_style_border_width(scr->label_4_dehydrate, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(scr->label_4_dehydrate, lv_color_hex(0xc4300e), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_4_dehydrate, lv_color_hex(0x615f5f), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->label_4_dehydrate, lv_color_hex(0xc4300e), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_4_dehydrate, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->label_4_dehydrate, 18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->label_4_dehydrate, 18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_4_dehydrate, fs_montserratmedium_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->label_4_dehydrate
    lv_obj_add_event_cb(scr->label_4_dehydrate, screen_02_main_label_4_dehydrate_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->container_6_pop_up
    scr->container_6_pop_up = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->container_6_pop_up, 0, 0);
    lv_obj_set_size(scr->container_6_pop_up, 1152, 576);
    lv_obj_set_scrollbar_mode(scr->container_6_pop_up, LV_SCROLLBAR_MODE_OFF);
    lv_obj_add_flag(scr->container_6_pop_up, LV_OBJ_FLAG_HIDDEN);

    // Set style of scr->container_6_pop_up
    lv_obj_set_style_border_width(scr->container_6_pop_up, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_6_pop_up, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->container_6_pop_up, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->container_6_pop_up, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_6_pop_up, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_6_pop_up, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_6_pop_up, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_6_pop_up, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->container_6_pop_up
    lv_obj_add_event_cb(scr->container_6_pop_up, screen_02_main_container_6_pop_up_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->container_6_pop_up_1
    scr->container_6_pop_up_1 = lv_obj_create(scr->container_6_pop_up);
    lv_obj_set_pos(scr->container_6_pop_up_1, 126, 88);
    lv_obj_set_size(scr->container_6_pop_up_1, 900, 400);
    lv_obj_set_scrollbar_mode(scr->container_6_pop_up_1, LV_SCROLLBAR_MODE_OFF);
    lv_obj_clear_flag(scr->container_6_pop_up_1, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->container_6_pop_up_1
    lv_obj_set_style_border_width(scr->container_6_pop_up_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_6_pop_up_1, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->container_6_pop_up_1, LVGL_IMAGE_PATH(pop_upp_prompt_image.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_6_pop_up_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_6_pop_up_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_6_pop_up_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_6_pop_up_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_6_pop_up_1_insert_basket
    scr->label_6_pop_up_1_insert_basket = lv_label_create(scr->container_6_pop_up_1);
    lv_label_set_text(scr->label_6_pop_up_1_insert_basket, "请插入炸篮");
    lv_label_set_long_mode(scr->label_6_pop_up_1_insert_basket, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_6_pop_up_1_insert_basket, 50, 340);
    lv_obj_set_size(scr->label_6_pop_up_1_insert_basket, 800, 40);

    // Set style of scr->label_6_pop_up_1_insert_basket
    lv_obj_set_style_border_opa(scr->label_6_pop_up_1_insert_basket, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(scr->label_6_pop_up_1_insert_basket, lv_color_hex(0xc4300e), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_6_pop_up_1_insert_basket, lv_color_hex(0x615f5f), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->label_6_pop_up_1_insert_basket, lv_color_hex(0xc4300e), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_6_pop_up_1_insert_basket, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->label_6_pop_up_1_insert_basket, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_6_pop_up_1_insert_basket, fs_montserratmedium_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->button_2_x
    scr->button_2_x = lv_btn_create(scr->container_6_pop_up_1);
    lv_obj_t *button_2_x_label = lv_label_create(scr->button_2_x);
    lv_label_set_text(button_2_x_label, "");
    lv_obj_align(button_2_x_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->button_2_x, 810, 5);
    lv_obj_set_size(scr->button_2_x, 80, 50);

    // Set style of scr->button_2_x
    lv_obj_set_style_shadow_width(scr->button_2_x, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->button_2_x, LVGL_IMAGE_PATH(icon_x.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->button_2_x, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->button_2_x, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->button_2_x
    lv_obj_add_event_cb(scr->button_2_x, screen_02_main_button_2_x_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->container_7_toast_notification
    scr->container_7_toast_notification = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->container_7_toast_notification, 0, 0);
    lv_obj_set_size(scr->container_7_toast_notification, 1152, 576);
    lv_obj_set_scrollbar_mode(scr->container_7_toast_notification, LV_SCROLLBAR_MODE_OFF);
    lv_obj_add_flag(scr->container_7_toast_notification, LV_OBJ_FLAG_HIDDEN);

    // Set style of scr->container_7_toast_notification
    lv_obj_set_style_border_width(scr->container_7_toast_notification, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_7_toast_notification, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->container_7_toast_notification, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->container_7_toast_notification, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_7_toast_notification, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_7_toast_notification, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_7_toast_notification, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_7_toast_notification, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->container_7_toast_notification
    lv_obj_add_event_cb(scr->container_7_toast_notification, screen_02_main_container_7_toast_notification_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->label_10_toast_notification
    scr->label_10_toast_notification = lv_label_create(scr->container_7_toast_notification);
    lv_label_set_text(scr->label_10_toast_notification, "弹框提示");
    lv_label_set_long_mode(scr->label_10_toast_notification, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_10_toast_notification, 326, 167);
    lv_obj_set_size(scr->label_10_toast_notification, 500, 205);

    // Set style of scr->label_10_toast_notification
    lv_obj_set_style_text_color(scr->label_10_toast_notification, lv_color_hex(0x615f5f), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->label_10_toast_notification, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_10_toast_notification, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->label_10_toast_notification, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->label_10_toast_notification, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->label_10_toast_notification, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_10_toast_notification, fs_montserratmedium_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    screen_02_main_custom_created();
}


