/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by UIBuilder
 * UIBuilder version: v2.1.0
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"


void __attribute__((weak)) screen_09_F_to_C_custom_created(void) {
}

static void screen_09_F_to_C_button_1_back_clicked (lv_event_t *e) {
    lv_obj_t *act_scr = lv_scr_act();
    if (!screen_is_loading(act_scr)) {
        // create screen_03_setting
        screen_03_setting_create(&ui_manager);
        // load screen_03_setting
        lv_scr_load_anim(screen_03_setting_get(&ui_manager)->obj, LV_SCR_LOAD_ANIM_NONE, 1, 0, ui_manager.auto_del);
    }
}

void __attribute__((weak)) screen_09_F_to_C_container_2_f_custom_clicked(void) {
}

static void screen_09_F_to_C_container_2_f_clicked (lv_event_t *e) {
    screen_09_F_to_C_container_2_f_custom_clicked();
}

void __attribute__((weak)) screen_09_F_to_C_container_3_c_custom_clicked(void) {
}

static void screen_09_F_to_C_container_3_c_clicked (lv_event_t *e) {
    screen_09_F_to_C_container_3_c_custom_clicked();
}


void screen_09_F_to_C_create(ui_manager_t *ui)
{
    screen_09_F_to_C_t *scr = screen_09_F_to_C_get(ui);

    if (!ui->auto_del && scr->obj) {
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0xf2f2f2), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->button_1_back
    scr->button_1_back = lv_btn_create(scr->obj);
    lv_obj_t *button_1_back_label = lv_label_create(scr->button_1_back);
    lv_label_set_text(button_1_back_label, "");
    lv_obj_align(button_1_back_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->button_1_back, 5, 20);
    lv_obj_set_size(scr->button_1_back, 80, 40);

    // Set style of scr->button_1_back
    lv_obj_set_style_shadow_width(scr->button_1_back, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->button_1_back, LVGL_IMAGE_PATH(back.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->button_1_back, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->button_1_back, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->button_1_back
    lv_obj_add_event_cb(scr->button_1_back, screen_09_F_to_C_button_1_back_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->label_0_f_to_c
    scr->label_0_f_to_c = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_0_f_to_c, "°F to °C");
    lv_label_set_long_mode(scr->label_0_f_to_c, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_0_f_to_c, 326, 15);
    lv_obj_set_size(scr->label_0_f_to_c, 500, 50);

    // Set style of scr->label_0_f_to_c
    lv_obj_set_style_text_color(scr->label_0_f_to_c, lv_color_hex(0xc4330f), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_0_f_to_c, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_0_f_to_c, fs_montserratmedium_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->container_1_F_to_C
    scr->container_1_F_to_C = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->container_1_F_to_C, 30, 82);
    lv_obj_set_size(scr->container_1_F_to_C, 1092, 72);
    lv_obj_set_scrollbar_mode(scr->container_1_F_to_C, LV_SCROLLBAR_MODE_OFF);
    lv_obj_clear_flag(scr->container_1_F_to_C, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->container_1_F_to_C
    lv_obj_set_style_border_width(scr->container_1_F_to_C, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_1_F_to_C, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_1_F_to_C, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_1_F_to_C, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_1_F_to_C, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_1_F_to_C, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_1_f_to_c
    scr->label_1_f_to_c = lv_label_create(scr->container_1_F_to_C);
    lv_label_set_text(scr->label_1_f_to_c, "°F to °C");
    lv_label_set_long_mode(scr->label_1_f_to_c, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_1_f_to_c, 20, 19);
    lv_obj_set_size(scr->label_1_f_to_c, 211, 34);

    // Set style of scr->label_1_f_to_c
    lv_obj_set_style_text_color(scr->label_1_f_to_c, lv_color_hex(0x615f5f), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_1_f_to_c, fs_montserratmedium_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->container_2_f
    scr->container_2_f = lv_obj_create(scr->container_1_F_to_C);
    lv_obj_set_pos(scr->container_2_f, 758, 0);
    lv_obj_set_size(scr->container_2_f, 142, 72);
    lv_obj_set_scrollbar_mode(scr->container_2_f, LV_SCROLLBAR_MODE_OFF);
    lv_obj_add_flag(scr->container_2_f, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->container_2_f
    lv_obj_set_style_border_width(scr->container_2_f, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_2_f, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->container_2_f, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->container_2_f, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_2_f, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_2_f, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_2_f, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_2_f, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->container_2_f
    lv_obj_add_event_cb(scr->container_2_f, screen_09_F_to_C_container_2_f_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->image_1_f
    scr->image_1_f = lv_img_create(scr->container_2_f);
    lv_img_set_src(scr->image_1_f, LVGL_IMAGE_PATH(set_time0.png));
    lv_img_set_pivot(scr->image_1_f, 50, 50);
    lv_img_set_offset_x(scr->image_1_f, 0);
    lv_img_set_offset_y(scr->image_1_f, 0);
    lv_img_set_angle(scr->image_1_f, 0);
    lv_obj_set_pos(scr->image_1_f, 5, 25);

    // Init scr->label_2_f
    scr->label_2_f = lv_label_create(scr->container_2_f);
    lv_label_set_text(scr->label_2_f, "°F,0z");
    lv_label_set_long_mode(scr->label_2_f, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_2_f, 37, 19);
    lv_obj_set_size(scr->label_2_f, 100, 34);

    // Set style of scr->label_2_f
    lv_obj_set_style_text_color(scr->label_2_f, lv_color_hex(0x615f5f), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_2_f, fs_montserratmedium_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->container_3_c
    scr->container_3_c = lv_obj_create(scr->container_1_F_to_C);
    lv_obj_set_pos(scr->container_3_c, 940, 0);
    lv_obj_set_size(scr->container_3_c, 142, 72);
    lv_obj_set_scrollbar_mode(scr->container_3_c, LV_SCROLLBAR_MODE_OFF);
    lv_obj_add_flag(scr->container_3_c, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->container_3_c
    lv_obj_set_style_border_width(scr->container_3_c, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_3_c, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->container_3_c, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->container_3_c, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_3_c, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_3_c, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_3_c, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_3_c, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->container_3_c
    lv_obj_add_event_cb(scr->container_3_c, screen_09_F_to_C_container_3_c_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->label_3_c
    scr->label_3_c = lv_label_create(scr->container_3_c);
    lv_label_set_text(scr->label_3_c, "°C,g");
    lv_label_set_long_mode(scr->label_3_c, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_3_c, 37, 19);
    lv_obj_set_size(scr->label_3_c, 100, 34);

    // Set style of scr->label_3_c
    lv_obj_set_style_text_color(scr->label_3_c, lv_color_hex(0x615f5f), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_3_c, fs_montserratmedium_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_2_c
    scr->image_2_c = lv_img_create(scr->container_3_c);
    lv_img_set_src(scr->image_2_c, LVGL_IMAGE_PATH(set_time1.png));
    lv_img_set_pivot(scr->image_2_c, 50, 50);
    lv_img_set_offset_x(scr->image_2_c, 0);
    lv_img_set_offset_y(scr->image_2_c, 0);
    lv_img_set_angle(scr->image_2_c, 0);
    lv_obj_set_pos(scr->image_2_c, 5, 25);

    screen_09_F_to_C_custom_created();
}


