/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by UIBuilder
 * UIBuilder version: v2.1.0
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"


void __attribute__((weak)) screen_13_screensaver_custom_created(void) {
}
void __attribute__((weak)) screen_13_screensaver_custom_loaded(void) {
}
void __attribute__((weak)) screen_13_screensaver_custom_unloaded(void) {
}

static void screen_13_screensaver_unloaded (lv_event_t *e) {
    screen_13_screensaver_custom_unloaded();
}

static void screen_13_screensaver_loaded (lv_event_t *e) {
    screen_13_screensaver_custom_loaded();
}

void __attribute__((weak)) screen_13_screensaver_button_1_back_custom_pressed(void) {
}

static void screen_13_screensaver_button_1_back_pressed (lv_event_t *e) {
    screen_13_screensaver_button_1_back_custom_pressed();
}


void screen_13_screensaver_create(ui_manager_t *ui)
{
    screen_13_screensaver_t *scr = screen_13_screensaver_get(ui);

    if (!ui->auto_del && scr->obj) {
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->obj
    lv_obj_add_event_cb(scr->obj, screen_13_screensaver_unloaded, LV_EVENT_SCREEN_UNLOADED, NULL);
    lv_obj_add_event_cb(scr->obj, screen_13_screensaver_loaded, LV_EVENT_SCREEN_LOADED, NULL);

    // Init scr->container_1
    scr->container_1 = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->container_1, 336, 48);
    lv_obj_set_size(scr->container_1, 480, 480);
    lv_obj_set_scrollbar_mode(scr->container_1, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->container_1
    lv_obj_set_style_border_width(scr->container_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->container_1, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->container_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_1_time
    scr->label_1_time = lv_label_create(scr->container_1);
    lv_label_set_text(scr->label_1_time, "00:00");
    lv_label_set_long_mode(scr->label_1_time, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_1_time, 80, 120);
    lv_obj_set_size(scr->label_1_time, 330, 156);

    // Set style of scr->label_1_time
    lv_obj_set_style_text_color(scr->label_1_time, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_1_time, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_1_time, fs_montserratmedium_110, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_2_am_pm
    scr->label_2_am_pm = lv_label_create(scr->container_1);
    lv_label_set_text(scr->label_2_am_pm, "AM");
    lv_label_set_long_mode(scr->label_2_am_pm, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_2_am_pm, 75, 250);
    lv_obj_set_size(scr->label_2_am_pm, 330, 156);

    // Set style of scr->label_2_am_pm
    lv_obj_set_style_text_color(scr->label_2_am_pm, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_2_am_pm, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_2_am_pm, fs_montserratmedium_110, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->container_2
    scr->container_2 = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->container_2, 336, 48);
    lv_obj_set_size(scr->container_2, 480, 480);
    lv_obj_set_scrollbar_mode(scr->container_2, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->container_2
    lv_obj_set_style_border_width(scr->container_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->container_2, LVGL_IMAGE_PATH(screensaver_2.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->container_2, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_1_h
    scr->image_1_h = lv_img_create(scr->container_2);
    lv_img_set_src(scr->image_1_h, LVGL_IMAGE_PATH(screensaver_h.png));
    lv_img_set_pivot(scr->image_1_h, 21, 135);
    lv_img_set_offset_x(scr->image_1_h, 0);
    lv_img_set_offset_y(scr->image_1_h, 0);
    lv_img_set_angle(scr->image_1_h, 0);
    lv_obj_set_pos(scr->image_1_h, 218, 104);

    // Init scr->image_2_m
    scr->image_2_m = lv_img_create(scr->container_2);
    lv_img_set_src(scr->image_2_m, LVGL_IMAGE_PATH(screensaver_m.png));
    lv_img_set_pivot(scr->image_2_m, 17, 183);
    lv_img_set_offset_x(scr->image_2_m, 0);
    lv_img_set_offset_y(scr->image_2_m, 0);
    lv_img_set_angle(scr->image_2_m, 0);
    lv_obj_set_pos(scr->image_2_m, 222, 56);

    // Init scr->image_3_s
    scr->image_3_s = lv_img_create(scr->container_2);
    lv_img_set_src(scr->image_3_s, LVGL_IMAGE_PATH(screensaver_s.png));
    lv_img_set_pivot(scr->image_3_s, 8, 199);
    lv_img_set_offset_x(scr->image_3_s, 0);
    lv_img_set_offset_y(scr->image_3_s, 0);
    lv_img_set_angle(scr->image_3_s, 0);
    lv_obj_set_pos(scr->image_3_s, 231, 40);

    // Init scr->button_1_back
    scr->button_1_back = lv_btn_create(scr->obj);
    lv_obj_t *button_1_back_label = lv_label_create(scr->button_1_back);
    lv_label_set_text(button_1_back_label, "");
    lv_obj_align(button_1_back_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->button_1_back, 0, 0);
    lv_obj_set_size(scr->button_1_back, 1152, 576);

    // Set style of scr->button_1_back
    lv_obj_set_style_shadow_opa(scr->button_1_back, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->button_1_back, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(scr->button_1_back, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->button_1_back, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->button_1_back, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(scr->button_1_back, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->button_1_back, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->button_1_back
    lv_obj_add_event_cb(scr->button_1_back, screen_13_screensaver_button_1_back_pressed, LV_EVENT_PRESSED, NULL);

    screen_13_screensaver_custom_created();
}


