/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by UIBuilder
 * UIBuilder version: v2.1.0
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"


void __attribute__((weak)) screen_08_sound_custom_created(void) {
}

static void screen_08_sound_button_1_back_clicked (lv_event_t *e) {
    lv_obj_t *act_scr = lv_scr_act();
    if (!screen_is_loading(act_scr)) {
        // create screen_03_setting
        screen_03_setting_create(&ui_manager);
        // load screen_03_setting
        lv_scr_load_anim(screen_03_setting_get(&ui_manager)->obj, LV_SCR_LOAD_ANIM_NONE, 1, 0, ui_manager.auto_del);
    }
}

void __attribute__((weak)) screen_08_sound_switch_1_sound_custom_clicked(void) {
}

static void screen_08_sound_switch_1_sound_clicked (lv_event_t *e) {
    screen_08_sound_switch_1_sound_custom_clicked();
}


void screen_08_sound_create(ui_manager_t *ui)
{
    screen_08_sound_t *scr = screen_08_sound_get(ui);

    if (!ui->auto_del && scr->obj) {
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0xf2f2f2), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->button_1_back
    scr->button_1_back = lv_btn_create(scr->obj);
    lv_obj_t *button_1_back_label = lv_label_create(scr->button_1_back);
    lv_label_set_text(button_1_back_label, "");
    lv_obj_align(button_1_back_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->button_1_back, 5, 20);
    lv_obj_set_size(scr->button_1_back, 80, 40);

    // Set style of scr->button_1_back
    lv_obj_set_style_shadow_width(scr->button_1_back, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->button_1_back, LVGL_IMAGE_PATH(back.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->button_1_back, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->button_1_back, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->button_1_back
    lv_obj_add_event_cb(scr->button_1_back, screen_08_sound_button_1_back_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->label_0_sound
    scr->label_0_sound = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_0_sound, "Sound");
    lv_label_set_long_mode(scr->label_0_sound, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_0_sound, 326, 15);
    lv_obj_set_size(scr->label_0_sound, 500, 50);

    // Set style of scr->label_0_sound
    lv_obj_set_style_text_color(scr->label_0_sound, lv_color_hex(0xc4330f), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_0_sound, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_0_sound, fs_montserratmedium_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->container_1_sound
    scr->container_1_sound = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->container_1_sound, 30, 82);
    lv_obj_set_size(scr->container_1_sound, 1092, 72);
    lv_obj_set_scrollbar_mode(scr->container_1_sound, LV_SCROLLBAR_MODE_OFF);
    lv_obj_clear_flag(scr->container_1_sound, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->container_1_sound
    lv_obj_set_style_border_width(scr->container_1_sound, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_1_sound, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_1_sound, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_1_sound, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_1_sound, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_1_sound, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_1_sound
    scr->label_1_sound = lv_label_create(scr->container_1_sound);
    lv_label_set_text(scr->label_1_sound, "Sound");
    lv_label_set_long_mode(scr->label_1_sound, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_1_sound, 20, 19);
    lv_obj_set_size(scr->label_1_sound, 211, 34);

    // Set style of scr->label_1_sound
    lv_obj_set_style_text_color(scr->label_1_sound, lv_color_hex(0x615f5f), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_1_sound, fs_montserratmedium_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->switch_1_sound
    scr->switch_1_sound = lv_switch_create(scr->container_1_sound);
    lv_obj_set_pos(scr->switch_1_sound, 973, 15);
    lv_obj_set_size(scr->switch_1_sound, 99, 41);

    // Set style of scr->switch_1_sound
    lv_obj_set_style_bg_color(scr->switch_1_sound, lv_color_hex(0xa95806), LV_PART_INDICATOR | LV_STATE_CHECKED);

    // Set event handler of scr->switch_1_sound
    lv_obj_add_event_cb(scr->switch_1_sound, screen_08_sound_switch_1_sound_clicked, LV_EVENT_CLICKED, NULL);

    screen_08_sound_custom_created();
}


