# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.29

# compile C with D:/Program Files (x86)/AiUIBuilder/tool/mingw/bin/gcc.exe
C_DEFINES = -DFT2_BUILD_LIBRARY -DHAVE_FCNTL_H -DHAVE_UNISTD_H -DLVGL_DIR=\"L:F:/AiUlBuilder/LVGL/1152x576_fan_img/simulator/../ui_builder/assets/\" -DLVGL_STORAGE_PATH=\"F:/AiUlBuilder/LVGL/1152x576_fan_img/simulator/../ui_builder/assets/\" -DLV_CONF_INCLUDE_SIMPLE

C_INCLUDES = @CMakeFiles/main.dir/includes_C.rsp

C_FLAGS = -std=gnu11

