/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by UIBuilder
 * UIBuilder version: v2.1.0
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"


void __attribute__((weak)) screen_10_version_custom_created(void) {
}

static void screen_10_version_button_1_back_clicked (lv_event_t *e) {
    lv_obj_t *act_scr = lv_scr_act();
    if (!screen_is_loading(act_scr)) {
        // create screen_03_setting
        screen_03_setting_create(&ui_manager);
        // load screen_03_setting
        lv_scr_load_anim(screen_03_setting_get(&ui_manager)->obj, LV_SCR_LOAD_ANIM_NONE, 1, 0, ui_manager.auto_del);
    }
}


void screen_10_version_create(ui_manager_t *ui)
{
    screen_10_version_t *scr = screen_10_version_get(ui);

    if (!ui->auto_del && scr->obj) {
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0xf2f2f2), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->button_1_back
    scr->button_1_back = lv_btn_create(scr->obj);
    lv_obj_t *button_1_back_label = lv_label_create(scr->button_1_back);
    lv_label_set_text(button_1_back_label, "");
    lv_obj_align(button_1_back_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->button_1_back, 5, 20);
    lv_obj_set_size(scr->button_1_back, 80, 40);

    // Set style of scr->button_1_back
    lv_obj_set_style_shadow_width(scr->button_1_back, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->button_1_back, LVGL_IMAGE_PATH(back.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->button_1_back, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->button_1_back, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->button_1_back
    lv_obj_add_event_cb(scr->button_1_back, screen_10_version_button_1_back_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->label_0_version
    scr->label_0_version = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_0_version, "Version");
    lv_label_set_long_mode(scr->label_0_version, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_0_version, 326, 15);
    lv_obj_set_size(scr->label_0_version, 500, 50);

    // Set style of scr->label_0_version
    lv_obj_set_style_text_color(scr->label_0_version, lv_color_hex(0xc4330f), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_0_version, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_0_version, fs_montserratmedium_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->container_1
    scr->container_1 = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->container_1, 30, 82);
    lv_obj_set_size(scr->container_1, 1092, 62);
    lv_obj_set_scrollbar_mode(scr->container_1, LV_SCROLLBAR_MODE_OFF);
    lv_obj_clear_flag(scr->container_1, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->container_1
    lv_obj_set_style_border_width(scr->container_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_1_version
    scr->label_1_version = lv_label_create(scr->container_1);
    lv_label_set_text(scr->label_1_version, "Version");
    lv_label_set_long_mode(scr->label_1_version, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_1_version, 20, 14);
    lv_obj_set_size(scr->label_1_version, 211, 34);

    // Set style of scr->label_1_version
    lv_obj_set_style_text_color(scr->label_1_version, lv_color_hex(0x615f5f), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_1_version, fs_montserratmedium_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_2_version_V
    scr->label_2_version_V = lv_label_create(scr->container_1);
    lv_label_set_text(scr->label_2_version_V, "V_1.0.0");
    lv_label_set_long_mode(scr->label_2_version_V, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_2_version_V, 872, 14);
    lv_obj_set_size(scr->label_2_version_V, 200, 34);

    // Set style of scr->label_2_version_V
    lv_obj_set_style_text_color(scr->label_2_version_V, lv_color_hex(0x615f5f), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_2_version_V, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_2_version_V, fs_montserratmedium_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    screen_10_version_custom_created();
}


