/*
 * Copyright (C) 2025 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v2.0.1
 */

#ifndef CUSTOM_CODE
#define CUSTOM_CODE
#ifdef __cplusplus
extern "C" {
#endif

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"

#include "yk_ui_common.h"

#include "./driver/apps.h"
#include "yk_file_flash.h"
#include "yk_lang.h"
#include "yk_pwm_set.h"
#include "yk_rtc.h"
#include "yk_touch.h"
#include "yk_view_i.h"

#define P_TEST_MODE 0   //彭总自己的五寸空气炸锅 0：572(AC) 1：6001(AC) 2:AB800C(DC)-- 彭总用
//是否是美规 0:否 1:是
#define YK_US_ENGLISH 0

//直流还是交流
#define YK_DC_AC 0  //1:DC直流 0:AC交流

#define CUSTOM_SCREEN_3_BAKE_LOG  1  //打印信息在烘烤界面上 1 打印 0 不打印


#define YK_USE_PM 1  //0:关闭 1:开启 -- 定义一个是否需要开启低功耗模式的宏

#define YK_COLOR_BG_LIGHT  0xf2f2f2
#define YK_COLOR_BG_DARK  0x2F2F2F
#define YK_COLOR_COUNT_LIGHT  0xffffff
#define YK_COLOR_COUNT_DARK  0x3f3f3f
#define YK_COLOR_LBL_LIGHT  0x615f5f
#define YK_COLOR_LBL_DARK  0xffffff


#define YK_FOOD_SUM 17  // 食物总数
#define FAVORITE_FLAG_DIY_BASE 200u
extern uint8_t yk_food_flag;
extern uint8_t yk_diy_flag;
extern uint32_t yk_active_favorite_flag;
extern bool yk_active_from_favorites;
extern uint16_t yk_v_food_t_f;
extern uint16_t yk_v_food_min;


extern uint16_t screensaver_time;


void custom_init();


void screen_02_main_run_custom_created(void);
// 食物信息结构体
typedef struct {
    const char* ingredients;        // 食物材料
    const char* steps;              // 食物步骤
} food_info_t;
extern food_info_t yk_food_info[YK_FOOD_SUM];
extern bool yk_v_stop_run_state;
extern bool yk_v_lamp_state;
void yk_f_run(void);
void yk_f_pause(void);
void food_tf_time(uint16_t foof_t_f,uint16_t foof_min);
void update_all_containers_border_opa(uint8_t food_flag);
void yk_show_toast(lv_obj_t *toast, const char *txt, uint32_t ms);
void yk_main_refresh_love_icon(void);
void yk_main_update_ui_text(void);

#if YK_USE_PM
// 设置屏保倒计时时间
void screensaver_set_pm_countdown(uint16_t time);
#endif

// Favorites API
void yk_favorites_add(lv_obj_t *parent, const void *img_src, const char *name, uint16_t temp, uint16_t time_min);
int yk_favorites_has_img(const void *img_src);
int yk_favorites_get_count(void);
void yk_favorites_reload_from_settings(void);
void yk_favorites_update_ui_text(void);
// Use flag-based APIs for add/remove checks
void yk_favorites_remove_by_flag(uint32_t food_flag);
int yk_favorites_has_flag(uint32_t food_flag);

#ifdef __cplusplus
}
#endif
#endif /* CUSTOM_CODE */
