/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by UIBuilder
 * UIBuilder version: v2.1.0
 */

#include "ui_init.h"
#include "ui_util.h"
#include "aic_ui.h"
#include "custom/custom.h"

ui_manager_t ui_manager;

lv_font_t *fs_montserratmedium_16;
lv_font_t *fs_montserratmedium_25;
lv_font_t *fs_montserratmedium_47;
lv_font_t *fs_montserratmedium_34;
lv_font_t *fs_montserratmedium_22;
lv_font_t *fs_montserratmedium_20;
lv_font_t *fs_montserratmedium_30;
lv_font_t *fs_montserratmedium_24;
lv_font_t *fs_montserratmedium_36;
lv_font_t *fs_montserratmedium_26;
lv_font_t *fs_montserratmedium_110;

void ui_init(void)
{
    fs_montserratmedium_16 = ui_font_init(LVGL_FONT_PATH(montserratMedium.ttf), 16);
    fs_montserratmedium_25 = ui_font_init(LVGL_FONT_PATH(montserratMedium.ttf), 25);
    fs_montserratmedium_47 = ui_font_init(LVGL_FONT_PATH(montserratMedium.ttf), 47);
    fs_montserratmedium_34 = ui_font_init(LVGL_FONT_PATH(montserratMedium.ttf), 34);
    fs_montserratmedium_22 = ui_font_init(LVGL_FONT_PATH(montserratMedium.ttf), 22);
    fs_montserratmedium_20 = ui_font_init(LVGL_FONT_PATH(montserratMedium.ttf), 20);
    fs_montserratmedium_30 = ui_font_init(LVGL_FONT_PATH(montserratMedium.ttf), 30);
    fs_montserratmedium_24 = ui_font_init(LVGL_FONT_PATH(montserratMedium.ttf), 24);
    fs_montserratmedium_36 = ui_font_init(LVGL_FONT_PATH(montserratMedium.ttf), 36);
    fs_montserratmedium_26 = ui_font_init(LVGL_FONT_PATH(montserratMedium.ttf), 26);
    fs_montserratmedium_110 = ui_font_init(LVGL_FONT_PATH(montserratMedium.ttf), 110);
    if (!fs_montserratmedium_16) {
    	LV_LOG_ERROR("Failed to init fs_montserratmedium_16");
    	return;
    }
    if (!fs_montserratmedium_25) {
    	LV_LOG_ERROR("Failed to init fs_montserratmedium_25");
    	return;
    }
    if (!fs_montserratmedium_47) {
    	LV_LOG_ERROR("Failed to init fs_montserratmedium_47");
    	return;
    }
    if (!fs_montserratmedium_34) {
    	LV_LOG_ERROR("Failed to init fs_montserratmedium_34");
    	return;
    }
    if (!fs_montserratmedium_22) {
    	LV_LOG_ERROR("Failed to init fs_montserratmedium_22");
    	return;
    }
    if (!fs_montserratmedium_20) {
    	LV_LOG_ERROR("Failed to init fs_montserratmedium_20");
    	return;
    }
    if (!fs_montserratmedium_30) {
    	LV_LOG_ERROR("Failed to init fs_montserratmedium_30");
    	return;
    }
    if (!fs_montserratmedium_24) {
    	LV_LOG_ERROR("Failed to init fs_montserratmedium_24");
    	return;
    }
    if (!fs_montserratmedium_36) {
    	LV_LOG_ERROR("Failed to init fs_montserratmedium_36");
    	return;
    }
    if (!fs_montserratmedium_26) {
    	LV_LOG_ERROR("Failed to init fs_montserratmedium_26");
    	return;
    }
    if (!fs_montserratmedium_110) {
    	LV_LOG_ERROR("Failed to init fs_montserratmedium_110");
    	return;
    }

    // auto delete screen
    ui_manager_init(&ui_manager, false);

    screen_01_logo_create(&ui_manager);
    lv_scr_load(screen_01_logo_get(&ui_manager)->obj);

    // custom code
    custom_init();
}
