/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by UIBuilder
 * UIBuilder version: v2.1.0
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"


void __attribute__((weak)) screen_05_language_custom_created(void) {
}

void __attribute__((weak)) screen_05_language_container_1_english_custom_clicked(void) {
}

static void screen_05_language_container_1_english_clicked (lv_event_t *e) {
    screen_05_language_container_1_english_custom_clicked();
}

void __attribute__((weak)) screen_05_language_container_2_chinese_custom_clicked(void) {
}

static void screen_05_language_container_2_chinese_clicked (lv_event_t *e) {
    screen_05_language_container_2_chinese_custom_clicked();
}

void __attribute__((weak)) screen_05_language_container_3_french_custom_clicked(void) {
}

static void screen_05_language_container_3_french_clicked (lv_event_t *e) {
    screen_05_language_container_3_french_custom_clicked();
}

void __attribute__((weak)) screen_05_language_container_4_spanish_custom_clicked(void) {
}

static void screen_05_language_container_4_spanish_clicked (lv_event_t *e) {
    screen_05_language_container_4_spanish_custom_clicked();
}

void __attribute__((weak)) screen_05_language_container_5_japan_custom_clicked(void) {
}

static void screen_05_language_container_5_japan_clicked (lv_event_t *e) {
    screen_05_language_container_5_japan_custom_clicked();
}

void __attribute__((weak)) screen_05_language_container_6_german_custom_clicked(void) {
}

static void screen_05_language_container_6_german_clicked (lv_event_t *e) {
    screen_05_language_container_6_german_custom_clicked();
}

void __attribute__((weak)) screen_05_language_container_7_italian_custom_clicked(void) {
}

static void screen_05_language_container_7_italian_clicked (lv_event_t *e) {
    screen_05_language_container_7_italian_custom_clicked();
}

static void screen_05_language_button_1_back_clicked (lv_event_t *e) {
    lv_obj_t *act_scr = lv_scr_act();
    if (!screen_is_loading(act_scr)) {
        // create screen_03_setting
        screen_03_setting_create(&ui_manager);
        // load screen_03_setting
        lv_scr_load_anim(screen_03_setting_get(&ui_manager)->obj, LV_SCR_LOAD_ANIM_NONE, 1, 0, ui_manager.auto_del);
    }
}


void screen_05_language_create(ui_manager_t *ui)
{
    screen_05_language_t *scr = screen_05_language_get(ui);

    if (!ui->auto_del && scr->obj) {
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0xf2f2f2), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->container_1
    scr->container_1 = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->container_1, 0, 83);
    lv_obj_set_size(scr->container_1, 1152, 493);
    lv_obj_set_scrollbar_mode(scr->container_1, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->container_1
    lv_obj_set_style_border_width(scr->container_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->container_1, lv_color_hex(0xf5f5f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->container_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->container_1_english
    scr->container_1_english = lv_obj_create(scr->container_1);
    lv_obj_set_pos(scr->container_1_english, 30, 0);
    lv_obj_set_size(scr->container_1_english, 1092, 62);
    lv_obj_set_scrollbar_mode(scr->container_1_english, LV_SCROLLBAR_MODE_OFF);
    lv_obj_add_flag(scr->container_1_english, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->container_1_english
    lv_obj_set_style_border_width(scr->container_1_english, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_1_english, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_1_english, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_1_english, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_1_english, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_1_english, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->container_1_english
    lv_obj_add_event_cb(scr->container_1_english, screen_05_language_container_1_english_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->label_1_english
    scr->label_1_english = lv_label_create(scr->container_1_english);
    lv_label_set_text(scr->label_1_english, "English");
    lv_label_set_long_mode(scr->label_1_english, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_1_english, 20, 17);
    lv_obj_set_size(scr->label_1_english, 211, 24);

    // Set style of scr->label_1_english
    lv_obj_set_style_text_color(scr->label_1_english, lv_color_hex(0x615f5f), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_1_english, fs_montserratmedium_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_1_english
    scr->image_1_english = lv_img_create(scr->container_1_english);
    lv_img_set_src(scr->image_1_english, LVGL_IMAGE_PATH(set_check.png));
    lv_img_set_pivot(scr->image_1_english, 50, 50);
    lv_img_set_offset_x(scr->image_1_english, 0);
    lv_img_set_offset_y(scr->image_1_english, 0);
    lv_img_set_angle(scr->image_1_english, 0);
    lv_obj_set_pos(scr->image_1_english, 1043, 16);

    // Init scr->container_2_chinese
    scr->container_2_chinese = lv_obj_create(scr->container_1);
    lv_obj_set_pos(scr->container_2_chinese, 30, 83);
    lv_obj_set_size(scr->container_2_chinese, 1092, 62);
    lv_obj_set_scrollbar_mode(scr->container_2_chinese, LV_SCROLLBAR_MODE_OFF);
    lv_obj_add_flag(scr->container_2_chinese, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->container_2_chinese
    lv_obj_set_style_border_width(scr->container_2_chinese, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_2_chinese, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_2_chinese, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_2_chinese, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_2_chinese, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_2_chinese, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->container_2_chinese
    lv_obj_add_event_cb(scr->container_2_chinese, screen_05_language_container_2_chinese_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->label_2_chinese
    scr->label_2_chinese = lv_label_create(scr->container_2_chinese);
    lv_label_set_text(scr->label_2_chinese, "Chinese");
    lv_label_set_long_mode(scr->label_2_chinese, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_2_chinese, 20, 17);
    lv_obj_set_size(scr->label_2_chinese, 211, 24);

    // Set style of scr->label_2_chinese
    lv_obj_set_style_text_color(scr->label_2_chinese, lv_color_hex(0x615f5f), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_2_chinese, fs_montserratmedium_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_2_chinese
    scr->image_2_chinese = lv_img_create(scr->container_2_chinese);
    lv_img_set_src(scr->image_2_chinese, LVGL_IMAGE_PATH(set_check.png));
    lv_img_set_pivot(scr->image_2_chinese, 50, 50);
    lv_img_set_offset_x(scr->image_2_chinese, 0);
    lv_img_set_offset_y(scr->image_2_chinese, 0);
    lv_img_set_angle(scr->image_2_chinese, 0);
    lv_obj_set_pos(scr->image_2_chinese, 1043, 16);
    lv_obj_add_flag(scr->image_2_chinese, LV_OBJ_FLAG_HIDDEN);

    // Init scr->container_3_french
    scr->container_3_french = lv_obj_create(scr->container_1);
    lv_obj_set_pos(scr->container_3_french, 30, 166);
    lv_obj_set_size(scr->container_3_french, 1092, 62);
    lv_obj_set_scrollbar_mode(scr->container_3_french, LV_SCROLLBAR_MODE_OFF);
    lv_obj_add_flag(scr->container_3_french, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->container_3_french
    lv_obj_set_style_border_width(scr->container_3_french, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_3_french, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_3_french, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_3_french, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_3_french, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_3_french, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->container_3_french
    lv_obj_add_event_cb(scr->container_3_french, screen_05_language_container_3_french_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->label_3_french
    scr->label_3_french = lv_label_create(scr->container_3_french);
    lv_label_set_text(scr->label_3_french, "French");
    lv_label_set_long_mode(scr->label_3_french, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_3_french, 20, 17);
    lv_obj_set_size(scr->label_3_french, 211, 24);

    // Set style of scr->label_3_french
    lv_obj_set_style_text_color(scr->label_3_french, lv_color_hex(0x615f5f), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_3_french, fs_montserratmedium_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_3_french
    scr->image_3_french = lv_img_create(scr->container_3_french);
    lv_img_set_src(scr->image_3_french, LVGL_IMAGE_PATH(set_check.png));
    lv_img_set_pivot(scr->image_3_french, 50, 50);
    lv_img_set_offset_x(scr->image_3_french, 0);
    lv_img_set_offset_y(scr->image_3_french, 0);
    lv_img_set_angle(scr->image_3_french, 0);
    lv_obj_set_pos(scr->image_3_french, 1043, 16);
    lv_obj_add_flag(scr->image_3_french, LV_OBJ_FLAG_HIDDEN);

    // Init scr->container_4_spanish
    scr->container_4_spanish = lv_obj_create(scr->container_1);
    lv_obj_set_pos(scr->container_4_spanish, 30, 249);
    lv_obj_set_size(scr->container_4_spanish, 1092, 62);
    lv_obj_set_scrollbar_mode(scr->container_4_spanish, LV_SCROLLBAR_MODE_OFF);
    lv_obj_add_flag(scr->container_4_spanish, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->container_4_spanish
    lv_obj_set_style_border_width(scr->container_4_spanish, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_4_spanish, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_4_spanish, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_4_spanish, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_4_spanish, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_4_spanish, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->container_4_spanish
    lv_obj_add_event_cb(scr->container_4_spanish, screen_05_language_container_4_spanish_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->label_4_spanish
    scr->label_4_spanish = lv_label_create(scr->container_4_spanish);
    lv_label_set_text(scr->label_4_spanish, "Spanish");
    lv_label_set_long_mode(scr->label_4_spanish, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_4_spanish, 20, 17);
    lv_obj_set_size(scr->label_4_spanish, 211, 24);

    // Set style of scr->label_4_spanish
    lv_obj_set_style_text_color(scr->label_4_spanish, lv_color_hex(0x615f5f), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_4_spanish, fs_montserratmedium_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_4_spanish
    scr->image_4_spanish = lv_img_create(scr->container_4_spanish);
    lv_img_set_src(scr->image_4_spanish, LVGL_IMAGE_PATH(set_check.png));
    lv_img_set_pivot(scr->image_4_spanish, 50, 50);
    lv_img_set_offset_x(scr->image_4_spanish, 0);
    lv_img_set_offset_y(scr->image_4_spanish, 0);
    lv_img_set_angle(scr->image_4_spanish, 0);
    lv_obj_set_pos(scr->image_4_spanish, 1043, 16);
    lv_obj_add_flag(scr->image_4_spanish, LV_OBJ_FLAG_HIDDEN);

    // Init scr->container_5_japan
    scr->container_5_japan = lv_obj_create(scr->container_1);
    lv_obj_set_pos(scr->container_5_japan, 30, 332);
    lv_obj_set_size(scr->container_5_japan, 1092, 62);
    lv_obj_set_scrollbar_mode(scr->container_5_japan, LV_SCROLLBAR_MODE_OFF);
    lv_obj_add_flag(scr->container_5_japan, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(scr->container_5_japan, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->container_5_japan
    lv_obj_set_style_border_width(scr->container_5_japan, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_5_japan, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_5_japan, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_5_japan, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_5_japan, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_5_japan, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->container_5_japan
    lv_obj_add_event_cb(scr->container_5_japan, screen_05_language_container_5_japan_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->label_5_japan
    scr->label_5_japan = lv_label_create(scr->container_5_japan);
    lv_label_set_text(scr->label_5_japan, "Japan");
    lv_label_set_long_mode(scr->label_5_japan, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_5_japan, 20, 17);
    lv_obj_set_size(scr->label_5_japan, 211, 24);

    // Set style of scr->label_5_japan
    lv_obj_set_style_text_color(scr->label_5_japan, lv_color_hex(0x615f5f), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_5_japan, fs_montserratmedium_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_5_japan
    scr->image_5_japan = lv_img_create(scr->container_5_japan);
    lv_img_set_src(scr->image_5_japan, LVGL_IMAGE_PATH(set_check.png));
    lv_img_set_pivot(scr->image_5_japan, 50, 50);
    lv_img_set_offset_x(scr->image_5_japan, 0);
    lv_img_set_offset_y(scr->image_5_japan, 0);
    lv_img_set_angle(scr->image_5_japan, 0);
    lv_obj_set_pos(scr->image_5_japan, 1043, 16);
    lv_obj_add_flag(scr->image_5_japan, LV_OBJ_FLAG_HIDDEN);

    // Init scr->container_6_german
    scr->container_6_german = lv_obj_create(scr->container_1);
    lv_obj_set_pos(scr->container_6_german, 30, 332);
    lv_obj_set_size(scr->container_6_german, 1092, 62);
    lv_obj_set_scrollbar_mode(scr->container_6_german, LV_SCROLLBAR_MODE_OFF);
    lv_obj_add_flag(scr->container_6_german, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->container_6_german
    lv_obj_set_style_border_width(scr->container_6_german, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_6_german, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_6_german, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_6_german, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_6_german, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_6_german, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->container_6_german
    lv_obj_add_event_cb(scr->container_6_german, screen_05_language_container_6_german_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->label_6_german
    scr->label_6_german = lv_label_create(scr->container_6_german);
    lv_label_set_text(scr->label_6_german, "German");
    lv_label_set_long_mode(scr->label_6_german, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_6_german, 20, 17);
    lv_obj_set_size(scr->label_6_german, 211, 24);

    // Set style of scr->label_6_german
    lv_obj_set_style_text_color(scr->label_6_german, lv_color_hex(0x615f5f), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_6_german, fs_montserratmedium_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_6_german
    scr->image_6_german = lv_img_create(scr->container_6_german);
    lv_img_set_src(scr->image_6_german, LVGL_IMAGE_PATH(set_check.png));
    lv_img_set_pivot(scr->image_6_german, 50, 50);
    lv_img_set_offset_x(scr->image_6_german, 0);
    lv_img_set_offset_y(scr->image_6_german, 0);
    lv_img_set_angle(scr->image_6_german, 0);
    lv_obj_set_pos(scr->image_6_german, 1043, 16);
    lv_obj_add_flag(scr->image_6_german, LV_OBJ_FLAG_HIDDEN);

    // Init scr->container_7_italian
    scr->container_7_italian = lv_obj_create(scr->container_1);
    lv_obj_set_pos(scr->container_7_italian, 30, 415);
    lv_obj_set_size(scr->container_7_italian, 1092, 62);
    lv_obj_set_scrollbar_mode(scr->container_7_italian, LV_SCROLLBAR_MODE_OFF);
    lv_obj_add_flag(scr->container_7_italian, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->container_7_italian
    lv_obj_set_style_border_width(scr->container_7_italian, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_7_italian, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_7_italian, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_7_italian, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_7_italian, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_7_italian, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->container_7_italian
    lv_obj_add_event_cb(scr->container_7_italian, screen_05_language_container_7_italian_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->label_7_italian
    scr->label_7_italian = lv_label_create(scr->container_7_italian);
    lv_label_set_text(scr->label_7_italian, "Italian");
    lv_label_set_long_mode(scr->label_7_italian, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_7_italian, 20, 17);
    lv_obj_set_size(scr->label_7_italian, 211, 24);

    // Set style of scr->label_7_italian
    lv_obj_set_style_text_color(scr->label_7_italian, lv_color_hex(0x615f5f), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_7_italian, fs_montserratmedium_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_7_italian
    scr->image_7_italian = lv_img_create(scr->container_7_italian);
    lv_img_set_src(scr->image_7_italian, LVGL_IMAGE_PATH(set_check.png));
    lv_img_set_pivot(scr->image_7_italian, 50, 50);
    lv_img_set_offset_x(scr->image_7_italian, 0);
    lv_img_set_offset_y(scr->image_7_italian, 0);
    lv_img_set_angle(scr->image_7_italian, 0);
    lv_obj_set_pos(scr->image_7_italian, 1043, 16);
    lv_obj_add_flag(scr->image_7_italian, LV_OBJ_FLAG_HIDDEN);

    // Init scr->button_1_back
    scr->button_1_back = lv_btn_create(scr->obj);
    lv_obj_t *button_1_back_label = lv_label_create(scr->button_1_back);
    lv_label_set_text(button_1_back_label, "");
    lv_obj_align(button_1_back_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->button_1_back, 5, 20);
    lv_obj_set_size(scr->button_1_back, 80, 40);

    // Set style of scr->button_1_back
    lv_obj_set_style_shadow_width(scr->button_1_back, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->button_1_back, LVGL_IMAGE_PATH(back.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->button_1_back, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->button_1_back, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->button_1_back
    lv_obj_add_event_cb(scr->button_1_back, screen_05_language_button_1_back_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->label_0_language
    scr->label_0_language = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_0_language, "Language");
    lv_label_set_long_mode(scr->label_0_language, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_0_language, 326, 15);
    lv_obj_set_size(scr->label_0_language, 500, 50);

    // Set style of scr->label_0_language
    lv_obj_set_style_text_color(scr->label_0_language, lv_color_hex(0xc4330f), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_0_language, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_0_language, fs_montserratmedium_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    screen_05_language_custom_created();
}


