/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by UIBuilder
 * UIBuilder version: v2.1.0
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"


void __attribute__((weak)) screen_12_idle_custom_loaded(void) {
}
void __attribute__((weak)) screen_12_idle_custom_unload_start(void) {
}

static void screen_12_idle_unload_start (lv_event_t *e) {
    screen_12_idle_custom_unload_start();
}

static void screen_12_idle_clicked (lv_event_t *e) {
    lv_obj_t *act_scr = lv_scr_act();
    if (!screen_is_loading(act_scr)) {
        // create screen_02_main
        screen_02_main_create(&ui_manager);
        // load screen_02_main
        lv_scr_load_anim(screen_02_main_get(&ui_manager)->obj, LV_SCR_LOAD_ANIM_NONE, 1, 0, ui_manager.auto_del);
    }
}

static void screen_12_idle_loaded (lv_event_t *e) {
    screen_12_idle_custom_loaded();
}


void screen_12_idle_create(ui_manager_t *ui)
{
    screen_12_idle_t *scr = screen_12_idle_get(ui);

    if (!ui->auto_del && scr->obj) {
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->obj
    lv_obj_add_event_cb(scr->obj, screen_12_idle_unload_start, LV_EVENT_SCREEN_UNLOAD_START, NULL);
    lv_obj_add_event_cb(scr->obj, screen_12_idle_clicked, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(scr->obj, screen_12_idle_loaded, LV_EVENT_SCREEN_LOADED, NULL);


}


