/*
 * Copyright (C) 2025 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v2.0.1
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"
#include "aic_lang.h"
#include "lv_aic_player.h"

static void bread_bt_menu_back_btn_clicked (lv_event_t *e) {
    lv_obj_t *act_scr = lv_scr_act();
    if (!screen_is_loading(act_scr)) {
        // create bread_main_menu
        bread_main_menu_create(&ui_manager);
        // load bread_main_menu
        lv_scr_load_anim(bread_main_menu_get(&ui_manager)->obj, LV_SCR_LOAD_ANIM_NONE, 0, 0, ui_manager.auto_del);
    }
}

static void bread_bt_menu_settings_label_clicked (lv_event_t *e) {
    lv_obj_t *act_scr = lv_scr_act();
    if (!screen_is_loading(act_scr)) {
        // create bread_setting_menu
        bread_setting_menu_create(&ui_manager);
        // load bread_setting_menu
        lv_scr_load_anim(bread_setting_menu_get(&ui_manager)->obj, LV_SCR_LOAD_ANIM_NONE, 0, 0, ui_manager.auto_del);
    }
}

static void bread_bt_menu_back_img_clicked (lv_event_t *e) {
    lv_obj_t *act_scr = lv_scr_act();
    if (!screen_is_loading(act_scr)) {
        // create bread_main_menu
        bread_main_menu_create(&ui_manager);
        // load bread_main_menu
        lv_scr_load_anim(bread_main_menu_get(&ui_manager)->obj, LV_SCR_LOAD_ANIM_NONE, 0, 0, ui_manager.auto_del);
    }
}

static void bread_bt_menu_settings_img_clicked (lv_event_t *e) {
    lv_obj_t *act_scr = lv_scr_act();
    if (!screen_is_loading(act_scr)) {
        // create bread_setting_menu
        bread_setting_menu_create(&ui_manager);
        // load bread_setting_menu
        lv_scr_load_anim(bread_setting_menu_get(&ui_manager)->obj, LV_SCR_LOAD_ANIM_NONE, 0, 0, ui_manager.auto_del);
    }
}


void bread_bt_menu_create(ui_manager_t *ui)
{
    bread_bt_menu_t *scr = bread_bt_menu_get(ui);

    if (!ui->auto_del && scr->obj) {
        bread_bt_menu_update_current_language();
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0xfcfcfc), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->bt_menu_bg
    scr->bt_menu_bg = lv_img_create(scr->obj);
    lv_img_set_src(scr->bt_menu_bg, LVGL_IMAGE_PATH(bread_bg.png));
    lv_img_set_pivot(scr->bt_menu_bg, 50, 50);
    lv_img_set_angle(scr->bt_menu_bg, 0);
    lv_obj_set_style_img_opa(scr->bt_menu_bg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->bt_menu_bg, 0, 0);

    // Init scr->back_btn
    scr->back_btn = lv_label_create(scr->obj);
    lv_label_set_text(scr->back_btn, aic_get_translation(return1));
    lv_label_set_long_mode(scr->back_btn, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->back_btn, 820, 500);
    lv_obj_set_size(scr->back_btn, 155, 60);
    lv_obj_add_flag(scr->back_btn, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->back_btn
    lv_obj_set_style_bg_img_src(scr->back_btn, LVGL_IMAGE_PATH(bread_settings_menu/Sketchpad2.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->back_btn, aic_get_multi_lang_font(22), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->back_btn, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->back_btn, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->back_btn, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->back_btn
    lv_obj_add_event_cb(scr->back_btn, bread_bt_menu_back_btn_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->power_label
    scr->power_label = lv_label_create(scr->obj);
    lv_label_set_text(scr->power_label, aic_get_translation(power));
    lv_label_set_long_mode(scr->power_label, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->power_label, 770, 55);
    lv_obj_set_size(scr->power_label, 100, 20);

    // Set style of scr->power_label
    lv_obj_set_style_text_font(scr->power_label, aic_get_multi_lang_font(16), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->power_label, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->power_label, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->bt_label
    scr->bt_label = lv_label_create(scr->obj);
    lv_label_set_text(scr->bt_label, aic_get_translation(bluetooth));
    lv_label_set_long_mode(scr->bt_label, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->bt_label, 845, 55);
    lv_obj_set_size(scr->bt_label, 100, 20);

    // Set style of scr->bt_label
    lv_obj_set_style_text_font(scr->bt_label, aic_get_multi_lang_font(16), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->bt_label, lv_color_hex(0xee9391), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->bt_label, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->settings_label
    scr->settings_label = lv_label_create(scr->obj);
    lv_label_set_text(scr->settings_label, aic_get_translation(settings));
    lv_label_set_long_mode(scr->settings_label, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->settings_label, 920, 55);
    lv_obj_set_size(scr->settings_label, 100, 20);
    lv_obj_add_flag(scr->settings_label, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->settings_label
    lv_obj_set_style_text_font(scr->settings_label, aic_get_multi_lang_font(16), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->settings_label, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->settings_label, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->settings_label
    lv_obj_add_event_cb(scr->settings_label, bread_bt_menu_settings_label_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->back_img
    scr->back_img = lv_img_create(scr->obj);
    lv_img_set_src(scr->back_img, LVGL_IMAGE_PATH(bread_time_menu/return.png));
    lv_img_set_pivot(scr->back_img, 50, 50);
    lv_img_set_angle(scr->back_img, 0);
    lv_obj_set_style_img_opa(scr->back_img, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->back_img, 840, 510);
    lv_obj_add_flag(scr->back_img, LV_OBJ_FLAG_CLICKABLE);

    // Set event handler of scr->back_img
    lv_obj_add_event_cb(scr->back_img, bread_bt_menu_back_img_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->QRcode
    scr->QRcode = lv_img_create(scr->obj);
    lv_img_set_src(scr->QRcode, LVGL_IMAGE_PATH(bread_bt_menu/QRcode.png));
    lv_img_set_pivot(scr->QRcode, 50, 50);
    lv_img_set_angle(scr->QRcode, 0);
    lv_obj_set_style_img_opa(scr->QRcode, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->QRcode, 312, 103);

    // Init scr->settings_img
    scr->settings_img = lv_img_create(scr->obj);
    lv_img_set_src(scr->settings_img, LVGL_IMAGE_PATH(bread_bt_menu/settings.png));
    lv_img_set_pivot(scr->settings_img, 50, 50);
    lv_img_set_angle(scr->settings_img, 0);
    lv_obj_set_style_img_opa(scr->settings_img, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->settings_img, 953, 20);
    lv_obj_add_flag(scr->settings_img, LV_OBJ_FLAG_CLICKABLE);

    // Set event handler of scr->settings_img
    lv_obj_add_event_cb(scr->settings_img, bread_bt_menu_settings_img_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->bt_img
    scr->bt_img = lv_img_create(scr->obj);
    lv_img_set_src(scr->bt_img, LVGL_IMAGE_PATH(bread_bt_menu/bt_selected.png));
    lv_img_set_pivot(scr->bt_img, 50, 50);
    lv_img_set_angle(scr->bt_img, 0);
    lv_obj_set_style_img_opa(scr->bt_img, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->bt_img, 880, 18);

    // Init scr->power_img
    scr->power_img = lv_img_create(scr->obj);
    lv_img_set_src(scr->power_img, LVGL_IMAGE_PATH(bread_machine_main_menu/Open.png));
    lv_img_set_pivot(scr->power_img, 50, 50);
    lv_img_set_angle(scr->power_img, 0);
    lv_obj_set_style_img_opa(scr->power_img, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->power_img, 798, 16);


}

void bread_bt_menu_update_language(lang_type_t lang)
{
    aic_set_language(lang);
    bread_bt_menu_update_current_language();
}

void bread_bt_menu_update_current_language()
{
    bread_bt_menu_t *scr = bread_bt_menu_get(&ui_manager);
    lv_obj_set_style_text_font(scr->back_btn, aic_get_multi_lang_font(22), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_label_set_text(scr->back_btn, aic_get_translation(return1));

    lv_obj_set_style_text_font(scr->power_label, aic_get_multi_lang_font(16), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_label_set_text(scr->power_label, aic_get_translation(power));

    lv_obj_set_style_text_font(scr->bt_label, aic_get_multi_lang_font(16), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_label_set_text(scr->bt_label, aic_get_translation(bluetooth));

    lv_obj_set_style_text_font(scr->settings_label, aic_get_multi_lang_font(16), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_label_set_text(scr->settings_label, aic_get_translation(settings));

}

