/*
 * Copyright (C) 2025 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v2.0.1
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"
#include "aic_lang.h"
#include "lv_aic_player.h"

void __attribute__((weak)) bread_setting_menu_custom_created(void) {
}

static void bread_setting_menu_back_btn_clicked (lv_event_t *e) {
    lv_obj_t *act_scr = lv_scr_act();
    if (!screen_is_loading(act_scr)) {
        // create bread_main_menu
        bread_main_menu_create(&ui_manager);
        // load bread_main_menu
        lv_scr_load_anim(bread_main_menu_get(&ui_manager)->obj, LV_SCR_LOAD_ANIM_NONE, 0, 0, ui_manager.auto_del);
    }
}

static void bread_setting_menu_bt_label_clicked (lv_event_t *e) {
    lv_obj_t *act_scr = lv_scr_act();
    if (!screen_is_loading(act_scr)) {
        // create bread_bt_menu
        bread_bt_menu_create(&ui_manager);
        // load bread_bt_menu
        lv_scr_load_anim(bread_bt_menu_get(&ui_manager)->obj, LV_SCR_LOAD_ANIM_NONE, 0, 0, ui_manager.auto_del);
    }
}

void __attribute__((weak)) bread_setting_menu_eng_switch_custom_value_changed(void) {
}
void __attribute__((weak)) bread_setting_menu_chn_switch_custom_value_changed(void) {
}
void __attribute__((weak)) bread_setting_menu_jpn_switch_custom_value_changed(void) {
}

static void bread_setting_menu_lan_switch_value_changed (lv_event_t *e) {
    lv_obj_t *bread_setting_menu_lan_switch = bread_setting_menu_get(&ui_manager)->lan_switch;
    uint32_t id = lv_dropdown_get_selected(bread_setting_menu_lan_switch);
    switch(id) {
    case 0:
    {
        bread_setting_menu_eng_switch_custom_value_changed();
        break;
    }
    case 1:
    {
        bread_setting_menu_chn_switch_custom_value_changed();
        break;
    }
    case 2:
    {
        bread_setting_menu_jpn_switch_custom_value_changed();
        break;
    }
    default:
        break;
    }
}

static void bread_setting_menu_setting2_clicked (lv_event_t *e) {
    lv_obj_t *bread_setting_menu_QRcode = bread_setting_menu_get(&ui_manager)->QRcode;
    lv_obj_clear_flag(bread_setting_menu_QRcode, LV_OBJ_FLAG_HIDDEN);
}

static void bread_setting_menu_setting3_clicked (lv_event_t *e) {
    lv_obj_t *bread_setting_menu_QRcode = bread_setting_menu_get(&ui_manager)->QRcode;
    lv_obj_clear_flag(bread_setting_menu_QRcode, LV_OBJ_FLAG_HIDDEN);
}

static void bread_setting_menu_back_img_clicked (lv_event_t *e) {
    lv_obj_t *act_scr = lv_scr_act();
    if (!screen_is_loading(act_scr)) {
        // create bread_main_menu
        bread_main_menu_create(&ui_manager);
        // load bread_main_menu
        lv_scr_load_anim(bread_main_menu_get(&ui_manager)->obj, LV_SCR_LOAD_ANIM_NONE, 0, 0, ui_manager.auto_del);
    }
}

static void bread_setting_menu_bt_img_clicked (lv_event_t *e) {
    lv_obj_t *act_scr = lv_scr_act();
    if (!screen_is_loading(act_scr)) {
        // create bread_bt_menu
        bread_bt_menu_create(&ui_manager);
        // load bread_bt_menu
        lv_scr_load_anim(bread_bt_menu_get(&ui_manager)->obj, LV_SCR_LOAD_ANIM_NONE, 0, 0, ui_manager.auto_del);
    }
}

static void bread_setting_menu_QRcode_clicked (lv_event_t *e) {
    lv_obj_t *bread_setting_menu_QRcode = bread_setting_menu_get(&ui_manager)->QRcode;
    lv_obj_add_flag(bread_setting_menu_QRcode, LV_OBJ_FLAG_HIDDEN);
}


void bread_setting_menu_create(ui_manager_t *ui)
{
    bread_setting_menu_t *scr = bread_setting_menu_get(ui);

    if (!ui->auto_del && scr->obj) {
        bread_setting_menu_update_current_language();
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0xfcfcfc), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->bg
    scr->bg = lv_img_create(scr->obj);
    lv_img_set_src(scr->bg, LVGL_IMAGE_PATH(bread_bg.png));
    lv_img_set_pivot(scr->bg, 50, 50);
    lv_img_set_angle(scr->bg, 0);
    lv_obj_set_style_img_opa(scr->bg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->bg, 0, 0);

    // Init scr->back_btn
    scr->back_btn = lv_label_create(scr->obj);
    lv_label_set_text(scr->back_btn, aic_get_translation(return1));
    lv_label_set_long_mode(scr->back_btn, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->back_btn, 820, 500);
    lv_obj_set_size(scr->back_btn, 155, 60);
    lv_obj_add_flag(scr->back_btn, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->back_btn
    lv_obj_set_style_bg_img_src(scr->back_btn, LVGL_IMAGE_PATH(bread_settings_menu/Sketchpad2.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->back_btn, aic_get_multi_lang_font(22), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->back_btn, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->back_btn, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->back_btn, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->back_btn
    lv_obj_add_event_cb(scr->back_btn, bread_setting_menu_back_btn_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->power_label
    scr->power_label = lv_label_create(scr->obj);
    lv_label_set_text(scr->power_label, aic_get_translation(power));
    lv_label_set_long_mode(scr->power_label, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->power_label, 770, 55);
    lv_obj_set_size(scr->power_label, 100, 20);

    // Set style of scr->power_label
    lv_obj_set_style_text_font(scr->power_label, aic_get_multi_lang_font(16), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->power_label, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->power_label, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->bt_label
    scr->bt_label = lv_label_create(scr->obj);
    lv_label_set_text(scr->bt_label, aic_get_translation(bluetooth));
    lv_label_set_long_mode(scr->bt_label, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->bt_label, 845, 55);
    lv_obj_set_size(scr->bt_label, 100, 20);
    lv_obj_add_flag(scr->bt_label, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->bt_label
    lv_obj_set_style_text_font(scr->bt_label, aic_get_multi_lang_font(16), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->bt_label, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->bt_label, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->bt_label
    lv_obj_add_event_cb(scr->bt_label, bread_setting_menu_bt_label_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->settings_label
    scr->settings_label = lv_label_create(scr->obj);
    lv_label_set_text(scr->settings_label, aic_get_translation(settings));
    lv_label_set_long_mode(scr->settings_label, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->settings_label, 920, 55);
    lv_obj_set_size(scr->settings_label, 100, 20);

    // Set style of scr->settings_label
    lv_obj_set_style_text_font(scr->settings_label, aic_get_multi_lang_font(16), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->settings_label, lv_color_hex(0xee9391), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->settings_label, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->main_container
    scr->main_container = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->main_container, 150, 91);
    lv_obj_set_size(scr->main_container, 724, 418);
    lv_obj_set_scrollbar_mode(scr->main_container, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->main_container
    lv_obj_set_style_bg_color(scr->main_container, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->main_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->main_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->main_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->main_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->main_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->main_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->main_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->setting1_container
    scr->setting1_container = lv_obj_create(scr->main_container);
    lv_obj_set_pos(scr->setting1_container, 64, 35);
    lv_obj_set_size(scr->setting1_container, 608, 72);
    lv_obj_set_scrollbar_mode(scr->setting1_container, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->setting1_container
    lv_obj_set_style_bg_color(scr->setting1_container, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->setting1_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->setting1_container, LVGL_IMAGE_PATH(bread_settings_menu/opbg.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->setting1_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->setting1_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->setting1_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->setting1_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->setting1_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->setting1_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->setting1_label
    scr->setting1_label = lv_label_create(scr->setting1_container);
    lv_label_set_text(scr->setting1_label, aic_get_translation(language));
    lv_label_set_long_mode(scr->setting1_label, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->setting1_label, 25, 16);
    lv_obj_set_size(scr->setting1_label, 100, 32);

    // Set style of scr->setting1_label
    lv_obj_set_style_text_font(scr->setting1_label, aic_get_multi_lang_font(22), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->setting1_label, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->lan_switch
    scr->lan_switch = lv_dropdown_create(scr->setting1_container);
    lv_obj_set_style_max_height(lv_dropdown_get_list(scr->lan_switch), 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    int lan_switch_options_len = strlen(aic_get_translation(english_lan)) + strlen(aic_get_translation(chinese_lan)) + strlen(aic_get_translation(japanese_lan)) + 3;
    char *lan_switch_options = lv_mem_alloc(sizeof(char *) * lan_switch_options_len);
    memset(lan_switch_options, 0, lan_switch_options_len);
    strcat(lan_switch_options, aic_get_translation(english_lan));
    strcat(lan_switch_options, "\n");
    strcat(lan_switch_options, aic_get_translation(chinese_lan));
    strcat(lan_switch_options, "\n");
    strcat(lan_switch_options, aic_get_translation(japanese_lan));
    lv_dropdown_set_options(scr->lan_switch, lan_switch_options);
    lv_mem_free(lan_switch_options);

    lv_obj_set_pos(scr->lan_switch, 451, 12);
    lv_obj_set_size(scr->lan_switch, 130, 47);

    // Set style of scr->lan_switch
    lv_obj_set_style_bg_color(scr->lan_switch, lv_color_hex(0x592f17), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->lan_switch, aic_get_multi_lang_font(16), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->lan_switch, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(lv_dropdown_get_list(scr->lan_switch), lv_color_hex(0x592f17), LV_PART_SELECTED | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(lv_dropdown_get_list(scr->lan_switch), lv_color_hex(0x592f17), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(lv_dropdown_get_list(scr->lan_switch), aic_get_multi_lang_font(16), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(lv_dropdown_get_list(scr->lan_switch), lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->lan_switch, LV_FONT_DEFAULT, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    // Set event handler of scr->lan_switch
    lv_obj_add_event_cb(scr->lan_switch, bread_setting_menu_lan_switch_value_changed, LV_EVENT_VALUE_CHANGED, NULL);

    // Init scr->setting2_container
    scr->setting2_container = lv_obj_create(scr->main_container);
    lv_obj_set_pos(scr->setting2_container, 64, 140);
    lv_obj_set_size(scr->setting2_container, 608, 72);
    lv_obj_set_scrollbar_mode(scr->setting2_container, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->setting2_container
    lv_obj_set_style_bg_color(scr->setting2_container, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->setting2_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->setting2_container, LVGL_IMAGE_PATH(bread_settings_menu/opbg.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->setting2_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->setting2_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->setting2_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->setting2_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->setting2_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->setting2_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->setting2
    scr->setting2 = lv_img_create(scr->setting2_container);
    lv_img_set_src(scr->setting2, LVGL_IMAGE_PATH(bread_settings_menu/Usage.png));
    lv_img_set_pivot(scr->setting2, 50, 50);
    lv_img_set_angle(scr->setting2, 0);
    lv_obj_set_style_img_opa(scr->setting2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->setting2, 496, 9);
    lv_obj_add_flag(scr->setting2, LV_OBJ_FLAG_CLICKABLE);

    // Set event handler of scr->setting2
    lv_obj_add_event_cb(scr->setting2, bread_setting_menu_setting2_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->setting2_label
    scr->setting2_label = lv_label_create(scr->setting2_container);
    lv_label_set_text(scr->setting2_label, aic_get_translation(usage));
    lv_label_set_long_mode(scr->setting2_label, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->setting2_label, 25, 16);
    lv_obj_set_size(scr->setting2_label, 100, 32);

    // Set style of scr->setting2_label
    lv_obj_set_style_text_font(scr->setting2_label, aic_get_multi_lang_font(22), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->setting2_label, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->setting3_container
    scr->setting3_container = lv_obj_create(scr->main_container);
    lv_obj_set_pos(scr->setting3_container, 67, 245);
    lv_obj_set_size(scr->setting3_container, 608, 72);
    lv_obj_set_scrollbar_mode(scr->setting3_container, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->setting3_container
    lv_obj_set_style_bg_color(scr->setting3_container, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->setting3_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->setting3_container, LVGL_IMAGE_PATH(bread_settings_menu/opbg.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->setting3_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->setting3_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->setting3_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->setting3_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->setting3_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->setting3_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->setting3
    scr->setting3 = lv_img_create(scr->setting3_container);
    lv_img_set_src(scr->setting3, LVGL_IMAGE_PATH(bread_settings_menu/Video_playback.png));
    lv_img_set_pivot(scr->setting3, 50, 50);
    lv_img_set_angle(scr->setting3, 0);
    lv_obj_set_style_img_opa(scr->setting3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->setting3, 490, 10);
    lv_obj_add_flag(scr->setting3, LV_OBJ_FLAG_CLICKABLE);

    // Set event handler of scr->setting3
    lv_obj_add_event_cb(scr->setting3, bread_setting_menu_setting3_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->setting3_label
    scr->setting3_label = lv_label_create(scr->setting3_container);
    lv_label_set_text(scr->setting3_label, aic_get_translation(introduction));
    lv_label_set_long_mode(scr->setting3_label, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->setting3_label, 25, 16);
    lv_obj_set_size(scr->setting3_label, 100, 32);

    // Set style of scr->setting3_label
    lv_obj_set_style_text_font(scr->setting3_label, aic_get_multi_lang_font(22), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->setting3_label, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->setting4_container
    scr->setting4_container = lv_obj_create(scr->main_container);
    lv_obj_set_pos(scr->setting4_container, 65, 350);
    lv_obj_set_size(scr->setting4_container, 608, 72);
    lv_obj_set_scrollbar_mode(scr->setting4_container, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->setting4_container
    lv_obj_set_style_bg_color(scr->setting4_container, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->setting4_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->setting4_container, LVGL_IMAGE_PATH(bread_settings_menu/opbg.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->setting4_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->setting4_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->setting4_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->setting4_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->setting4_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->setting4_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->setting4
    scr->setting4 = lv_label_create(scr->setting4_container);
    lv_label_set_text(scr->setting4, aic_get_translation(version_num));
    lv_label_set_long_mode(scr->setting4, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->setting4, 466, 13);
    lv_obj_set_size(scr->setting4, 100, 32);

    // Set style of scr->setting4
    lv_obj_set_style_text_font(scr->setting4, aic_get_multi_lang_font(20), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->setting4, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->setting4, 6, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->setting4_label
    scr->setting4_label = lv_label_create(scr->setting4_container);
    lv_label_set_text(scr->setting4_label, aic_get_translation(version));
    lv_label_set_long_mode(scr->setting4_label, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->setting4_label, 25, 16);
    lv_obj_set_size(scr->setting4_label, 100, 32);

    // Set style of scr->setting4_label
    lv_obj_set_style_text_font(scr->setting4_label, aic_get_multi_lang_font(22), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->setting4_label, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->back_img
    scr->back_img = lv_img_create(scr->obj);
    lv_img_set_src(scr->back_img, LVGL_IMAGE_PATH(bread_time_menu/return.png));
    lv_img_set_pivot(scr->back_img, 50, 50);
    lv_img_set_angle(scr->back_img, 0);
    lv_obj_set_style_img_opa(scr->back_img, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->back_img, 840, 510);
    lv_obj_add_flag(scr->back_img, LV_OBJ_FLAG_CLICKABLE);

    // Set event handler of scr->back_img
    lv_obj_add_event_cb(scr->back_img, bread_setting_menu_back_img_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->settings_img
    scr->settings_img = lv_img_create(scr->obj);
    lv_img_set_src(scr->settings_img, LVGL_IMAGE_PATH(bread_settings_menu/Set_up_selected.png));
    lv_img_set_pivot(scr->settings_img, 50, 50);
    lv_img_set_angle(scr->settings_img, 0);
    lv_obj_set_style_img_opa(scr->settings_img, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->settings_img, 953, 20);

    // Init scr->bt_img
    scr->bt_img = lv_img_create(scr->obj);
    lv_img_set_src(scr->bt_img, LVGL_IMAGE_PATH(bread_time_menu/Bluetooth.png));
    lv_img_set_pivot(scr->bt_img, 50, 50);
    lv_img_set_angle(scr->bt_img, 0);
    lv_obj_set_style_img_opa(scr->bt_img, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->bt_img, 880, 18);
    lv_obj_add_flag(scr->bt_img, LV_OBJ_FLAG_CLICKABLE);

    // Set event handler of scr->bt_img
    lv_obj_add_event_cb(scr->bt_img, bread_setting_menu_bt_img_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->power_img
    scr->power_img = lv_img_create(scr->obj);
    lv_img_set_src(scr->power_img, LVGL_IMAGE_PATH(bread_settings_menu/Open.png));
    lv_img_set_pivot(scr->power_img, 50, 50);
    lv_img_set_angle(scr->power_img, 0);
    lv_obj_set_style_img_opa(scr->power_img, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->power_img, 798, 16);

    // Init scr->QRcode
    scr->QRcode = lv_img_create(scr->obj);
    lv_img_set_src(scr->QRcode, LVGL_IMAGE_PATH(bread_bt_menu/QRcode.png));
    lv_img_set_pivot(scr->QRcode, 50, 50);
    lv_img_set_angle(scr->QRcode, 0);
    lv_obj_set_style_img_opa(scr->QRcode, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->QRcode, 312, 103);
    lv_obj_add_flag(scr->QRcode, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(scr->QRcode, LV_OBJ_FLAG_CLICKABLE);

    // Set event handler of scr->QRcode
    lv_obj_add_event_cb(scr->QRcode, bread_setting_menu_QRcode_clicked, LV_EVENT_CLICKED, NULL);

    bread_setting_menu_custom_created();
}

void bread_setting_menu_update_language(lang_type_t lang)
{
    aic_set_language(lang);
    bread_setting_menu_update_current_language();
}

void bread_setting_menu_update_current_language()
{
    bread_setting_menu_t *scr = bread_setting_menu_get(&ui_manager);
    lv_obj_set_style_text_font(scr->back_btn, aic_get_multi_lang_font(22), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_label_set_text(scr->back_btn, aic_get_translation(return1));

    lv_obj_set_style_text_font(scr->power_label, aic_get_multi_lang_font(16), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_label_set_text(scr->power_label, aic_get_translation(power));

    lv_obj_set_style_text_font(scr->bt_label, aic_get_multi_lang_font(16), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_label_set_text(scr->bt_label, aic_get_translation(bluetooth));

    lv_obj_set_style_text_font(scr->settings_label, aic_get_multi_lang_font(16), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_label_set_text(scr->settings_label, aic_get_translation(settings));

    lv_obj_set_style_text_font(scr->setting1_label, aic_get_multi_lang_font(22), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_label_set_text(scr->setting1_label, aic_get_translation(language));

    lv_obj_set_style_text_font(scr->lan_switch, aic_get_multi_lang_font(16), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(lv_dropdown_get_list(scr->lan_switch), aic_get_multi_lang_font(16), LV_PART_MAIN | LV_STATE_DEFAULT);
    int lan_switch_options_len = strlen(aic_get_translation(english_lan)) + strlen(aic_get_translation(chinese_lan)) + strlen(aic_get_translation(japanese_lan)) + 3;
    char *lan_switch_options = lv_mem_alloc(sizeof(char *) * lan_switch_options_len);
    memset(lan_switch_options, 0, lan_switch_options_len);
    strcat(lan_switch_options, aic_get_translation(english_lan));
    strcat(lan_switch_options, "\n");
    strcat(lan_switch_options, aic_get_translation(chinese_lan));
    strcat(lan_switch_options, "\n");
    strcat(lan_switch_options, aic_get_translation(japanese_lan));
    lv_dropdown_set_options(scr->lan_switch, lan_switch_options);
    lv_mem_free(lan_switch_options);

    lv_obj_set_style_text_font(scr->setting2_label, aic_get_multi_lang_font(22), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_label_set_text(scr->setting2_label, aic_get_translation(usage));

    lv_obj_set_style_text_font(scr->setting3_label, aic_get_multi_lang_font(22), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_label_set_text(scr->setting3_label, aic_get_translation(introduction));

    lv_obj_set_style_text_font(scr->setting4, aic_get_multi_lang_font(20), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_label_set_text(scr->setting4, aic_get_translation(version_num));

    lv_obj_set_style_text_font(scr->setting4_label, aic_get_multi_lang_font(22), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_label_set_text(scr->setting4_label, aic_get_translation(version));

}

