/*
 * Copyright (C) 2025 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v2.0.1
 */

#include "aic_lang.h"
#include "custom/custom.h"

static lang_type_t current_lang = AIC_LANG_EN;

const aic_language_t languages[] = {
    {"en", DROIDSANSFALLBACK_TTF, false},
    {"jp", DROIDSANSFALLBACK_TTF, false},
    {"zh", DROIDSANSFALLBACK_TTF, false}
};

const char *font_names[] = {
    "DroidSansFallback.ttf"
};

const char *translations[20][3] = {
    {"Appointment", "予約", "预约"},
    {"Cancel", "キャンセル", "取消"},
    {"Bluetooth", "ブルートゥース", "蓝牙"},
    {"中文", "中文", "中文"},
    {"Countdown", "カウントダウン", "倒计时"},
    {"Defrost", "解凍", "解冻"},
    {"ENGLISH", "ENGLISH", "ENGLISH"},
    {"Heat", "かねつ", "加热"},
    {"Heating", "加熱中", "加热中"},
    {"Introduction", "イントロダクション", "介绍"},
    {"日本語", "日本語", "日本語"},
    {"Language", "言語", "语言"},
    {"Power", "電源", "电源"},
    {"Return", "戻る", "返回"},
    {"Settings", "設定", "设置"},
    {"Start", "起動", "启动"},
    {"Time", "時間", "时间"},
    {"Usage", "使い方", "使用方法"},
    {"Version", "バージョン", "版本"},
    {"V 1.0.0", "V 1.0.0", "V 1.0.0"}
};

void aic_set_language(lang_type_t lang)
{
    current_lang  = lang;
}

const char *aic_get_translation(key_id_t key)
{
    return translations[key][current_lang];
}

const lv_font_t *aic_init_lang_font(int font_id, int font_size)
{
    const lv_font_t *font = aic_font_list_find(font_id, font_size);
    if (font)
        return font;

    char font_path[256] = {0};
    snprintf(font_path, sizeof(font_path) - 1, "%s/font/%s", LVGL_STORAGE_PATH, font_names[font_id]);

    font = ui_font_init(font_path, font_size);
    if (!font) {
        LV_LOG_ERROR("Failed to init font");
        return NULL;
    }

    aic_font_list_add(font_id, font_size, font);
    return font;
}

const lv_font_t *aic_get_lang_font(int font_id, int font_size, bool c_flag)
{
    if (c_flag)
        return aic_get_c_font(font_id, font_size);
    else
        return aic_init_lang_font(font_id, font_size);
}

const lv_font_t *aic_get_multi_lang_font(int font_size)
{
    const aic_language_t *lang = get_current_lang();
    return aic_get_lang_font(lang->font_id, font_size, lang->c_flag);
}

const lv_font_t *aic_get_c_font(int font_id, int font_size)
{
    switch (font_id) {

        default:
            return NULL;
    }
}

const aic_language_t *get_current_lang()
{
    return &languages[current_lang];
}
