/*
 * Copyright (C) 2025 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v2.0.1
 */

#include "ui_init.h"
#include "ui_util.h"
#include "aic_ui.h"
#include "custom/custom.h"

ui_manager_t ui_manager;


void ui_init(void)
{
    aic_font_list_init();

    // auto delete screen
    ui_manager_init(&ui_manager, false);

    bread_main_menu_create(&ui_manager);
    lv_scr_load(bread_main_menu_get(&ui_manager)->obj);

    // custom code
    custom_init();
}
