/*
 * Copyright (C) 2025 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v1.3.0
 */

#ifndef CUSTOM_CODE
#define CUSTOM_CODE
#ifdef __cplusplus
extern "C" {
#endif

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"

void custom_init();

#ifdef __cplusplus
}
#endif
#endif /* CUSTOM_CODE */
