/*
 * Copyright (C) 2025 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v2.0.1
 */

#include <stdlib.h>
#include <string.h>
#include "font_list.h"

typedef struct {
    int font_id;
    int font_size;
    const lv_font_t *font;
} font_node_t;

static lv_ll_t font_list;

void aic_font_list_init()
{
    _lv_ll_init(&font_list, sizeof(font_node_t));
}

void aic_font_list_add(int font_id, int font_size, const lv_font_t *font)
{
    font_node_t *new_node = (font_node_t *)_lv_ll_ins_head(&font_list);
    if (!new_node) {
        LV_LOG_ERROR("Failed to allocate memory for new font node");
        return;
    }

    new_node->font_id = font_id;
    new_node->font_size = font_size;
    new_node->font = font;
}

const lv_font_t *aic_font_list_find(int font_id, int font_size)
{
    font_node_t *node = _lv_ll_get_head(&font_list);
    while(node != NULL) {
        if (node->font_id == font_id && node->font_size == font_size) {
            return node->font;
        }
        node = _lv_ll_get_next(&font_list, node);
    }
    return NULL;
}
