/*
 * Copyright (C) 2025 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v2.0.1
 */

#ifndef _UI_OBJECTS
#define _UI_OBJECTS

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"
#include "lv_conf_custom.h"
#include "aic_lang.h"

typedef struct {
    lv_obj_t *obj;
    lv_obj_t *main_menu_bg;
    lv_obj_t *deforst_btn;
    lv_obj_t *heat_btn;
    lv_obj_t *power_label;
    lv_obj_t *set_time_btn;
    lv_obj_t *start_btn;
    lv_obj_t *defrost_img;
    lv_obj_t *heat_img;
    lv_obj_t *bread_container;
    lv_obj_t *bread1_img;
    lv_obj_t *bread2_img;
    lv_obj_t *bread3_img;
    lv_obj_t *bread4_img;
    lv_obj_t *bread5_img;
    lv_obj_t *bread6_img;
    lv_obj_t *time_img;
    lv_obj_t *heat_selected_img;
    lv_obj_t *deforst_selected_img;
    lv_obj_t *temp_container;
    lv_obj_t *tem_img_heat;
    lv_obj_t *tem_img_deforst;
    lv_obj_t *tem_value;
    lv_obj_t *tip;
    lv_obj_t *cancel_btn;
    lv_obj_t *bt_label;
    lv_obj_t *settings_label;
    lv_obj_t *settings_img;
    lv_obj_t *bt_img;
    lv_obj_t *power_img;
    lv_obj_t *player_1;
} bread_main_menu_t;

typedef struct {
    lv_obj_t *obj;
    lv_obj_t *time_menu_bg;
    lv_obj_t *time_container;
    lv_obj_t *hour_container;
    lv_obj_t *image_17;
    lv_obj_t *minute_container;
    lv_obj_t *image_2;
    lv_obj_t *back_btn;
    lv_obj_t *back_img;
    lv_obj_t *container_2;
    lv_obj_t *countdown_btn;
    lv_obj_t *ap_time_btn;
    lv_obj_t *set_time_selected;
    lv_obj_t *ap_time_normal;
    lv_obj_t *time_type_label;
    lv_obj_t *ap_time_selected;
    lv_obj_t *set_time_normal;
} bread_time_menu_t;

typedef struct {
    lv_obj_t *obj;
    lv_obj_t *bt_menu_bg;
    lv_obj_t *back_btn;
    lv_obj_t *power_label;
    lv_obj_t *bt_label;
    lv_obj_t *settings_label;
    lv_obj_t *back_img;
    lv_obj_t *QRcode;
    lv_obj_t *settings_img;
    lv_obj_t *bt_img;
    lv_obj_t *power_img;
} bread_bt_menu_t;

typedef struct {
    lv_obj_t *obj;
    lv_obj_t *bg;
    lv_obj_t *back_btn;
    lv_obj_t *power_label;
    lv_obj_t *bt_label;
    lv_obj_t *settings_label;
    lv_obj_t *main_container;
    lv_obj_t *setting1_container;
    lv_obj_t *setting1_label;
    lv_obj_t *lan_switch;
    lv_obj_t *setting2_container;
    lv_obj_t *setting2;
    lv_obj_t *setting2_label;
    lv_obj_t *setting3_container;
    lv_obj_t *setting3;
    lv_obj_t *setting3_label;
    lv_obj_t *setting4_container;
    lv_obj_t *setting4;
    lv_obj_t *setting4_label;
    lv_obj_t *back_img;
    lv_obj_t *settings_img;
    lv_obj_t *bt_img;
    lv_obj_t *power_img;
    lv_obj_t *QRcode;
} bread_setting_menu_t;


typedef struct {
    bool auto_del;
    bread_main_menu_t bread_main_menu;
    bread_time_menu_t bread_time_menu;
    bread_bt_menu_t bread_bt_menu;
    bread_setting_menu_t bread_setting_menu;

} ui_manager_t;

static inline void ui_manager_init(ui_manager_t *ui, bool auto_del)
{
    memset(ui, 0 , sizeof(ui_manager_t));
    ui->auto_del = auto_del;
}

static inline bread_main_menu_t *bread_main_menu_get(ui_manager_t *ui)
{
    return &ui->bread_main_menu;
}

static inline bread_time_menu_t *bread_time_menu_get(ui_manager_t *ui)
{
    return &ui->bread_time_menu;
}

static inline bread_bt_menu_t *bread_bt_menu_get(ui_manager_t *ui)
{
    return &ui->bread_bt_menu;
}

static inline bread_setting_menu_t *bread_setting_menu_get(ui_manager_t *ui)
{
    return &ui->bread_setting_menu;
}


void bread_main_menu_create(ui_manager_t *ui);
void bread_time_menu_create(ui_manager_t *ui);
void bread_bt_menu_create(ui_manager_t *ui);
void bread_setting_menu_create(ui_manager_t *ui);

void bread_main_menu_update_language(lang_type_t lang);
void bread_main_menu_update_current_language();
void bread_time_menu_update_language(lang_type_t lang);
void bread_time_menu_update_current_language();
void bread_bt_menu_update_language(lang_type_t lang);
void bread_bt_menu_update_current_language();
void bread_setting_menu_update_language(lang_type_t lang);
void bread_setting_menu_update_current_language();



extern ui_manager_t ui_manager;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif // _UI_OBJECTS
