/*
 * Copyright (C) 2025 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v2.0.1
 */

#ifndef FONT_LIST_H
#define FONT_LIST_H
#include "lvgl.h"

void aic_font_list_init();

const lv_font_t *aic_font_list_find(int font_id, int font_size);

void aic_font_list_add(int font_id, int font_size, const lv_font_t *font);

#endif // FONT_LIST_H
