# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.29

# The generator used is:
set(CMAKE_DEPENDS_GENERATOR "MinGW Makefiles")

# The top level Makefile was generated from the following files:
set(CMAKE_MAKEFILE_DEPENDS
  "CMakeCache.txt"
  "D:/Program Files (x86)/AiUIBuilder/tool/cmake/share/cmake-3.29/Modules/CMakeCInformation.cmake"
  "D:/Program Files (x86)/AiUIBuilder/tool/cmake/share/cmake-3.29/Modules/CMakeCXXInformation.cmake"
  "D:/Program Files (x86)/AiUIBuilder/tool/cmake/share/cmake-3.29/Modules/CMakeCommonLanguageInclude.cmake"
  "D:/Program Files (x86)/AiUIBuilder/tool/cmake/share/cmake-3.29/Modules/CMakeGenericSystem.cmake"
  "D:/Program Files (x86)/AiUIBuilder/tool/cmake/share/cmake-3.29/Modules/CMakeInitializeConfigs.cmake"
  "D:/Program Files (x86)/AiUIBuilder/tool/cmake/share/cmake-3.29/Modules/CMakeLanguageInformation.cmake"
  "D:/Program Files (x86)/AiUIBuilder/tool/cmake/share/cmake-3.29/Modules/CMakeRCInformation.cmake"
  "D:/Program Files (x86)/AiUIBuilder/tool/cmake/share/cmake-3.29/Modules/CMakeSystemSpecificInformation.cmake"
  "D:/Program Files (x86)/AiUIBuilder/tool/cmake/share/cmake-3.29/Modules/CMakeSystemSpecificInitialize.cmake"
  "D:/Program Files (x86)/AiUIBuilder/tool/cmake/share/cmake-3.29/Modules/Compiler/CMakeCommonCompilerMacros.cmake"
  "D:/Program Files (x86)/AiUIBuilder/tool/cmake/share/cmake-3.29/Modules/Compiler/GNU-C.cmake"
  "D:/Program Files (x86)/AiUIBuilder/tool/cmake/share/cmake-3.29/Modules/Compiler/GNU-CXX.cmake"
  "D:/Program Files (x86)/AiUIBuilder/tool/cmake/share/cmake-3.29/Modules/Compiler/GNU.cmake"
  "D:/Program Files (x86)/AiUIBuilder/tool/cmake/share/cmake-3.29/Modules/Platform/Windows-GNU-C-ABI.cmake"
  "D:/Program Files (x86)/AiUIBuilder/tool/cmake/share/cmake-3.29/Modules/Platform/Windows-GNU-C.cmake"
  "D:/Program Files (x86)/AiUIBuilder/tool/cmake/share/cmake-3.29/Modules/Platform/Windows-GNU-CXX-ABI.cmake"
  "D:/Program Files (x86)/AiUIBuilder/tool/cmake/share/cmake-3.29/Modules/Platform/Windows-GNU-CXX.cmake"
  "D:/Program Files (x86)/AiUIBuilder/tool/cmake/share/cmake-3.29/Modules/Platform/Windows-GNU.cmake"
  "D:/Program Files (x86)/AiUIBuilder/tool/cmake/share/cmake-3.29/Modules/Platform/Windows-Initialize.cmake"
  "D:/Program Files (x86)/AiUIBuilder/tool/cmake/share/cmake-3.29/Modules/Platform/Windows-windres.cmake"
  "D:/Program Files (x86)/AiUIBuilder/tool/cmake/share/cmake-3.29/Modules/Platform/Windows.cmake"
  "D:/Program Files (x86)/AiUIBuilder/tool/cmake/share/cmake-3.29/Modules/Platform/WindowsPaths.cmake"
  "F:/AiUlBuilder/LVGL/test_view/simulator/CMakeLists.txt"
  "CMakeFiles/3.29.1/CMakeCCompiler.cmake"
  "CMakeFiles/3.29.1/CMakeCXXCompiler.cmake"
  "CMakeFiles/3.29.1/CMakeRCCompiler.cmake"
  "CMakeFiles/3.29.1/CMakeSystem.cmake"
  )

# The corresponding makefile is:
set(CMAKE_MAKEFILE_OUTPUTS
  "Makefile"
  "CMakeFiles/cmake.check_cache"
  )

# Byproducts of CMake generate step:
set(CMAKE_MAKEFILE_PRODUCTS
  "CMakeFiles/CMakeDirectoryInformation.cmake"
  )

# Dependency information for all targets:
set(CMAKE_DEPEND_INFO_FILES
  "CMakeFiles/main.dir/DependInfo.cmake"
  )
