/*
 * Copyright (C) 2025 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v2.0.1
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"
#include "aic_lang.h"
#include "lv_aic_player.h"

void __attribute__((weak)) bread_main_menu_custom_created(void) {
}

static void bread_main_menu_deforst_btn_clicked (lv_event_t *e) {
    lv_obj_t *bread_main_menu_tem_img_deforst = bread_main_menu_get(&ui_manager)->tem_img_deforst;
    lv_obj_clear_flag(bread_main_menu_tem_img_deforst, LV_OBJ_FLAG_HIDDEN);
    lv_obj_t *bread_main_menu_tem_img_heat = bread_main_menu_get(&ui_manager)->tem_img_heat;
    lv_obj_add_flag(bread_main_menu_tem_img_heat, LV_OBJ_FLAG_HIDDEN);
    lv_obj_t *bread_main_menu_deforst_selected_img = bread_main_menu_get(&ui_manager)->deforst_selected_img;
    lv_obj_clear_flag(bread_main_menu_deforst_selected_img, LV_OBJ_FLAG_HIDDEN);
    lv_obj_t *bread_main_menu_heat_selected_img = bread_main_menu_get(&ui_manager)->heat_selected_img;
    lv_obj_add_flag(bread_main_menu_heat_selected_img, LV_OBJ_FLAG_HIDDEN);
    lv_obj_t *bread_main_menu_defrost_img = bread_main_menu_get(&ui_manager)->defrost_img;
    lv_obj_add_flag(bread_main_menu_defrost_img, LV_OBJ_FLAG_HIDDEN);
    lv_obj_t *bread_main_menu_heat_img = bread_main_menu_get(&ui_manager)->heat_img;
    lv_obj_clear_flag(bread_main_menu_heat_img, LV_OBJ_FLAG_HIDDEN);
}

static void bread_main_menu_heat_btn_clicked (lv_event_t *e) {
    lv_obj_t *bread_main_menu_tem_img_heat = bread_main_menu_get(&ui_manager)->tem_img_heat;
    lv_obj_clear_flag(bread_main_menu_tem_img_heat, LV_OBJ_FLAG_HIDDEN);
    lv_obj_t *bread_main_menu_tem_img_deforst = bread_main_menu_get(&ui_manager)->tem_img_deforst;
    lv_obj_add_flag(bread_main_menu_tem_img_deforst, LV_OBJ_FLAG_HIDDEN);
    lv_obj_t *bread_main_menu_heat_img = bread_main_menu_get(&ui_manager)->heat_img;
    lv_obj_add_flag(bread_main_menu_heat_img, LV_OBJ_FLAG_HIDDEN);
    lv_obj_t *bread_main_menu_defrost_img = bread_main_menu_get(&ui_manager)->defrost_img;
    lv_obj_clear_flag(bread_main_menu_defrost_img, LV_OBJ_FLAG_HIDDEN);
    lv_obj_t *bread_main_menu_heat_selected_img = bread_main_menu_get(&ui_manager)->heat_selected_img;
    lv_obj_clear_flag(bread_main_menu_heat_selected_img, LV_OBJ_FLAG_HIDDEN);
    lv_obj_t *bread_main_menu_deforst_selected_img = bread_main_menu_get(&ui_manager)->deforst_selected_img;
    lv_obj_add_flag(bread_main_menu_deforst_selected_img, LV_OBJ_FLAG_HIDDEN);
}

static void bread_main_menu_set_time_btn_clicked (lv_event_t *e) {
    lv_obj_t *act_scr = lv_scr_act();
    if (!screen_is_loading(act_scr)) {
        // create bread_time_menu
        bread_time_menu_create(&ui_manager);
        // load bread_time_menu
        lv_scr_load_anim(bread_time_menu_get(&ui_manager)->obj, LV_SCR_LOAD_ANIM_NONE, 0, 0, ui_manager.auto_del);
    }
}

void __attribute__((weak)) bread_main_menu_start_btn_custom_clicked(void) {
}

static void bread_main_menu_start_btn_clicked (lv_event_t *e) {
    bread_main_menu_start_btn_custom_clicked();
    lv_obj_t *bread_main_menu_tip = bread_main_menu_get(&ui_manager)->tip;
    lv_obj_clear_flag(bread_main_menu_tip, LV_OBJ_FLAG_HIDDEN);
    lv_obj_t *bread_main_menu_cancel_btn = bread_main_menu_get(&ui_manager)->cancel_btn;
    lv_obj_clear_flag(bread_main_menu_cancel_btn, LV_OBJ_FLAG_HIDDEN);
    lv_obj_t *bread_main_menu_set_time_btn = bread_main_menu_get(&ui_manager)->set_time_btn;
    lv_obj_clear_flag(bread_main_menu_set_time_btn, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_t *bread_main_menu_deforst_btn = bread_main_menu_get(&ui_manager)->deforst_btn;
    lv_obj_clear_flag(bread_main_menu_deforst_btn, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_t *bread_main_menu_heat_btn = bread_main_menu_get(&ui_manager)->heat_btn;
    lv_obj_clear_flag(bread_main_menu_heat_btn, LV_OBJ_FLAG_CLICKABLE);
}

static void bread_main_menu_time_img_clicked (lv_event_t *e) {
    lv_obj_t *act_scr = lv_scr_act();
    if (!screen_is_loading(act_scr)) {
        // create bread_time_menu
        bread_time_menu_create(&ui_manager);
        // load bread_time_menu
        lv_scr_load_anim(bread_time_menu_get(&ui_manager)->obj, LV_SCR_LOAD_ANIM_NONE, 0, 0, ui_manager.auto_del);
    }
}

void __attribute__((weak)) bread_main_menu_cancel_btn_custom_clicked(void) {
}

static void bread_main_menu_cancel_btn_clicked (lv_event_t *e) {
    bread_main_menu_cancel_btn_custom_clicked();
    lv_obj_t *bread_main_menu_tip = bread_main_menu_get(&ui_manager)->tip;
    lv_obj_add_flag(bread_main_menu_tip, LV_OBJ_FLAG_HIDDEN);
    lv_obj_t *bread_main_menu_cancel_btn = bread_main_menu_get(&ui_manager)->cancel_btn;
    lv_obj_add_flag(bread_main_menu_cancel_btn, LV_OBJ_FLAG_HIDDEN);
    lv_obj_t *bread_main_menu_deforst_btn = bread_main_menu_get(&ui_manager)->deforst_btn;
    lv_obj_add_flag(bread_main_menu_deforst_btn, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_t *bread_main_menu_heat_btn = bread_main_menu_get(&ui_manager)->heat_btn;
    lv_obj_add_flag(bread_main_menu_heat_btn, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_t *bread_main_menu_set_time_btn = bread_main_menu_get(&ui_manager)->set_time_btn;
    lv_obj_add_flag(bread_main_menu_set_time_btn, LV_OBJ_FLAG_CLICKABLE);
}

static void bread_main_menu_bt_label_clicked (lv_event_t *e) {
    lv_obj_t *act_scr = lv_scr_act();
    if (!screen_is_loading(act_scr)) {
        // create bread_bt_menu
        bread_bt_menu_create(&ui_manager);
        // load bread_bt_menu
        lv_scr_load_anim(bread_bt_menu_get(&ui_manager)->obj, LV_SCR_LOAD_ANIM_NONE, 0, 0, ui_manager.auto_del);
    }
}

static void bread_main_menu_settings_label_clicked (lv_event_t *e) {
    lv_obj_t *act_scr = lv_scr_act();
    if (!screen_is_loading(act_scr)) {
        // create bread_setting_menu
        bread_setting_menu_create(&ui_manager);
        // load bread_setting_menu
        lv_scr_load_anim(bread_setting_menu_get(&ui_manager)->obj, LV_SCR_LOAD_ANIM_NONE, 0, 0, ui_manager.auto_del);
    }
}

static void bread_main_menu_settings_img_clicked (lv_event_t *e) {
    lv_obj_t *act_scr = lv_scr_act();
    if (!screen_is_loading(act_scr)) {
        // create bread_setting_menu
        bread_setting_menu_create(&ui_manager);
        // load bread_setting_menu
        lv_scr_load_anim(bread_setting_menu_get(&ui_manager)->obj, LV_SCR_LOAD_ANIM_NONE, 0, 0, ui_manager.auto_del);
    }
}

static void bread_main_menu_bt_img_clicked (lv_event_t *e) {
    lv_obj_t *act_scr = lv_scr_act();
    if (!screen_is_loading(act_scr)) {
        // create bread_bt_menu
        bread_bt_menu_create(&ui_manager);
        // load bread_bt_menu
        lv_scr_load_anim(bread_bt_menu_get(&ui_manager)->obj, LV_SCR_LOAD_ANIM_NONE, 0, 0, ui_manager.auto_del);
    }
}


void bread_main_menu_create(ui_manager_t *ui)
{
    bread_main_menu_t *scr = bread_main_menu_get(ui);

    if (!ui->auto_del && scr->obj) {
        bread_main_menu_update_current_language();
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0xfcfcfc), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->main_menu_bg
    scr->main_menu_bg = lv_img_create(scr->obj);
    lv_img_set_src(scr->main_menu_bg, LVGL_IMAGE_PATH(bread_bg.png));
    lv_img_set_pivot(scr->main_menu_bg, 50, 50);
    lv_img_set_angle(scr->main_menu_bg, 0);
    lv_obj_set_style_img_opa(scr->main_menu_bg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->main_menu_bg, 0, 0);

    // Init scr->deforst_btn
    scr->deforst_btn = lv_label_create(scr->obj);
    lv_label_set_text(scr->deforst_btn, aic_get_translation(defrost));
    lv_label_set_long_mode(scr->deforst_btn, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->deforst_btn, 25, 400);
    lv_obj_set_size(scr->deforst_btn, 155, 60);
    lv_obj_add_flag(scr->deforst_btn, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->deforst_btn
    lv_obj_set_style_bg_img_src(scr->deforst_btn, LVGL_IMAGE_PATH(bread_machine_main_menu/Sketchpad.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->deforst_btn, aic_get_multi_lang_font(20), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->deforst_btn, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->deforst_btn, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->deforst_btn, 23, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->deforst_btn
    lv_obj_add_event_cb(scr->deforst_btn, bread_main_menu_deforst_btn_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->heat_btn
    scr->heat_btn = lv_label_create(scr->obj);
    lv_label_set_text(scr->heat_btn, aic_get_translation(heat));
    lv_label_set_long_mode(scr->heat_btn, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->heat_btn, 25, 475);
    lv_obj_set_size(scr->heat_btn, 155, 60);
    lv_obj_add_flag(scr->heat_btn, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->heat_btn
    lv_obj_set_style_bg_img_src(scr->heat_btn, LVGL_IMAGE_PATH(bread_machine_main_menu/Sketchpad.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->heat_btn, aic_get_multi_lang_font(20), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->heat_btn, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->heat_btn, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->heat_btn, 25, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->heat_btn
    lv_obj_add_event_cb(scr->heat_btn, bread_main_menu_heat_btn_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->power_label
    scr->power_label = lv_label_create(scr->obj);
    lv_label_set_text(scr->power_label, aic_get_translation(power));
    lv_label_set_long_mode(scr->power_label, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->power_label, 770, 55);
    lv_obj_set_size(scr->power_label, 100, 20);

    // Set style of scr->power_label
    lv_obj_set_style_text_font(scr->power_label, aic_get_multi_lang_font(16), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->power_label, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->power_label, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->set_time_btn
    scr->set_time_btn = lv_label_create(scr->obj);
    lv_label_set_text(scr->set_time_btn, aic_get_translation(time));
    lv_label_set_long_mode(scr->set_time_btn, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->set_time_btn, 850, 400);
    lv_obj_set_size(scr->set_time_btn, 155, 60);
    lv_obj_add_flag(scr->set_time_btn, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->set_time_btn
    lv_obj_set_style_bg_img_src(scr->set_time_btn, LVGL_IMAGE_PATH(bread_machine_main_menu/Sketchpad.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->set_time_btn, aic_get_multi_lang_font(20), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->set_time_btn, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->set_time_btn, 17, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->set_time_btn, 40, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->set_time_btn
    lv_obj_add_event_cb(scr->set_time_btn, bread_main_menu_set_time_btn_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->start_btn
    scr->start_btn = lv_btn_create(scr->obj);
    lv_obj_t *start_btn_label = lv_label_create(scr->start_btn);
    lv_label_set_text(start_btn_label, aic_get_translation(start));
    lv_obj_align(start_btn_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->start_btn, 850, 473);
    lv_obj_set_size(scr->start_btn, 155, 60);

    // Set style of scr->start_btn
    lv_obj_set_style_bg_opa(scr->start_btn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->start_btn, LVGL_IMAGE_PATH(bread_machine_main_menu/Sketchpad.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->start_btn, aic_get_multi_lang_font(20), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->start_btn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->start_btn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(scr->start_btn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->start_btn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->start_btn
    lv_obj_add_event_cb(scr->start_btn, bread_main_menu_start_btn_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->defrost_img
    scr->defrost_img = lv_img_create(scr->obj);
    lv_img_set_src(scr->defrost_img, LVGL_IMAGE_PATH(bread_machine_main_menu/thaw_40x40.png));
    lv_img_set_pivot(scr->defrost_img, 50, 50);
    lv_img_set_angle(scr->defrost_img, 0);
    lv_obj_set_style_img_opa(scr->defrost_img, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->defrost_img, 35, 408);

    // Init scr->heat_img
    scr->heat_img = lv_img_create(scr->obj);
    lv_img_set_src(scr->heat_img, LVGL_IMAGE_PATH(bread_machine_main_menu/heating_40x40.png));
    lv_img_set_pivot(scr->heat_img, 50, 50);
    lv_img_set_angle(scr->heat_img, 0);
    lv_obj_set_style_img_opa(scr->heat_img, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->heat_img, 35, 483);

    // Init scr->bread_container
    scr->bread_container = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->bread_container, 12, 128);
    lv_obj_set_size(scr->bread_container, 1000, 240);
    lv_obj_set_scrollbar_mode(scr->bread_container, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->bread_container
    lv_obj_set_style_bg_color(scr->bread_container, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->bread_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->bread_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->bread_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->bread_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->bread_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->bread_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->bread_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->bread1_img
    scr->bread1_img = lv_img_create(scr->bread_container);
    lv_img_set_src(scr->bread1_img, LVGL_IMAGE_PATH(bread/bread1.png));
    lv_img_set_pivot(scr->bread1_img, 50, 50);
    lv_img_set_angle(scr->bread1_img, 0);
    lv_obj_set_style_img_opa(scr->bread1_img, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->bread1_img, -50, 0);
    lv_obj_add_flag(scr->bread1_img, LV_OBJ_FLAG_HIDDEN);

    // Init scr->bread2_img
    scr->bread2_img = lv_img_create(scr->bread_container);
    lv_img_set_src(scr->bread2_img, LVGL_IMAGE_PATH(bread/bread2.png));
    lv_img_set_pivot(scr->bread2_img, 50, 50);
    lv_img_set_angle(scr->bread2_img, 0);
    lv_obj_set_style_img_opa(scr->bread2_img, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->bread2_img, 150, 0);
    lv_obj_add_flag(scr->bread2_img, LV_OBJ_FLAG_HIDDEN);

    // Init scr->bread3_img
    scr->bread3_img = lv_img_create(scr->bread_container);
    lv_img_set_src(scr->bread3_img, LVGL_IMAGE_PATH(bread/bread3.png));
    lv_img_set_pivot(scr->bread3_img, 50, 50);
    lv_img_set_angle(scr->bread3_img, 0);
    lv_obj_set_style_img_opa(scr->bread3_img, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->bread3_img, 400, 0);
    lv_obj_add_flag(scr->bread3_img, LV_OBJ_FLAG_HIDDEN);

    // Init scr->bread4_img
    scr->bread4_img = lv_img_create(scr->bread_container);
    lv_img_set_src(scr->bread4_img, LVGL_IMAGE_PATH(bread/bread4.png));
    lv_img_set_pivot(scr->bread4_img, 50, 50);
    lv_img_set_angle(scr->bread4_img, 0);
    lv_obj_set_style_img_opa(scr->bread4_img, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->bread4_img, 650, 0);
    lv_obj_add_flag(scr->bread4_img, LV_OBJ_FLAG_HIDDEN);

    // Init scr->bread5_img
    scr->bread5_img = lv_img_create(scr->bread_container);
    lv_img_set_src(scr->bread5_img, LVGL_IMAGE_PATH(bread/bread5.png));
    lv_img_set_pivot(scr->bread5_img, 50, 50);
    lv_img_set_angle(scr->bread5_img, 0);
    lv_obj_set_style_img_opa(scr->bread5_img, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->bread5_img, 850, 0);
    lv_obj_add_flag(scr->bread5_img, LV_OBJ_FLAG_HIDDEN);

    // Init scr->bread6_img
    scr->bread6_img = lv_img_create(scr->bread_container);
    lv_img_set_src(scr->bread6_img, LVGL_IMAGE_PATH(bread/bread6.png));
    lv_img_set_pivot(scr->bread6_img, 50, 50);
    lv_img_set_angle(scr->bread6_img, 0);
    lv_obj_set_style_img_opa(scr->bread6_img, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->bread6_img, 1050, 0);
    lv_obj_add_flag(scr->bread6_img, LV_OBJ_FLAG_HIDDEN);

    // Init scr->time_img
    scr->time_img = lv_img_create(scr->obj);
    lv_img_set_src(scr->time_img, LVGL_IMAGE_PATH(bread_machine_main_menu/Time.png));
    lv_img_set_pivot(scr->time_img, 50, 50);
    lv_img_set_angle(scr->time_img, 0);
    lv_obj_set_style_img_opa(scr->time_img, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->time_img, 872, 413);
    lv_obj_add_flag(scr->time_img, LV_OBJ_FLAG_CLICKABLE);

    // Set event handler of scr->time_img
    lv_obj_add_event_cb(scr->time_img, bread_main_menu_time_img_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->heat_selected_img
    scr->heat_selected_img = lv_img_create(scr->obj);
    lv_img_set_src(scr->heat_selected_img, LVGL_IMAGE_PATH(bread_machine_main_menu/heating2_40x40.png));
    lv_img_set_pivot(scr->heat_selected_img, 50, 50);
    lv_img_set_angle(scr->heat_selected_img, 0);
    lv_obj_set_style_img_opa(scr->heat_selected_img, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->heat_selected_img, 35, 483);
    lv_obj_add_flag(scr->heat_selected_img, LV_OBJ_FLAG_HIDDEN);

    // Init scr->deforst_selected_img
    scr->deforst_selected_img = lv_img_create(scr->obj);
    lv_img_set_src(scr->deforst_selected_img, LVGL_IMAGE_PATH(bread_machine_main_menu/thaw2_40x40.png));
    lv_img_set_pivot(scr->deforst_selected_img, 50, 50);
    lv_img_set_angle(scr->deforst_selected_img, 0);
    lv_obj_set_style_img_opa(scr->deforst_selected_img, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->deforst_selected_img, 35, 408);

    // Init scr->temp_container
    scr->temp_container = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->temp_container, 180, 368);
    lv_obj_set_size(scr->temp_container, 668, 200);
    lv_obj_set_scrollbar_mode(scr->temp_container, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->temp_container
    lv_obj_set_style_bg_color(scr->temp_container, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->temp_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->temp_container, LVGL_IMAGE_PATH(bread_machine_main_menu/Sketchpad1.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->temp_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->temp_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->temp_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->temp_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->temp_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->temp_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->tem_img_heat
    scr->tem_img_heat = lv_img_create(scr->temp_container);
    lv_img_set_src(scr->tem_img_heat, LVGL_IMAGE_PATH(bread_machine_main_menu/Slidebar1.png));
    lv_img_set_pivot(scr->tem_img_heat, 50, 50);
    lv_img_set_angle(scr->tem_img_heat, 0);
    lv_obj_set_style_img_opa(scr->tem_img_heat, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->tem_img_heat, 70, 65);
    lv_obj_add_flag(scr->tem_img_heat, LV_OBJ_FLAG_HIDDEN);

    // Init scr->tem_img_deforst
    scr->tem_img_deforst = lv_img_create(scr->temp_container);
    lv_img_set_src(scr->tem_img_deforst, LVGL_IMAGE_PATH(bread_machine_main_menu/Slidebar.png));
    lv_img_set_pivot(scr->tem_img_deforst, 50, 50);
    lv_img_set_angle(scr->tem_img_deforst, 0);
    lv_obj_set_style_img_opa(scr->tem_img_deforst, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->tem_img_deforst, 70, 65);

    // Init scr->tem_value
    scr->tem_value = lv_img_create(scr->temp_container);
    lv_img_set_src(scr->tem_value, LVGL_IMAGE_PATH(bread_machine_main_menu/digit.png));
    lv_img_set_pivot(scr->tem_value, 50, 50);
    lv_img_set_angle(scr->tem_value, 0);
    lv_obj_set_style_img_opa(scr->tem_value, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->tem_value, 84, 106);

    // Init scr->tip
    scr->tip = lv_label_create(scr->obj);
    lv_label_set_text(scr->tip, aic_get_translation(heating));
    lv_label_set_long_mode(scr->tip, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->tip, 435, 355);
    lv_obj_set_size(scr->tip, 155, 60);
    lv_obj_add_flag(scr->tip, LV_OBJ_FLAG_HIDDEN);

    // Set style of scr->tip
    lv_obj_set_style_bg_img_src(scr->tip, LVGL_IMAGE_PATH(bread_machine_main_menu/Sketchpad.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->tip, aic_get_multi_lang_font(23), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->tip, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->tip, 11, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->cancel_btn
    scr->cancel_btn = lv_label_create(scr->obj);
    lv_label_set_text(scr->cancel_btn, aic_get_translation(Cancel));
    lv_label_set_long_mode(scr->cancel_btn, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->cancel_btn, 435, 520);
    lv_obj_set_size(scr->cancel_btn, 155, 60);
    lv_obj_add_flag(scr->cancel_btn, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(scr->cancel_btn, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->cancel_btn
    lv_obj_set_style_bg_img_src(scr->cancel_btn, LVGL_IMAGE_PATH(bread_machine_main_menu/Sketchpad.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->cancel_btn, aic_get_multi_lang_font(20), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->cancel_btn, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->cancel_btn, 14, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->cancel_btn
    lv_obj_add_event_cb(scr->cancel_btn, bread_main_menu_cancel_btn_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->bt_label
    scr->bt_label = lv_label_create(scr->obj);
    lv_label_set_text(scr->bt_label, aic_get_translation(bluetooth));
    lv_label_set_long_mode(scr->bt_label, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->bt_label, 845, 55);
    lv_obj_set_size(scr->bt_label, 100, 20);
    lv_obj_add_flag(scr->bt_label, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->bt_label
    lv_obj_set_style_text_font(scr->bt_label, aic_get_multi_lang_font(16), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->bt_label, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->bt_label, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->bt_label
    lv_obj_add_event_cb(scr->bt_label, bread_main_menu_bt_label_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->settings_label
    scr->settings_label = lv_label_create(scr->obj);
    lv_label_set_text(scr->settings_label, aic_get_translation(settings));
    lv_label_set_long_mode(scr->settings_label, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->settings_label, 920, 55);
    lv_obj_set_size(scr->settings_label, 100, 20);
    lv_obj_add_flag(scr->settings_label, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->settings_label
    lv_obj_set_style_text_font(scr->settings_label, aic_get_multi_lang_font(16), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->settings_label, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->settings_label, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->settings_label
    lv_obj_add_event_cb(scr->settings_label, bread_main_menu_settings_label_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->settings_img
    scr->settings_img = lv_img_create(scr->obj);
    lv_img_set_src(scr->settings_img, LVGL_IMAGE_PATH(bread_machine_main_menu/set_up.png));
    lv_img_set_pivot(scr->settings_img, 50, 50);
    lv_img_set_angle(scr->settings_img, 0);
    lv_obj_set_style_img_opa(scr->settings_img, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->settings_img, 953, 20);
    lv_obj_add_flag(scr->settings_img, LV_OBJ_FLAG_CLICKABLE);

    // Set event handler of scr->settings_img
    lv_obj_add_event_cb(scr->settings_img, bread_main_menu_settings_img_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->bt_img
    scr->bt_img = lv_img_create(scr->obj);
    lv_img_set_src(scr->bt_img, LVGL_IMAGE_PATH(bread_machine_main_menu/Bluetooth.png));
    lv_img_set_pivot(scr->bt_img, 50, 50);
    lv_img_set_angle(scr->bt_img, 0);
    lv_obj_set_style_img_opa(scr->bt_img, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->bt_img, 880, 18);
    lv_obj_add_flag(scr->bt_img, LV_OBJ_FLAG_CLICKABLE);

    // Set event handler of scr->bt_img
    lv_obj_add_event_cb(scr->bt_img, bread_main_menu_bt_img_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->power_img
    scr->power_img = lv_img_create(scr->obj);
    lv_img_set_src(scr->power_img, LVGL_IMAGE_PATH(bread_machine_main_menu/Open.png));
    lv_img_set_pivot(scr->power_img, 50, 50);
    lv_img_set_angle(scr->power_img, 0);
    lv_obj_set_style_img_opa(scr->power_img, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->power_img, 798, 16);

    // Init scr->player_1
    scr->player_1 = lv_aic_player_create(scr->obj);
    lv_aic_player_set_src(scr->player_1, LVGL_VIDEO_PATH(10s.mp4));
    lv_aic_player_set_cmd(scr->player_1, LV_AIC_PLAYER_CMD_START, NULL);
    lv_obj_set_pos(scr->player_1, 58, 37);
    lv_obj_set_size(scr->player_1, 874, 530);

    bread_main_menu_custom_created();
}

void bread_main_menu_update_language(lang_type_t lang)
{
    aic_set_language(lang);
    bread_main_menu_update_current_language();
}

void bread_main_menu_update_current_language()
{
    bread_main_menu_t *scr = bread_main_menu_get(&ui_manager);
    lv_obj_set_style_text_font(scr->deforst_btn, aic_get_multi_lang_font(20), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_label_set_text(scr->deforst_btn, aic_get_translation(defrost));

    lv_obj_set_style_text_font(scr->heat_btn, aic_get_multi_lang_font(20), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_label_set_text(scr->heat_btn, aic_get_translation(heat));

    lv_obj_set_style_text_font(scr->power_label, aic_get_multi_lang_font(16), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_label_set_text(scr->power_label, aic_get_translation(power));

    lv_obj_set_style_text_font(scr->set_time_btn, aic_get_multi_lang_font(20), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_label_set_text(scr->set_time_btn, aic_get_translation(time));

    lv_obj_set_style_text_font(scr->start_btn, aic_get_multi_lang_font(20), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_label_set_text(lv_obj_get_child(scr->start_btn, 0), aic_get_translation(start));

    lv_obj_set_style_text_font(scr->tip, aic_get_multi_lang_font(23), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_label_set_text(scr->tip, aic_get_translation(heating));

    lv_obj_set_style_text_font(scr->cancel_btn, aic_get_multi_lang_font(20), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_label_set_text(scr->cancel_btn, aic_get_translation(Cancel));

    lv_obj_set_style_text_font(scr->bt_label, aic_get_multi_lang_font(16), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_label_set_text(scr->bt_label, aic_get_translation(bluetooth));

    lv_obj_set_style_text_font(scr->settings_label, aic_get_multi_lang_font(16), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_label_set_text(scr->settings_label, aic_get_translation(settings));

}

