/*
 * Copyright (C) 2025 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v2.0.1
 */

#ifndef AIC_LANG_H
#define AIC_LANG_H
#include "lvgl.h"
#include "font_list.h"

typedef enum {
    AIC_LANG_EN,
    AIC_LANG_JP,
    AIC_LANG_ZH
} lang_type_t;

typedef struct {
    char *lan_name;
    int font_id;
    bool c_flag;
} aic_language_t;

typedef enum {
    Appointment,
    Cancel,
    bluetooth,
    chinese_lan,
    countdown,
    defrost,
    english_lan,
    heat,
    heating,
    introduction,
    japanese_lan,
    language,
    power,
    return1,
    settings,
    start,
    time,
    usage,
    version,
    version_num
} key_id_t;

#define DROIDSANSFALLBACK_TTF 0

void aic_set_language(lang_type_t lang);

const char *aic_get_translation(key_id_t key);

const lv_font_t *aic_init_lang_font(int font_id, int font_size);

const lv_font_t *aic_get_lang_font(int font_id, int font_size, bool c_flag);

const lv_font_t *aic_get_multi_lang_font(int font_size);

const lv_font_t *aic_get_c_font(int font_id, int font_size);

const aic_language_t *get_current_lang();

#endif // AIC_LANG_H
