/*
 * Copyright (C) 2025 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v2.0.1
 */

#ifndef _UI_INIT_H
#define _UI_INIT_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdio.h>
#include "ui_objects.h"

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif // _UI_INIT_H
