/*
 * Copyright (C) 2025 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v2.0.1
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"
#include "aic_lang.h"
#include "lv_aic_player.h"

void __attribute__((weak)) bread_time_menu_custom_created(void) {
}

static void bread_time_menu_back_btn_clicked (lv_event_t *e) {
    lv_obj_t *act_scr = lv_scr_act();
    if (!screen_is_loading(act_scr)) {
        // create bread_main_menu
        bread_main_menu_create(&ui_manager);
        // load bread_main_menu
        lv_scr_load_anim(bread_main_menu_get(&ui_manager)->obj, LV_SCR_LOAD_ANIM_NONE, 0, 0, ui_manager.auto_del);
    }
}

static void bread_time_menu_countdown_btn_clicked (lv_event_t *e) {
    lv_obj_t *bread_time_menu_set_time_selected = bread_time_menu_get(&ui_manager)->set_time_selected;
    lv_obj_clear_flag(bread_time_menu_set_time_selected, LV_OBJ_FLAG_HIDDEN);
    lv_obj_t *bread_time_menu_ap_time_normal = bread_time_menu_get(&ui_manager)->ap_time_normal;
    lv_obj_clear_flag(bread_time_menu_ap_time_normal, LV_OBJ_FLAG_HIDDEN);
    lv_obj_t *bread_time_menu_set_time_normal = bread_time_menu_get(&ui_manager)->set_time_normal;
    lv_obj_add_flag(bread_time_menu_set_time_normal, LV_OBJ_FLAG_HIDDEN);
    lv_obj_t *bread_time_menu_ap_time_selected = bread_time_menu_get(&ui_manager)->ap_time_selected;
    lv_obj_add_flag(bread_time_menu_ap_time_selected, LV_OBJ_FLAG_HIDDEN);
}

static void bread_time_menu_ap_time_btn_clicked (lv_event_t *e) {
    lv_obj_t *bread_time_menu_set_time_normal = bread_time_menu_get(&ui_manager)->set_time_normal;
    lv_obj_clear_flag(bread_time_menu_set_time_normal, LV_OBJ_FLAG_HIDDEN);
    lv_obj_t *bread_time_menu_ap_time_selected = bread_time_menu_get(&ui_manager)->ap_time_selected;
    lv_obj_clear_flag(bread_time_menu_ap_time_selected, LV_OBJ_FLAG_HIDDEN);
    lv_obj_t *bread_time_menu_ap_time_normal = bread_time_menu_get(&ui_manager)->ap_time_normal;
    lv_obj_add_flag(bread_time_menu_ap_time_normal, LV_OBJ_FLAG_HIDDEN);
    lv_obj_t *bread_time_menu_set_time_selected = bread_time_menu_get(&ui_manager)->set_time_selected;
    lv_obj_add_flag(bread_time_menu_set_time_selected, LV_OBJ_FLAG_HIDDEN);
}

static void bread_time_menu_ap_time_normal_clicked (lv_event_t *e) {
    lv_obj_t *bread_time_menu_set_time_normal = bread_time_menu_get(&ui_manager)->set_time_normal;
    lv_obj_clear_flag(bread_time_menu_set_time_normal, LV_OBJ_FLAG_HIDDEN);
    lv_obj_t *bread_time_menu_ap_time_selected = bread_time_menu_get(&ui_manager)->ap_time_selected;
    lv_obj_clear_flag(bread_time_menu_ap_time_selected, LV_OBJ_FLAG_HIDDEN);
    lv_obj_t *bread_time_menu_ap_time_normal = bread_time_menu_get(&ui_manager)->ap_time_normal;
    lv_obj_add_flag(bread_time_menu_ap_time_normal, LV_OBJ_FLAG_HIDDEN);
    lv_obj_t *bread_time_menu_set_time_selected = bread_time_menu_get(&ui_manager)->set_time_selected;
    lv_obj_add_flag(bread_time_menu_set_time_selected, LV_OBJ_FLAG_HIDDEN);
}

static void bread_time_menu_set_time_normal_clicked (lv_event_t *e) {
    lv_obj_t *bread_time_menu_set_time_normal = bread_time_menu_get(&ui_manager)->set_time_normal;
    lv_obj_add_flag(bread_time_menu_set_time_normal, LV_OBJ_FLAG_HIDDEN);
    lv_obj_t *bread_time_menu_ap_time_selected = bread_time_menu_get(&ui_manager)->ap_time_selected;
    lv_obj_add_flag(bread_time_menu_ap_time_selected, LV_OBJ_FLAG_HIDDEN);
    lv_obj_t *bread_time_menu_ap_time_normal = bread_time_menu_get(&ui_manager)->ap_time_normal;
    lv_obj_clear_flag(bread_time_menu_ap_time_normal, LV_OBJ_FLAG_HIDDEN);
    lv_obj_t *bread_time_menu_set_time_selected = bread_time_menu_get(&ui_manager)->set_time_selected;
    lv_obj_clear_flag(bread_time_menu_set_time_selected, LV_OBJ_FLAG_HIDDEN);
}


void bread_time_menu_create(ui_manager_t *ui)
{
    bread_time_menu_t *scr = bread_time_menu_get(ui);

    if (!ui->auto_del && scr->obj) {
        bread_time_menu_update_current_language();
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0xfcfcfc), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->time_menu_bg
    scr->time_menu_bg = lv_img_create(scr->obj);
    lv_img_set_src(scr->time_menu_bg, LVGL_IMAGE_PATH(bread_bg.png));
    lv_img_set_pivot(scr->time_menu_bg, 50, 50);
    lv_img_set_angle(scr->time_menu_bg, 0);
    lv_obj_set_style_img_opa(scr->time_menu_bg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->time_menu_bg, 0, 0);

    // Init scr->time_container
    scr->time_container = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->time_container, 375, 210);
    lv_obj_set_size(scr->time_container, 250, 280);
    lv_obj_set_scrollbar_mode(scr->time_container, LV_SCROLLBAR_MODE_OFF);
    lv_obj_clear_flag(scr->time_container, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_add_flag(scr->time_container, LV_OBJ_FLAG_EVENT_BUBBLE);

    // Set style of scr->time_container
    lv_obj_set_style_bg_color(scr->time_container, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->time_container, LVGL_IMAGE_PATH(bread_time_menu/Sketchpad.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->time_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->time_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->time_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->time_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->time_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->time_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->hour_container
    scr->hour_container = lv_obj_create(scr->time_container);
    lv_obj_set_pos(scr->hour_container, 0, 0);
    lv_obj_set_size(scr->hour_container, 125, 280);
    lv_obj_set_scrollbar_mode(scr->hour_container, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->hour_container
    lv_obj_set_style_bg_color(scr->hour_container, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->hour_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(scr->hour_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->hour_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->hour_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->hour_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->hour_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->hour_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->hour_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_17
    scr->image_17 = lv_img_create(scr->hour_container);
    lv_img_set_src(scr->image_17, LVGL_IMAGE_PATH(bread_time_menu/H_20x20.png));
    lv_img_set_pivot(scr->image_17, 50, 50);
    lv_img_set_angle(scr->image_17, 0);
    lv_obj_set_style_img_opa(scr->image_17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->image_17, 100, 130);

    // Init scr->minute_container
    scr->minute_container = lv_obj_create(scr->time_container);
    lv_obj_set_pos(scr->minute_container, 125, 0);
    lv_obj_set_size(scr->minute_container, 125, 280);
    lv_obj_set_scrollbar_mode(scr->minute_container, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->minute_container
    lv_obj_set_style_bg_color(scr->minute_container, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->minute_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(scr->minute_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->minute_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->minute_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->minute_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->minute_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->minute_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->minute_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_2
    scr->image_2 = lv_img_create(scr->minute_container);
    lv_img_set_src(scr->image_2, LVGL_IMAGE_PATH(bread_time_menu/M_20x20.png));
    lv_img_set_pivot(scr->image_2, 50, 50);
    lv_img_set_angle(scr->image_2, 0);
    lv_obj_set_style_img_opa(scr->image_2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->image_2, 103, 130);

    // Init scr->back_btn
    scr->back_btn = lv_label_create(scr->obj);
    lv_label_set_text(scr->back_btn, aic_get_translation(return1));
    lv_label_set_long_mode(scr->back_btn, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->back_btn, 820, 500);
    lv_obj_set_size(scr->back_btn, 155, 60);
    lv_obj_add_flag(scr->back_btn, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->back_btn
    lv_obj_set_style_bg_img_src(scr->back_btn, LVGL_IMAGE_PATH(bread_settings_menu/Sketchpad2.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->back_btn, aic_get_multi_lang_font(22), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->back_btn, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->back_btn, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->back_btn, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->back_btn
    lv_obj_add_event_cb(scr->back_btn, bread_time_menu_back_btn_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->back_img
    scr->back_img = lv_img_create(scr->obj);
    lv_img_set_src(scr->back_img, LVGL_IMAGE_PATH(bread_time_menu/return.png));
    lv_img_set_pivot(scr->back_img, 50, 50);
    lv_img_set_angle(scr->back_img, 0);
    lv_obj_set_style_img_opa(scr->back_img, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->back_img, 840, 510);

    // Init scr->container_2
    scr->container_2 = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->container_2, 179, 67);
    lv_obj_set_size(scr->container_2, 631, 200);
    lv_obj_set_scrollbar_mode(scr->container_2, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->container_2
    lv_obj_set_style_bg_color(scr->container_2, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->container_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->container_2, LVGL_IMAGE_PATH(bread_time_menu/Sketchpad2.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->container_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->countdown_btn
    scr->countdown_btn = lv_btn_create(scr->container_2);
    lv_obj_t *countdown_btn_label = lv_label_create(scr->countdown_btn);
    lv_label_set_text(countdown_btn_label, aic_get_translation(countdown));
    lv_obj_align(countdown_btn_label, LV_ALIGN_LEFT_MID, 0, 0);
    lv_obj_set_pos(scr->countdown_btn, 289, 79);
    lv_obj_set_size(scr->countdown_btn, 117, 43);

    // Set style of scr->countdown_btn
    lv_obj_set_style_bg_opa(scr->countdown_btn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->countdown_btn, aic_get_multi_lang_font(16), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->countdown_btn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->countdown_btn, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->countdown_btn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->countdown_btn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->countdown_btn
    lv_obj_add_event_cb(scr->countdown_btn, bread_time_menu_countdown_btn_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->ap_time_btn
    scr->ap_time_btn = lv_btn_create(scr->container_2);
    lv_obj_t *ap_time_btn_label = lv_label_create(scr->ap_time_btn);
    lv_label_set_text(ap_time_btn_label, aic_get_translation(Appointment));
    lv_obj_align(ap_time_btn_label, LV_ALIGN_LEFT_MID, 0, 0);
    lv_obj_set_pos(scr->ap_time_btn, 468, 79);
    lv_obj_set_size(scr->ap_time_btn, 128, 43);

    // Set style of scr->ap_time_btn
    lv_obj_set_style_bg_opa(scr->ap_time_btn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->ap_time_btn, aic_get_multi_lang_font(16), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->ap_time_btn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->ap_time_btn, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->ap_time_btn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->ap_time_btn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->ap_time_btn
    lv_obj_add_event_cb(scr->ap_time_btn, bread_time_menu_ap_time_btn_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->set_time_selected
    scr->set_time_selected = lv_img_create(scr->container_2);
    lv_img_set_src(scr->set_time_selected, LVGL_IMAGE_PATH(bread_time_menu/choose.png));
    lv_img_set_pivot(scr->set_time_selected, 50, 50);
    lv_img_set_angle(scr->set_time_selected, 0);
    lv_obj_set_style_img_opa(scr->set_time_selected, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->set_time_selected, 250, 79);

    // Init scr->ap_time_normal
    scr->ap_time_normal = lv_img_create(scr->container_2);
    lv_img_set_src(scr->ap_time_normal, LVGL_IMAGE_PATH(bread_time_menu/Not_selected.png));
    lv_img_set_pivot(scr->ap_time_normal, 50, 50);
    lv_img_set_angle(scr->ap_time_normal, 0);
    lv_obj_set_style_img_opa(scr->ap_time_normal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->ap_time_normal, 427, 79);
    lv_obj_add_flag(scr->ap_time_normal, LV_OBJ_FLAG_CLICKABLE);

    // Set event handler of scr->ap_time_normal
    lv_obj_add_event_cb(scr->ap_time_normal, bread_time_menu_ap_time_normal_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->time_type_label
    scr->time_type_label = lv_label_create(scr->container_2);
    lv_label_set_text(scr->time_type_label, aic_get_translation(time));
    lv_label_set_long_mode(scr->time_type_label, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->time_type_label, 53, 68);
    lv_obj_set_size(scr->time_type_label, 94, 56);

    // Set style of scr->time_type_label
    lv_obj_set_style_text_font(scr->time_type_label, aic_get_multi_lang_font(30), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->time_type_label, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->time_type_label, 11, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->ap_time_selected
    scr->ap_time_selected = lv_img_create(scr->container_2);
    lv_img_set_src(scr->ap_time_selected, LVGL_IMAGE_PATH(bread_time_menu/choose.png));
    lv_img_set_pivot(scr->ap_time_selected, 50, 50);
    lv_img_set_angle(scr->ap_time_selected, 0);
    lv_obj_set_style_img_opa(scr->ap_time_selected, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->ap_time_selected, 427, 79);
    lv_obj_add_flag(scr->ap_time_selected, LV_OBJ_FLAG_HIDDEN);

    // Init scr->set_time_normal
    scr->set_time_normal = lv_img_create(scr->container_2);
    lv_img_set_src(scr->set_time_normal, LVGL_IMAGE_PATH(bread_time_menu/Not_selected.png));
    lv_img_set_pivot(scr->set_time_normal, 50, 50);
    lv_img_set_angle(scr->set_time_normal, 0);
    lv_obj_set_style_img_opa(scr->set_time_normal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->set_time_normal, 250, 79);
    lv_obj_add_flag(scr->set_time_normal, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(scr->set_time_normal, LV_OBJ_FLAG_CLICKABLE);

    // Set event handler of scr->set_time_normal
    lv_obj_add_event_cb(scr->set_time_normal, bread_time_menu_set_time_normal_clicked, LV_EVENT_CLICKED, NULL);

    bread_time_menu_custom_created();
}

void bread_time_menu_update_language(lang_type_t lang)
{
    aic_set_language(lang);
    bread_time_menu_update_current_language();
}

void bread_time_menu_update_current_language()
{
    bread_time_menu_t *scr = bread_time_menu_get(&ui_manager);
    lv_obj_set_style_text_font(scr->back_btn, aic_get_multi_lang_font(22), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_label_set_text(scr->back_btn, aic_get_translation(return1));

    lv_obj_set_style_text_font(scr->countdown_btn, aic_get_multi_lang_font(16), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_label_set_text(lv_obj_get_child(scr->countdown_btn, 0), aic_get_translation(countdown));

    lv_obj_set_style_text_font(scr->ap_time_btn, aic_get_multi_lang_font(16), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_label_set_text(lv_obj_get_child(scr->ap_time_btn, 0), aic_get_translation(Appointment));

    lv_obj_set_style_text_font(scr->time_type_label, aic_get_multi_lang_font(30), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_label_set_text(scr->time_type_label, aic_get_translation(time));

}

